app/views/_flash_msg.html.erb

See https://getbootstrap.com/docs/4.6/components/alerts/\#dismissing

Make the dismiss button accessible

---

spec/features/callnum_search_spec.rb
spec/fixtures/solr_documents/1.yml
spec/rails_helper.rb

closes #3923 
Expands testing suite.

update tests to include call number hierarchy

---

.github/workflows/ruby.yml

update github build config

---

README.md
docker-compose.yml

Add a docker compose file for starting solr

---

spec/fixtures/solr_documents/10.yml

Add Folio data to the fixture for the librarian view

---

app/javascript/location-hours.js

Addresses the time zone issue in #3940.

Force library hours display to Pacific time

---

app/javascript/embedded-call-number-browse.js

Simplify gallery docs code

---

app/assets/stylesheets/searchworks-mixins.scss

Remove unused css mixin

---

app/components/access_panels/location_item_component.rb

We no longer use these delegations

---

app/policies/location_request_link_policy.rb

We no longer need a separate method for the folio way

---

app/assets/stylesheets/modules/browse-embed.scss
app/javascript/embedded-call-number-browse.js

we can move away from sass if we stop using extend

Avoid using sass extend unnecessarily

---

app/assets/stylesheets/modules/browse-embed.scss

This should have been part of https://github.com/sul-dlss/SearchWorks/commit/5e35482a52ff8606b30d5fa1bb6fe23543949a7e#diff-e9c9f2a4b4c514861f555f52001f83856f75efed0763a2aaf08339fa064e9d2f

Remove styles that are never used in the app

---

app/assets/stylesheets/modules/buttons.scss
app/assets/stylesheets/modules/pagination.scss
app/assets/stylesheets/modules/results-documents.scss
app/assets/stylesheets/searchworks.scss
app/assets/stylesheets/sul-variables.scss

Remove unused style for btn-sul-toolbar and pagination

---

lib/constants.rb
lib/holdings/item.rb
spec/components/access_panels/at_the_library_component_spec.rb
spec/lib/holdings/item_spec.rb

None of these codes are used in FOLIO

Remove Symphony reserves locations

---

spec/helpers/browse_helper_spec.rb

Remove unused let variable in test

---

app/assets/stylesheets/modules/record-toolbar.scss

This is already handled by `app/assets/stylesheets/modules/sul-toolbar.scss`

Remove unnecessary style

---

app/assets/stylesheets/modules/record-toolbar.scss

This hasn't worked since the Bootstrap 4 upgrade.
Ref https://github.com/sul-dlss/SearchWorks/pull/3959#issuecomment-1949074540

Remove dead styles

---

app/assets/stylesheets/modules/access-panel-library-locations.scss
app/assets/stylesheets/searchworks-mixins.scss

Reduce unnecessary indirection in css

---

lib/holdings/location.rb

Remove unused conditionals

---

config/settings.yml

Remove unused requestable_current_locations

---

app/policies/location_request_link_policy.rb

We don't need two methods anymore

Consolidate aeon_pageable? and folio_aeon_pageable?

---

app/models/links/ezproxy.rb
spec/lib/holdings/item_spec.rb
spec/models/concerns/index_links_spec.rb
spec/models/links/ezproxy_spec.rb

Use the Folio Lane library code

---

lib/holdings/location.rb

Remove unused methods from Holdings::Location

---

app/components/access_panels/library_location_component.rb
app/components/location_request_link_component.rb
app/components/request_links/hoover_request_link_component.rb
app/policies/location_request_link_policy.rb
app/views/catalog/_index_location.html.erb
spec/components/location_request_link_component_spec.rb
spec/policies/location_request_link_policy_spec.rb

Refactor LocationRequestLinkComponent to avoid passing items

---

app/policies/item_request_link_policy.rb

Presumable left-over from #3515

Remove unused delegations

---

app/controllers/browse_controller.rb
spec/features/callnumber_browse_spec.rb

override blacklight @current_bookmarks for browse view

---

spec/requests/search_for_marc_fields_spec.rb

Add a test for the secret MARC field search feature

---

spec/fixtures/solr_documents/13553090.yml
spec/fixtures/solr_documents/14136548.yml
spec/fixtures/solr_documents/2279186.yml
spec/fixtures/solr_documents/2472159.yml
spec/fixtures/solr_documents/4085072.yml
spec/fixtures/solr_documents/5488000.yml
spec/fixtures/solr_documents/in00000053236.yml

Re-harvest fixtures to remove empty summary_struct fields

---

app/components/access_panels/location_item_component.rb
lib/holdings/item.rb

Handle a nil temporary_location

---

app/javascript/preview-content.js

Remove unnecessary conditional

---

app/javascript/jquery.plug-google-content.js

Use modern javascript

---

Gemfile
app/components/search_result/location_component.rb
app/models/folio/holding.rb
app/services/folio/locations.rb
spec/components/search_result/location_component_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/factories.rb

Only show the bound-with message in the appropriate library

---

app/javascript/jquery.preview-gallery.js
app/views/catalog/_index_gallery.html.erb

closes #3894 
View ticket to see current view. See screenshots below for updated view.

update css for gallery view to responsively fit screen

---

lib/holdings/location.rb
spec/components/access_panels/at_the_library_component_spec.rb
spec/lib/holdings/item_spec.rb
spec/lib/holdings/location_spec.rb

SEE-OTHER is no longer used in the index, so remove it from the code

---

app/javascript/jquery.libraryh3lp.js
app/javascript/jquery.plug-google-content.js
package.json
yarn.lock

This helps us decouple from jquery

Use fetchJsonp for getting jsonp responses

---

app/controllers/browse_controller.rb
app/helpers/browse_helper.rb
app/models/nearby_on_shelf.rb
app/views/catalog/record/_callnumber_browse.html.erb
lib/holdings/spine.rb
spec/controllers/browse_controller_spec.rb
spec/helpers/browse_helper_spec.rb
spec/views/catalog/record/_callnumber_browse.html.erb_spec.rb

Update browse nearby to work with browse spines, not items

---

app/models/folio/library.rb
app/models/solr_document.rb
spec/models/folio/library_spec.rb

Goes with the indexer changes in https://github.com/sul-dlss/searchworks_traject_indexer/pull/1390 so this is decoupled from `item_display_struct` data entirely.

Use holdings_library_code_ssim to look up the eresources owning library

---

app/assets/stylesheets/modules/skip-to-nav.scss

All browsers support border-radius now

Remove browser specific css for border radius

---

app/views/layouts/searchworks.html.erb

This doesn't require the font loader script.

Upgrade to the css2 google font api

---

app/assets/stylesheets/bootstrap-variables.scss
app/views/shared/feedback_forms/_reporting_from.html.erb

update link in alert info to be accessible

---

config/settings.yml
spec/components/location_request_link_component_spec.rb

closes #4197 
Needs to wait on sul-requests rewrite to go live.

restore aged to lost links

---

docker-compose.yml

Remove obsolete version attribute

---

app/views/course_reserves/index.html.erb

Update crez link

---

app/models/links/ezproxy.rb
spec/models/concerns/index_links_spec.rb
spec/models/links/ezproxy_spec.rb

Use holdings_library_code_ssim to check library for ezproxy links

---

app/helpers/collection_helper.rb

add canonical link to header

---

app/javascript/controllers/live_lookup_controller.js

fix due date when using back button

---

app/javascript/backend_lookup.js

fix browser back duplicate results, closes #3643

---

app/controllers/course_reserves_controller.rb
app/services/folio/courses.rb
app/services/folio_client.rb
db/migrate/20240701183130_add_course_status_dates_to_course_reserves.rb
db/schema.rb
spec/controllers/course_reserves_controller_spec.rb
spec/factories/course_reserves.rb

only allow active course reserves to display on show page

---

config/deploy/prod.rb

webapp-a through -e share a common database.

Remove db role from other sw webapp boxes.

---

config/initializers/rack_attack.rb

Similarly separate articles+ search + view throttling.

---

config/initializers/rack_attack.rb

... in order to safe-list e.g. bento

Update rack_attack ranges for local IPs

---

config/initializers/rack_attack.rb

Throttle email, sms, citation and fulltext actions.

---

config/deploy.rb
config/deploy/preview_folio.rb
config/deploy/preview_gryphon.rb
config/deploy/prod.rb
config/deploy/stage.rb
config/deploy/uat.rb
config/schedule.rb

This PR is an alternative to https://github.com/sul-dlss/SearchWorks/pull/4310 with more cleanup of roles.

Remove courses role; use db role for updating course data and pruning guest user data

---

app/views/catalog/index.rss.builder

Update index.rss.builder from upstream.

---

app/views/layouts/searchworks.html.erb

Disable turbo-prefetch.

---

app/controllers/articles_controller.rb
config/settings.yml
spec/controllers/articles_controller_spec.rb

PR to toggle the feature flag for the bot boxes: https://github.com/sul-dlss/shared_configs/pull/2219

Add a feature flag to enable/disable EDS searching (e.g. on bot boxes)

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

... for better tracing in the solr logs.

Pass the requesting client ip and the rails request id 

---

app/models/sfx_data.rb

Set a user-agent header for SFX requests.

---

app/controllers/articles_controller.rb
app/views/catalog/index.json.jbuilder
spec/controllers/articles_controller_spec.rb

Handle bot blocking for articles+ without creating more honeybadger alerts

---

app/views/catalog/_home_page.html.erb
app/views/catalog/mastheads/_iiif_resources.html.erb
config/settings.yml
spec/components/record/item/mods/metadata_component_spec.rb
spec/views/catalog/_show_mods.html.erb_spec.rb

Update IIIF link to https://library.stanford.edu/iiif

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

Guard against structured queries (as used by browse nearby)

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

Force boolean parsed queries to use edismax.

---

Gemfile
Gemfile.lock

Upgrade sqlite3 to 2.0

---

config/solr_configs/schema.xml
config/solr_configs/solrconfig.xml

Sync solr configurations from sul-solr

---

config/initializers/okcomputer.rb

We have this check connected to https://library-status.stanford.edu/
https://github.com/sul-dlss/library-status/blob/7c78bff4cecff2e1aafd3ae8fc628c970dbea59c/src/utils/endpointParsers.js#L38

Restore OkComputer check for oclc_citation_service

---

config/initializers/okcomputer.rb

Fixes class name in https://github.com/sul-dlss/SearchWorks/pull/4427

Fix OclcDiscoveryClient class name

---

app/controllers/catalog_controller.rb
config/initializers/blacklight_initialize.rb

Ensure blocked deep pagination options are not shown

---

Gemfile

Remove obsolete comment from Gemfile

---

.gitignore

Now there are apparently such things as `.sqlite3-shm` and `.sqlite3-wal`. God help us all

Ignore more kinds of sqlite files

---

Gemfile
Gemfile.lock

Upgrade rspec-rails to version 7

---

config/initializers/rack_attack.rb
config/settings.yml

Use rack-attack to throttle /16 and /24 ranges too.

---

Gemfile.lock

bundle --update bundler

---

app/helpers/feedback_form_helper.rb

After Rubocop autocorrect from https://github.com/sul-dlss/SearchWorks/pull/4584

Remove redundant logic in form helper

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/fonts.scss
app/assets/stylesheets/modules/online-resource-links.scss

Use Noto Serif Tibetan for Tibetan Unicode range

---

app/assets/stylesheets/searchworks-mixins.scss

Remove unused sass mixin

---

Jenkinsfile

Restore `main` branch deploy to folio preview environment

---

Jenkinsfile

Deploy `blacklight8-redux` branch to -uat.

---

app/models/folio/holding.rb
app/models/folio/location.rb

This matches what we do in the indexer. https://github.com/sul-dlss/searchworks_traject_indexer/commit/95434a1faaee433a2d9b24d2c2d79bfa07ee4071

Expand search for bound-with to look at the effectiveLocation.details

---

app/services/folio/courses.rb

Include the whole termObject in course debug data

---

spec/components/access_panels/course_reserves_component_spec.rb

create test for course_reserves_list_component link_to_course_reserve_course in course_reserves_component_spec

---

app/services/folio/courses.rb

See #4631
Sometimes the API doesn't give us a term and we do not yet know why.

Skip updating Folio courses that have no term

---

app/services/folio_client.rb
config/settings.yml

Log FOLIO API calls.

---

.rubocop.yml
app/components/location_request_link_component.rb
app/models/concerns/marc_metadata.rb
app/models/nearby_on_shelf.rb
app/services/folio_client.rb

Update rubocop language spec to 3.3 and autocorrect

---

app/components/request_links/hoover_request_link_component.rb
spec/components/request_links/hoover_request_link_component_spec.rb

Use In_process_non_requestable status instead of In_process for non-requestable Hoover items

---

app/models/concerns/schema_dot_org.rb

Add documentation about Schema.org

---

spec/features/top_nav_spec.rb

Use specific capybara methods for links

---

Gemfile
Gemfile.lock

Unpin solr_wrapper.

---

app/components/record/item/marc/metadata_component.html.erb
app/models/concerns/druid.rb
app/models/solr_document.rb
app/views/catalog/_index_online_section.html.erb
app/views/catalog/_managed_purl_embed.html.erb

Sometimes we use index_links and sometimes we use marc_links, so pick one way for consistency

Always use marc_links for managed purls

---

config/settings.yml

add aged to lost to recallable statuses

---

app/components/access_panels/collection_component.html.erb
app/components/access_panels/library_component.html.erb
app/components/access_panels/online_component.rb
app/components/request_links/hoover_request_link_component.rb
app/models/concerns/access_panel_links.rb
app/models/concerns/document_links.rb
app/models/concerns/marc_links.rb
app/models/solr_document.rb
app/views/catalog/mastheads/_collection.html.erb
spec/components/access_panels/at_the_library_component_spec.rb
spec/components/location_request_link_component_spec.rb
spec/components/request_links/hoover_request_link_component_spec.rb
spec/components/search_result/item/marc/metadata_component_spec.rb
spec/fixtures/solr_documents/29.yml
spec/fixtures/solr_documents/4085072.yml
spec/models/concerns/access_panel_links_spec.rb
spec/models/concerns/marc_links_spec.rb
spec/views/catalog/record/_marc_contents_summary.html.erb_spec.rb
spec/views/catalog/record/_marc_metadata_sections.html.erb_spec.rb

Merge various marc links refactoring work

---

.rubocop.yml

Set target ruby version to 3.4

---

app/views/shared/_su_footer.html.erb

Add top margin on the footer, per new designs

---

app/views/shared/_su_footer.html.erb

Footer should not have a contentinfo role

---

config/ezproxy/sul_proxy_file.txt

Remove domain from sul_proxy_file

---

Jenkinsfile

Deploy `main` to -uat again

---

app/assets/stylesheets/modules/item-preview.scss

Drop obsolete rules for IE

---

app/assets/stylesheets/modules/results-documents.scss

Dividing in Sass is deprecated

---

package.json

Configure sass not to emit warnings about bootstrap internals

---

spec/fixtures/solr_documents/13553090.yml

Refresh fixture data

---

app/assets/stylesheets/modules/feedback-form.scss

Remove unused style

---

app/views/shared/feedback_forms/_quick_report.html.erb

Remove unused template

---

app/assets/stylesheets/modules/results-documents.scss
app/assets/stylesheets/variables.css
app/views/layouts/searchworks.html.erb

Use the palette from the component library

---

app/views/catalog/_constraints.html.erb

This is identical to the upstream template:
https://github.com/projectblacklight/blacklight/blob/v8.9.0/app/views/catalog/_constraints.html.erb

Remove unnecessary override

---

app/components/access_panels/location_item_component.html.erb
lib/holdings/item.rb
spec/lib/holdings/item_spec.rb

closes #4726 
See https://github.com/sul-dlss/SearchWorks/issues/4726#issuecomment-2810658047 for details on this PR

fix live lookup for bound-withs

---

app/models/concerns/solr_holdings.rb
spec/models/concerns/solr_holdings_spec.rb

initialize bound-withs items to include holdings data

---

app/assets/stylesheets/modules/recaptcha.css

@dbranchini requested an update to these styles in Slack for #3868

Update recaptcha login link style

---

Jenkinsfile

Deploy citeproc experiment to UAT

---

Jenkinsfile
Jenkinsfile-Lane-Update

Use Ruby 3.4.1 for jenkins

---

app/assets/stylesheets/modules/availability.scss
app/assets/stylesheets/modules/location-table.css
app/assets/stylesheets/searchworks.scss
app/components/search_result/location_component.html.erb
app/components/search_result/location_component.rb
lib/holdings/item.rb
spec/components/search_result/location_component_spec.rb
spec/features/request_link_spec.rb

update bound-with-note to display for all bound-withs, style/text updates

---

config/ezproxy/sul_proxy_file.txt

Add i2.saiglobal.com to sul_proxy_file.txt

---

app/assets/stylesheets/print/styles.scss
app/views/shared/_print_header.html.erb

Remove unused template print_header

---

app/assets/stylesheets/modules/facets.scss

Porting over https://github.com/projectblacklight/blacklight/pull/3553/files#diff-da66ed03019fafc11578dd848b4320bf9283d952f1554a0a431845e0fcfe4c32.

Add upstream css to hide an empty div.

---

Jenkinsfile-Folio-Update

Sync configs from folio-test

---

config/settings.yml

Update RILM database link

---

app/views/shared/record/_record_toolbar_tools_subset.html.erb

fix progress bar after click

---

.rubocop_todo.yml
spec/features/blacklight_customizations/emailing_records_spec.rb

Use capybara specific actions for the email spec

---

app/assets/stylesheets/modules/sul-icons.scss
app/components/icons/loose_leaf_component.rb
app/helpers/facets_helper.rb
lib/constants.rb

add loose-leaf icon

---

app/components/access_panels/library_location_component.html.erb
app/components/access_panels/library_location_component.rb
app/components/access_panels/location_item_component.html.erb
app/components/access_panels/location_item_component.rb
app/services/fixture_harvester.rb
spec/features/access_panels/library_location_spec.rb
spec/features/alternate_catalog_spec.rb
spec/features/blacklight_customizations/results_document_spec.rb
spec/features/blacklight_customizations/results_toolbar_spec.rb
spec/fixtures/solr_documents/4085177.yml
spec/fixtures/solr_documents/6631609.yml

Consolidate finding aid call numbers in access panel

---

app/views/catalog/_document_brief.html.erb

Also use the article component for bookmarks.

---

app/assets/stylesheets/modules/sul-icons.scss

Remove unused icon styles

---

app/components/search_result/document_gallery_component.html.erb
app/components/search_result/document_gallery_component.rb
app/helpers/preview_helper.rb

Build the gallery document container directly.

---

app/helpers/collection_helper.rb
spec/helpers/collection_helper_spec.rb

Remove unused method: collection_members_enumeration

---

app/helpers/results_document_helper.rb
spec/features/blacklight_customizations/results_document_spec.rb
spec/features/merged_image_spec.rb
spec/fixtures/solr_documents/37.yml
spec/helpers/results_document_helper_spec.rb

Marc records have pub_year_ss indexed now. See https://github.com/sul-dlss/searchworks_traject_indexer/blob/9f1e6f5f5c199629a1a3cc53279134f846b43e6f/lib/traject/config/folio_config.rb#L734-L755

Remove unnecessary code

---

app/assets/stylesheets/bootstrap-addons.scss
app/assets/stylesheets/searchworks.scss
app/components/articles/index_brief_component.html.erb
app/components/search_result/index_brief_component.html.erb

.row already give display: flex

Remove unnecessary css class

---

app/assets/stylesheets/modules/brief-view.scss

This reverts commit fd848f0b8f10afa9f6172a79bcbdba02ff98bd91.

Revert "Fix row margins for brief view."

---

app/assets/stylesheets/blacklight.scss

Fix facet value padding.

---

app/components/search_result/location_component.html.erb
app/views/catalog/stackmap.html.erb

Replace col-xs-* (dropped in Bootstrap 4)

---

Jenkinsfile

Deploy the bootstrap-5 branch to sw-webapp-sandbox-c/gryphon-search.

---

spec/models/marc_fields/linked_serials_spec.rb

Remove unnecessary puts

---

app/assets/stylesheets/modules/side-nav-minimap.scss

box-shadow is widely supported

Remove obsolete browser prefixes

---

app/models/concerns/marc_links.rb
spec/models/concerns/marc_links_spec.rb

Preserve managed purl explicit sort order.

---

app/views/layouts/searchworks.html.erb

we should have test be as close as possible to prod

Stop disabling animations in test

---

app/assets/stylesheets/blacklight.scss

Remove unnecessary css

---

app/javascript/alternate_catalog.js

Convert alternate_catalog to use fetch

---

config/settings.yml

SAL will never have hours again.

---

app/components/stanford_only_span_component.rb
app/views/shared/_search_navbar_services_menu.html.erb

Update the help menu links

---

app/assets/stylesheets/searchworks-mixins.scss

border-bottom is included in border, which is defined just above this removed line

Remove duplicate rule

---

app/assets/stylesheets/modules/alternate-catalog.scss
app/views/articles/_alternate_catalog.html.erb
app/views/catalog/_alternate_catalog.html.erb

fix mini bento double close icon and icon alignment

---

app/helpers/access_panel_helper.rb

Remove empty helper module

---

app/assets/stylesheets/modules/article.scss
app/views/articles/_search_results.html.erb
config/locales/searchworks.en.yml

Add duplicates removed text in articles search results header

---

app/controllers/browse_controller.rb
spec/features/callnumber_browse_spec.rb

Configure search_state_fields for browse nearby.

---

app/assets/stylesheets/modules/course_reserve_browse.scss
app/javascript/course_reserves.js
app/views/layouts/searchworks.html.erb
spec/features/course_reserves_browse_spec.rb

Upgrade DataTables to 2.3.0

---

app/assets/stylesheets/modules/course_reserve_browse.scss

Update dataTables style

---

app/helpers/catalog_helper.rb
spec/helpers/catalog_helper_spec.rb

Remove unnecessary helper method

---

app/assets/stylesheets/modules/file-list-table.scss
app/assets/stylesheets/searchworks.scss

Remove unused css rule

---

app/assets/stylesheets/modules/advanced-search.scss

Cleanup of unused advanced search styles

---

spec/fixtures/solr_documents/13553090.yml
spec/fixtures/solr_documents/14136548.yml
spec/fixtures/solr_documents/2279186.yml
spec/fixtures/solr_documents/2285756.yml
spec/fixtures/solr_documents/2285763.yml
spec/fixtures/solr_documents/2300812.yml
spec/fixtures/solr_documents/2308798.yml
spec/fixtures/solr_documents/2312336.yml
spec/fixtures/solr_documents/2472159.yml
spec/fixtures/solr_documents/4085072.yml
spec/fixtures/solr_documents/4085177.yml
spec/fixtures/solr_documents/5488000.yml
spec/fixtures/solr_documents/6631609.yml
spec/fixtures/solr_documents/L210044.yml
spec/fixtures/solr_documents/in00000053236.yml

Update fixture objects

---

.rubocop_todo.yml
app/controllers/catalog_controller.rb
app/helpers/record_helper.rb
app/models/concerns/cjk_query.rb
app/models/concerns/searchworks/document/sms.rb
app/models/eds_document.rb
app/models/solr_document.rb
spec/controllers/concerns/replace_special_quotes_spec.rb
spec/features/blacklight_customizations/results_toolbar_spec.rb
spec/features/home_page_spec.rb
spec/features/special_quotes_spec.rb
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/fixtures/mods_records/mods_fixtures.rb
spec/models/concerns/cjk_query_spec.rb
spec/views/catalog/record/_mods_abstract_contents.html.erb_spec.rb
spec/views/catalog/record/_mods_access.html.erb_spec.rb
spec/views/catalog/record/_mods_subjects.html.erb_spec.rb

Remove unnecessary encoding pragmas

---

app/helpers/marc_helper.rb
app/models/solr_document.rb
app/views/catalog/_marc_search_results_document_fields.html.erb
spec/helpers/marc_helper_spec.rb
spec/models/solr_document_spec.rb

Move imprint from a helper to a model attribute

---

app/services/folio_client.rb
config/settings.yml

add timeout to folio client requests

---

app/components/access_panels/library_location_component.html.erb
app/components/access_panels/online_link_list_component.html.erb
app/components/search_result/location_component.html.erb

Correctly pass data-long-table-button-context-value attribute

---

app/models/marc_fields/linked_serials.rb
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/models/marc_fields/linked_serials_spec.rb

closes #4936 
[a10101712](https://searchworks.stanford.edu/view/10101712)
in00000192493 before
After
[2413697](https://searchworks.stanford.edu/view/2413697)
[a4778333](https://searchworks.stanford.edu/view/a4778333)
[a10268084](https://searchworks.stanford.edu/view/10268084)

ignore control 7 subfield

---

spec/features/skip_to_nav_spec.rb

Fix flaky test by ensuring bookmark is saved before navigating away

---

app/assets/stylesheets/modules/access-panel-online.scss
app/assets/stylesheets/modules/access-panel-related.scss
app/assets/stylesheets/modules/access-panel.scss
app/assets/stylesheets/searchworks-mixins.scss
app/components/access_panels/google_books_preview_component.html.erb
app/components/access_panels/google_books_preview_component.rb
app/components/access_panels/online_link_list_component.html.erb
app/javascript/controllers/long_table_controller.js
app/javascript/jquery.plug-google-content.js

Don't count hidden children in the long table controller

---

app/javascript/jquery.plug-google-content.js

fix longTable is null error

---

.rubocop_todo.yml
app/controllers/catalog_controller.rb
app/helpers/feedback_form_helper.rb
spec/models/eds/repository_spec.rb

Autocorrect argument alignment

---

app/models/citation.rb
config/locales/searchworks.en.yml
config/settings.yml
config/settings/test.yml

With e.g. https://github.com/sul-dlss/shared_configs/pull/2342

Put Citeproc citations behind a feature flag

---

app/models/citation.rb
app/services/citeproc/issued.rb
app/services/citeproc_item_service.rb

Guard against missing 008 or 245 fields.

---

spec/requests/bound_with_children_spec.rb

Remove empty spec

---

spec/fixtures/solr_documents/13553090.yml
spec/fixtures/solr_documents/14136548.yml
spec/fixtures/solr_documents/2279186.yml
spec/fixtures/solr_documents/2285756.yml
spec/fixtures/solr_documents/2285763.yml
spec/fixtures/solr_documents/2300812.yml
spec/fixtures/solr_documents/2308798.yml
spec/fixtures/solr_documents/2312336.yml
spec/fixtures/solr_documents/2472159.yml
spec/fixtures/solr_documents/4085072.yml
spec/fixtures/solr_documents/4085177.yml
spec/fixtures/solr_documents/5488000.yml
spec/fixtures/solr_documents/6631609.yml
spec/fixtures/solr_documents/L210044.yml
spec/fixtures/solr_documents/in00000053236.yml

Update solr fixtures

---

app/views/layouts/searchworks.html.erb
spec/features/blacklight_customizations/accessibility_spec.rb

Use main element rather than section + role

---

app/javascript/vendor/responsiveTruncator.js

Remove unused variable

---

app/views/layouts/searchworks.html.erb

Remove unnecessary div

---

app/javascript/location-hours.js

Rewrite location-hours.js without jquery dependency

---

app/javascript/popover.js

See https://getbootstrap.com/docs/5.3/components/popovers/#enable-popovers

Enable popovers using the Bootstrap 5 way (without jquery)

---

app/javascript/jquery.stackmap.js

All of our other jsonp using scripts use this library

Convert jquery.stackmap.js to use fetchJsonp

---

app/assets/stylesheets/modules/sul-icons.scss
app/views/shared/_side_nav_minimap.html.erb

fix missing icon in sidebar

---

app/javascript/controllers/preview_filmstrip_controller.js

Add code comment to preview_filmstrip_controller.js

---

app/services/citeproc_item_service.rb
spec/services/citeproc_item_service_spec.rb

Quote thesis titles

---

app/components/search_result/document_gallery_component.html.erb

Remove unused data property

---

app/components/search_result/document_brief_component.html.erb
app/javascript/controllers/preview_brief_controller.js
app/views/preview/show.html.erb
spec/features/brief_view_spec.rb

Load brief preview with turbo-frame

---

app/assets/stylesheets/modules/browse-toolbar.scss
app/components/record/item/marc/callnumber_browse_component.html.erb
app/components/record/item/marc/callnumber_browse_component.rb
app/javascript/embedded-call-number-browse.js
spec/components/record/item/marc/callnumber_browse_component_spec.rb

Switch to using bootstrap for controling browse nearby visibility

---

app/javascript/controllers/articles_facet_more_controller.js
app/javascript/controllers/preview_filmstrip_controller.js
app/javascript/feedback_form.js
app/javascript/jquery.preview-embed-browse.js
app/javascript/jquery.preview-gallery.js
app/views/_flash_msg.html.erb
spec/components/search_result/mini_bento/article_component_spec.rb
spec/components/search_result/mini_bento/catalog_component_spec.rb
spec/components/search_result/mini_bento/layout_component_spec.rb

Remove Bootstrap 4 close class

---

config/solr_configs/schema.xml
config/solr_configs/solrconfig.xml

Sync the solrconfig from production.

---

app/javascript/jquery.preview-gallery.js

Simplify previewOpen method

---

config/ezproxy/law_proxy_file.txt

Add discover.llmc.com to law proxy

---

config/initializers/okcomputer.rb
spec/models/performance_alerts_spec.rb
spec/rails_helper.rb

Don't connect to the newrelic API while testing

---

app/components/articles/login_banner_component.html.erb
app/components/search_result/mini_bento/layout_component.html.erb

Remove obsolete bootstrap 3 close class

---

app/javascript/feedback_form.js
app/views/_flash_msg.html.erb

convert alert html to component library

---

config/solr_configs/solrconfig.xml
spec/features/callnum_search_spec.rb

Add callnum_search to all fields search

---

spec/controllers/sfx_data_controller_spec.rb
spec/rails_helper.rb

Remove unnecessary webmock allow hosts

---

spec/system/article_eds_facets_spec.rb

Fix flaky test

---

app/components/access_panels/exhibit_component.rb
config/settings.yml
config/settings/test.yml

It's been in prod for over 5 years

Remove feature flag for exhibits access panel

---

app/assets/stylesheets/modules/access-panel-exhibit.scss
app/javascript/exhibitPanel.js
spec/features/access_panels/exhibit_spec.rb

Fix layout for exhibit panels

---

app/views/articles/_search_header.html.erb
app/views/articles/_search_results.html.erb
app/views/catalog/_search_header.html.erb
app/views/catalog/_search_results.html.erb

Remove unnecessary partials

---

app/javascript/controllers/preview_filmstrip_controller.js
app/views/collection_members/_image_collection_filmstrip.html.erb

Prefer static classes to dynamically added ones

---

app/javascript/article.js

Remove jquery from articles plugin

---

app/components/search_result/document_gallery_component.html.erb
app/components/search_result/document_gallery_component.rb
app/javascript/controllers/gallery_preview_controller.js
app/javascript/controllers/preview_embed_browse_controller.js
app/javascript/controllers/preview_filmstrip_controller.js
app/javascript/embedded-call-number-browse.js
app/views/collection_members/_image_collection_filmstrip.html.erb

Use turbo frame for preview content

---

Jenkinsfile

Deploy the main branch to stage

---

app/assets/stylesheets/searchworks4.scss

Use a 1500px max container size

---

app/assets/stylesheets/searchworks4/homepage.css
app/assets/stylesheets/searchworks4/variables.css
app/views/catalog/_home_page.html.erb

Refine home page search box

---

app/views/shared/searchworks4/_top_navbar.html.erb

The "Catalog" part of the header is meant to be semibold

---

app/javascript/controllers/embed_browse_controller.js

Remove jquery dependency from embed browse javascript controller

---

app/assets/stylesheets/modules/sort-and-per-page-toolbar.scss

Backports #5069 to the `release` branch

Restore button hover color for sul-toolbar

---

app/assets/stylesheets/searchworks4/homepage.css
app/views/catalog/_home_page.html.erb

Responsive layout for homepage

---

app/controllers/recent_selections_controller.rb
app/javascript/recent-selections.js

Remove jquery dependency from recent-selections

---

config/ezproxy/sul_proxy_file.txt

Add domains to sul_proxy file

---

app/assets/stylesheets/searchworks4/homepage.css
app/views/catalog/_home_page.html.erb

Large (unchanged):
Medium (after):

Use flexbox instead of bootstrap columns to implement the responsive design.

---

app/views/catalog/_home_page.html.erb

Add missing h2 header on homepage

---

app/javascript/analytics.js

Part of #5085.
Tracks internal link clicks using the same metrics and dimensions that GA4 uses to track outgoing links. The event is now "click" and there are a common set of [link dimensions](https://support.google.com/analytics/table/13594742#query=link).
I'm proposing using the `outbound` link dimension to carry type information. It is a text field. GA4 sets it to the string "true" for the default outbound link tracking and that is the only way GA4 uses it by default. It is a string so the end user can customize its behavior.
By placing type information in this field for internal links we are able to flag internal link clicks that have no other useful distinguishing characteristics (e.g., `browse-nearby`). It is an unfortunate field name (with inconsistent/incorrect documentation) that …

Use GA4 style internal link click tracking

---

.rubocop.yml
app/helpers/catalog_helper.rb

Add new rubocops and correct squawks

---

app/views/shared/searchworks4/_top_navbar.html.erb

Remove extra bracket

---

app/assets/stylesheets/searchworks4/blacklight.css

Copy css from blacklight to support the show/hide facets button

---

app/components/search_result/mini_bento/layout_component.html.erb

This change needs to be backported to the release branch 😬

Enable archives in the mini-bento

---

.github/workflows/ruby.yml

Run CI on release branch

---

Jenkinsfile-Folio-Update

Switch to release branch before running FOLIO updates

---

Gemfile
Gemfile.lock

This is already done on the main branch, but it needed a backport to release.
Ref #5183

[release branch] Update csl-styles to 2.0

---

Gemfile.lock

Update to latest citeproc-ruby

---

Gemfile.lock

[backport] Upgrade citeproc-ruby

---

Gemfile
Gemfile.lock
app/components/articles/document_list_component.html.erb
app/components/articles/response/facet_item_component.rb
app/components/articles/response/limited_facet_field_list_component.rb
app/components/articles/response/more_facets_list_component.rb
app/components/record/document_title_component.html.erb
app/components/search_result/document_gallery_component.html.erb
app/components/searchworks4/document_component.html.erb
app/controllers/catalog_controller.rb
app/models/collection_filter_query.rb
app/models/solr_document.rb
app/presenters/show_document_presenter.rb
app/views/catalog/_marc_search_results_document_fields.html.erb
app/views/catalog/_mods_search_results_document_fields.html.erb
app/views/catalog/_show_header_default.html.erb
package.json
spec/models/collection_filter_query_spec.rb
spec/models/nearby_on_shelf_spec.rb
yarn.lock

Upgrade to Blacklight 9.0.0 beta2

---

app/assets/stylesheets/searchworks4/blacklight.css
app/views/catalog/_search_results.html.erb

Restore modals

---

app/javascript/responsive-aside.js
app/javascript/searchworks4.js
app/views/catalog/_search_results.html.erb

Implement responsive designs for the minibento for xxl screens

---

app/assets/stylesheets/searchworks4/blacklight.css

make search bar smaller on larger screens

---

app/javascript/responsive-aside.js

Fix null checks in responsive aside

---

app/views/catalog/_search_results.html.erb
app/views/databases/_search_results.html.erb
spec/features/accessibility_spec.rb

Provide a visually-hidden h1 header for the search results

---

app/assets/stylesheets/searchworks4/search-results.css
app/components/document/tracking_bookmark_component.html.erb

Before:
https://github.com/user-attachments/assets/755e3557-12f9-4f32-a283-6fb4cc70a51c
After:
https://github.com/user-attachments/assets/21f28ffe-2d01-48fb-b874-f0dd80b85e1e

fix flashing button bug

---

app/javascript/responsive-aside.js

Avoid iterating over a scalar value

---

app/views/_flash_msg.html.erb
app/views/articles/_home_page.html.erb
app/views/catalog/_home_page.html.erb
app/views/databases/_header.html.erb
app/views/databases/_home_page.html.erb

Flash messages need a margin

---

app/components/main_container_component.html.erb

Enable google cover image lookup for searchworks4

---

app/assets/stylesheets/searchworks4/search-results.css
config/locales/blacklight.en.yml

fix spacing on selected sort-per-page dropdowns

---

Gemfile
Gemfile.lock
package.json
yarn.lock

update to blacklight 9.0.0-beta3

---

app/models/eds/session.rb

Don't memoize the EDS Faraday connection

---

app/assets/stylesheets/component-library-overrides.css
app/assets/stylesheets/searchworks4.scss
app/assets/stylesheets/searchworks4/search-results.css
app/components/facets/group_component.rb
app/components/main_container_component.html.erb
app/components/searchworks4/document_component.html.erb
app/components/searchworks4/item_status_component.html.erb
app/components/searchworks4/physical_availability_component.html.erb
app/components/searchworks4/physical_availability_component.rb
app/components/searchworks4/search_result/item_menu_component.html.erb
app/views/catalog/_search_results.html.erb
app/views/shared/searchworks4/_search_navbar.html.erb
app/views/shared/searchworks4/_su_footer.html.erb
app/views/shared/searchworks4/_top_navbar.html.erb

Steve, Darcy, and I reviewed the search results page and tweaked some of the alignment and responsive elements to better match the designs.

Style fixes

---

Jenkinsfile-Folio-Update
Jenkinsfile-Lane-Update

Pull latest commits on release branch when running scripts

---

app/views/articles/_search_results.html.erb
app/views/catalog/_search_results.html.erb
config/locales/searchworks.en.yml
spec/features/article_searching_spec.rb
spec/features/results_page_spec.rb

Set the page title for search results

---

app/components/masthead/layout_component.html.erb
app/views/databases/_home_page.html.erb
app/views/databases/_search_results.html.erb

Pull 'back to catalog search' up to the layout component.

---

app/views/shared/_zero_results.html.erb

Use inline link style on the no results page

---

app/assets/stylesheets/searchworks4/typography.css

Fix CSS syntax error.

---

app/views/catalog/_search_results.html.erb

Add, but grey-out, the previous link if we're on the first page

---

app/assets/stylesheets/searchworks4/blacklight.css

update modal backdrop color

---

app/assets/stylesheets/searchworks4/search-results.css
config/locales/blacklight.en.yml
spec/components/articles/response/limited_facet_field_list_component_spec.rb
spec/components/articles/response/more_facets_list_component_spec.rb
spec/system/article_eds_facets_spec.rb

update more to browse all

---

app/controllers/errors_controller.rb

Use searchworks4 layout for errors. 

---

lib/holdings/location.rb
spec/lib/holdings/location_spec.rb

Guard against bad stackmaps urls; fixes #5369

---

app/components/record/marc_document_component.html.erb
app/components/record/mods_document_component.html.erb

Fix single item viewer

---

app/assets/stylesheets/searchworks4.scss
app/views/catalog/opensearch.xml.builder
app/views/layouts/searchworks4.html.erb
app/views/shared/searchworks4/_user_util_links.html.erb

Update to latest component library

---

app/components/access_panels/library_component.html.erb

Fix up library sidebar styling

---

app/assets/stylesheets/searchworks4/record.css

Provides styles for exhibit access panel

---

app/components/record_toolbar_component.html.erb
spec/features/blacklight_customizations/record_toolbar_spec.rb
spec/features/responsive/record_toolbar_responsive_spec.rb

Add an aria-label to navigation element

---

config/locales/blacklight.en.yml

Bold the page entry info numbers

---

spec/features/accessibility_spec.rb

Run accessibility test on record view

---

app/assets/stylesheets/searchworks4/links.css
app/assets/stylesheets/searchworks4/typography.css
app/components/access_panels/at_the_library_component.html.erb
app/components/access_panels/availability_component.html.erb
app/components/access_panels/availability_component.rb
app/components/access_panels/layout_component.html.erb
app/components/access_panels/layout_component.rb
app/components/access_panels/library_component.html.erb
app/components/access_panels/library_component.rb
app/components/access_panels/library_location_component.html.erb
app/components/access_panels/online_component.html.erb
app/components/access_panels/online_component.rb
app/views/catalog/record/_metadata_panels.html.erb
spec/components/access_panels/at_the_library_component_spec.rb

Get record availability header styling closer to the designs 

---

app/components/page_links_component.html.erb
app/components/page_links_component.rb
app/views/catalog/_search_results.html.erb

This will be used on other pages such as the bookmarks

Extract PageLinksComponent

---

app/components/access_panels/library_component.html.erb
app/components/access_panels/library_component.rb
spec/features/access_panels/library_location_spec.rb

Only show the arrow icon if we've made a link.

---

app/assets/stylesheets/searchworks4/record.css
app/javascript/controllers/preview_filmstrip_controller.js
app/views/collection_members/_image_collection_filmstrip.html.erb

update filmstrip view for searchworks4

---

spec/features/emailing_records_spec.rb

Reenable skipped test post redesign

---

app/views/shared/searchworks4/_user_util_links.html.erb

Remove search history from header

---

app/assets/stylesheets/searchworks4/facets.css
app/components/facets/group_component.html.erb
app/components/facets/group_component.rb
app/components/search_result/mini_bento/layout_component.html.erb
app/controllers/catalog_controller.rb
app/javascript/controllers/facet_list_controller.js
app/views/catalog/_search_results.html.erb
spec/features/access_points/dissertation_theses_spec.rb
spec/features/blacklight_customizations/facets_spec.rb
spec/features/facets_spec.rb

Fixes #5319 
https://github.com/user-attachments/assets/c57ce655-e049-4374-8877-2d7f9771a1c9

Implement top filters offscreen using css classes

---

app/views/catalog/mastheads/_digital_collections.html.erb
app/views/catalog/mastheads/_government_documents.html.erb

Decrease the subheader size on mastheads to match designs

---

app/assets/stylesheets/searchworks4/search-results.css

fix browse all link hover color

---

app/javascript/controllers/facet_list_controller.js
spec/features/blacklight_customizations/facets_spec.rb

Don't hide/show facets if the user has picked a facet from that category already

---

app/models/eds/session.rb

Fix the error handling data type of citations and exports.

---

app/assets/stylesheets/searchworks4/record.css
app/helpers/facets_helper.rb
app/views/collection_members/_file_collection_members.html.erb
spec/views/collection_members/_file_collection_members.html.erb_spec.rb

restyle digital collections without images

---

app/views/collection_members/_file_collection_members.html.erb
spec/features/merged_file_collection_spec.rb

Collection figma has been updated to 
Before:
After:

move all collection link, increase results to 5

---

app/controllers/article_selections_controller.rb
app/models/eds/repository.rb
app/models/eds/session.rb
spec/models/eds/repository_spec.rb

Use the artificially constructed response object instead of a single document's response

---

app/views/articles/_email_form.html.erb
app/views/catalog/_email_form.html.erb
app/views/catalog/email.html.erb
app/views/shared/_email_form.html.erb
spec/features/emailing_records_spec.rb

Add email modal for multiple documents

---

Jenkinsfile

Deploy uat-release to the uat environment

---

app/assets/stylesheets/searchworks4.scss
app/assets/stylesheets/searchworks4/facets.css
app/assets/stylesheets/searchworks4/masthead.css
app/assets/stylesheets/searchworks4/search-results.css
app/components/access_panels/library_location_component.html.erb
app/components/searchworks4/constraint_layout_component.rb
app/components/searchworks4/constraints_component.rb
app/components/searchworks4/document_component.html.erb
app/components/searchworks4/physical_availability_component.rb
app/components/searchworks4/search_result/item_menu_component.html.erb
app/controllers/catalog_controller.rb
app/views/catalog/_search_results.html.erb
spec/components/searchworks4/constraint_layout_component_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/features/blacklight_customizations/facets_spec.rb
spec/features/date_range_spec.rb

Style tweaks from pairing with Darcy

---

spec/features/accessibility_spec.rb

Enable a11y checks on articles+

---

app/components/access_panels/library_component.html.erb
app/components/access_panels/library_location_component.html.erb

Availability sidebar tweaks

---

app/components/record/marc_content_advice_component.rb
app/services/fixture_harvester.rb
spec/component_previews/record/marc_content_advice_component_preview.rb
spec/features/alternate_catalog_spec.rb
spec/features/blacklight_customizations/facets_spec.rb
spec/fixtures/solr_documents/14289604.yml

Restore content advice styling.

---

app/components/masthead/layout_component.html.erb
app/components/masthead/layout_component.rb
app/views/catalog/index.html.erb
app/views/catalog/mastheads/_course_reserve.html.erb
spec/features/access_points/course_reserve_spec.rb
spec/fixtures/solr_documents/2.yml

Added course reserves result page

---

app/javascript/alternate_catalog.js

Stop injecting minibento into search results for articles+.

---

app/components/record/marc_document_component.html.erb
app/components/record/mods_document_component.html.erb

Add a margin between the title + vernacular title.

---

app/assets/stylesheets/searchworks4/modal.css

Position the feedback modal using viewport-relative coordinates.

---

app/assets/stylesheets/searchworks4/course-reserves.css
app/javascript/controllers/course_reserves_controller.js

fix course table stripes after search

---

app/views/catalog/_home_page.html.erb

Update home page copy

---

app/views/layouts/searchworks4.html.erb

Remove datatables

---

app/assets/stylesheets/searchworks4/links.css
app/assets/stylesheets/searchworks4/modal.css
app/assets/stylesheets/searchworks4/stackmap.css
app/controllers/catalog_controller.rb
app/javascript/controllers/stackmap_controller.js
app/views/catalog/_email_form.html.erb
app/views/catalog/stackmap.html.erb
spec/views/catalog/stackmap.html.erb_spec.rb

Ref #5422
This also fixes an issue where callnumber was missing.

Update style for stackmap modal

---

app/views/catalog/show.html.erb

Move tech details back to the right side of the screen

---

app/components/searchworks4/item_status_component.rb
spec/components/searchworks4/item_status_component_spec.rb

Add loan period for reserves

---

spec/system/article_eds_facets_spec.rb

Skip the flappy EDS spec on CI

---

app/components/searchworks4/item_status_component.html.erb

Put a little space before the due date.

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

Remove unused helpers

---

app/assets/stylesheets/searchworks4/record.css

Add some padding between metadata labels.

---

app/assets/stylesheets/searchworks4/record.css
app/components/record/document_layout_component.html.erb

Make some space between the document title + thumbnail.

---

app/views/articles/_home_page.html.erb

Update articles home page text

---

app/views/shared/searchworks4/_search_navbar.html.erb

check radio for articles+ when on articles+

---

spec/routing/devise_spec.rb

Move routing spec to the correct directory

---

app/helpers/masthead_helper.rb
app/views/catalog/mastheads/_digital_collections.html.erb
app/views/catalog/mastheads/_sdr.html.erb

update digital collections/sdr masthead to match figma

---

app/assets/stylesheets/searchworks4/browse-nearby.css
app/assets/stylesheets/searchworks4/record.css
app/assets/stylesheets/searchworks4/search-results.css
app/components/masthead/layout_component.html.erb
app/components/record/item/marc/callnumber_browse_component.html.erb
app/components/record/marc_contents_summary_component.html.erb
app/components/record/marc_document_component.html.erb
app/components/record/mods_document_component.html.erb
app/components/searchworks4/digital_collections_facet_header_component.html.erb
app/components/searchworks4/document_component.html.erb
app/components/searchworks4/online_availability_component.html.erb
app/services/live_lookup/folio.rb
app/views/catalog/mastheads/_course_reserve.html.erb
app/views/catalog/mastheads/_digital_collections.html.erb
app/views/catalog/mastheads/_government_documents.html.erb
app/views/catalog/mastheads/_sdr.html.erb
app/views/collection_members/_file_collection_members.html.erb
app/views/collection_members/_image_collection_filmstrip.html.erb
app/views/course_reserves/_header.html.erb
app/views/databases/_header.html.erb
spec/services/live_lookup/folio_spec.rb

Style tweaks

---

app/models/links/link.rb

Remove unused method

---

app/helpers/application_helper.rb
app/views/catalog/_search_bar_advanced_widget.html.erb
spec/helpers/application_helper_spec.rb

Remove unused search_bar_advanced_widget

---

app/services/eds/search_service.rb
spec/support/stub_article_service.rb

Fix Eds::SearchService#fetch_one regression.

---

app/components/record/marc_document_component.html.erb
app/components/searchworks4/document_component.html.erb

Guard against missing data.

---

app/assets/stylesheets/searchworks4/links.css
app/views/articles/_facet_header.html.erb

Style articles+ facet options

---

app/views/layouts/lookbook.html.erb
app/views/layouts/searchworks4.html.erb

... and I can't see any reason to prefer separate bootstrap + popper dependencies vs the bootstrap bundle? 🤷‍♂️

Update javascript dependencies

---

Gemfile.lock
yarn.lock

Upgrade to Blacklight 9.0.0.beta5

---

app/controllers/availability_controller.rb
app/services/folio_client.rb
app/views/availability/show.html.erb
spec/controllers/availability_controller_spec.rb
spec/requests/availability_spec.rb

Error handling for availability lookup

---

app/components/record/mods_bibliographic_component.html.erb
app/components/record/mods_document_component.html.erb

Update MODS field rendering.

---

app/components/searchworks4/item_status_component.rb

Add item status for long missing

---

app/components/access_panels/grouped_library_component.html.erb

Make the off-campus header match the other libraries

---

app/components/searchworks4/item_status_component.html.erb

Remove padding from item-level request links to match location-level

---

app/views/articles/_home_page.html.erb

This came in either as a bad merge or rebase from #5585 🤷

Remove duplicate login banner.

---

app/components/search_result/mini_bento/article_component.rb
spec/components/search_result/mini_bento/article_component_spec.rb
spec/components/search_result/mini_bento/catalog_component_spec.rb
spec/components/search_result/mini_bento/layout_component_spec.rb

@cbeer I think this reflects the changes from your current PR. Do with this what you will 😄

Update test for the new mini bento component

---

app/components/page_links_component.html.erb

This helps to provide consistency throughout the app

Use translations for previous/next

---

app/assets/stylesheets/searchworks4/record.css
app/components/access_panels/additional_info_component.html.erb
app/components/access_panels/additional_info_component.rb
app/components/access_panels/availability_component.html.erb
app/components/access_panels/library_component.html.erb
app/components/access_panels/library_component.rb
app/components/access_panels/library_header_component.html.erb
app/components/access_panels/library_header_component.rb
app/components/access_panels/library_location_component.html.erb
app/components/access_panels/library_location_component.rb
app/components/access_panels/library_location_popover_component.html.erb
app/components/access_panels/library_location_popover_component.rb
app/components/searchworks4/availability_accordion_component.html.erb
app/components/searchworks4/availability_accordion_component.rb
app/components/searchworks4/availability_modal_location_component.html.erb
app/components/searchworks4/availability_modal_location_component.rb
app/controllers/catalog_controller.rb
app/javascript/controllers/long_table_controller.js
app/views/catalog/availability_modal.html.erb
config/routes.rb
spec/features/access_panels/library_location_spec.rb
spec/features/mhld_spec.rb

part of #5447 
Things that I can see currently

initial creation of availability modal

---

app/assets/stylesheets/searchworks4/databases.css
app/components/databases/search_bar_component.html.erb
app/components/databases/search_bar_component.rb
app/controllers/databases_controller.rb
app/javascript/controllers/database_autocomplete_controller.js
app/javascript/controllers/index.js
app/views/databases/_header.html.erb
app/views/databases/autocomplete.html.erb
config/routes.rb

This is a spike for #5304
https://github.com/user-attachments/assets/247dfb13-8717-4916-833a-e65ecb723900

Add database-specific autocomplete behavior; 

---

app/javascript/controllers/list_toggle_controller.js
app/javascript/controllers/long_text_controller.js
app/javascript/controllers/show_more_button_controller.js

Fix show more/less behavior.

---

app/components/toolbar_search_context_info_component.html.erb
spec/features/blacklight_customizations/record_toolbar_spec.rb

Add placeholder 'previous' button to the record toolbar.

---

app/components/searchworks4/mods_authors_component.html.erb
spec/components/searchworks4/mods_authors_component_spec.rb

Remove the extra space from MODS author display

---

spec/components/citations/multiple_citations_component_spec.rb

Remove test debug code

---

app/views/catalog/_facet_header.html.erb
lib/page_location.rb

Create and use `PageLocation#dissertation_theses?`

Use existing search_state method

---

app/assets/stylesheets/searchworks4/sul-icons.css

Add documentation to css

---

app/components/articles/article_component.html.erb
app/javascript/controllers/articles_facet_more_controller.js
config/initializers/assets.rb
package.json
yarn.lock

Stop using font-awesome icons

---

app/assets/stylesheets/searchworks4/record.css
app/assets/stylesheets/searchworks4/search-results.css
app/components/document/tracking_bookmark_component.html.erb
app/components/document/tracking_bookmark_component.rb
app/components/record_toolbar_component.html.erb
app/controllers/bookmarks_controller.rb
app/views/bookmarks/destroy.turbo_stream.erb
app/views/bookmarks/update.turbo_stream.erb

Label the bookmark icon for the record view page

---

app/components/searchworks4/availability_component.rb
app/components/searchworks4/online_availability_component.html.erb
app/components/searchworks4/online_availability_component.rb
spec/components/searchworks4/availability_component_spec.rb

Add online link behavior for SDR-backed items

---

app/components/searchworks4/physical_availability_component.html.erb

Encourage flexbox to wrap after the library name

---

app/javascript/adv-search/advanced_search_controller.jsx

Guard against unknown filter fields in adv search

---

app/components/searchworks4/physical_availability_component.html.erb

Add the placeholder 'multiple locations' if we have multiple libraries

---

app/components/access_panels/library_location_component.html.erb
app/components/access_panels/library_location_popover_component.html.erb

Always wrap the summary of items below the location name

---

app/components/searchworks4/physical_availability_component.html.erb

Add "multiple locations"  label for truncated availability display

---

app/components/record/item/marc/callnumber_browse_component.rb
app/javascript/controllers/embed_browse_controller.js
spec/features/callnumber_browse_spec.rb

Scroll over and highlight current document in browse nearby

---

app/assets/stylesheets/searchworks4/record.css
app/components/citations/multiple_citations_component.html.erb
app/components/citations/multiple_citations_component.rb
app/components/searchworks4/citations/citation_component.html.erb
app/components/searchworks4/citations/citation_component.rb
app/models/citations/mods_citation.rb
app/services/fixture_harvester.rb
spec/components/citations/multiple_citations_component_spec.rb
spec/features/access_points/digital_collections_spec.rb
spec/features/alternate_catalog_spec.rb
spec/fixtures/solr_documents/nj140cs3237.yml
spec/models/citations/mods_citation_spec.rb

Add preferred & missing citation handling

---

.rubocop.yml
app/components/searchworks4/advanced_search_form_component.rb
app/controllers/catalog_controller.rb

Restore the advanced-search only search fields to adv search

---

app/views/shared/searchworks4/_catalog_featured_resources.html.erb

Alphabetize the featured resource menu

---

app/components/databases/search_bar_component.html.erb

Tweak the database placeholder.

---

app/views/databases/_header.html.erb

Fix databases subhead.

---

app/components/access_panels/library_location_component.html.erb
app/components/access_panels/library_location_component.rb

fix browse all link to include icon

---

app/components/stackmap/map_component.html.erb
app/javascript/controllers/stackmap_controller.js

Disable the reset button + zoomout buttons if the stackmap won't change

---

app/assets/stylesheets/searchworks4/record.css
app/assets/stylesheets/searchworks4/variables.css
app/components/searchworks4/availability_accordion_component.html.erb
app/components/searchworks4/availability_modal_location_component.html.erb
app/javascript/controllers/availability_search_controller.js
app/javascript/controllers/index.js
app/views/catalog/availability_modal.html.erb
spec/features/access_panels/library_location_spec.rb

Fixes #5675 
https://searchworks.stanford.edu/view/406524 is a good example to test with.
https://github.com/user-attachments/assets/865c659b-5b28-4e91-a5f7-182de656fe29
- search clear button (wait for the component library?)

Add availability search.

---

lib/constants.rb
spec/components/access_panels/at_the_library_component_spec.rb
spec/lib/holdings/library_spec.rb

remove on-site access heading.

---

app/views/shared/searchworks4/_user_util_links.html.erb

Fix save badge alignment

---

app/assets/stylesheets/searchworks4/record.css
app/components/bookmarks/toolbar_component.html.erb
app/views/bookmarks/index.html.erb

Use consistent styles on the bookmark toolbar as on the record page.

---

app/views/databases/_home_page.html.erb

Left-align databases

---

app/views/catalog/_home_page.html.erb
app/views/catalog/_new_search.html.erb
app/views/shared/searchworks4/_catalog_featured_resources.html.erb
spec/features/access_points/dissertation_theses_spec.rb
spec/features/home_page_spec.rb

Update Theses text

---

app/models/search_builder.rb

Add `f_inclusive` to our list of search params

---

spec/features/advanced_search_spec.rb

... and see if that helps with some flaky behavior.

Use a less vague selector for tests

---

app/components/masthead_search_component.rb
app/controllers/articles_controller.rb
app/controllers/catalog_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/search_navbar_controller.js
app/views/articles/_home_page.html.erb
app/views/articles/search_bar.html.erb
app/views/catalog/search_bar.html.erb
app/views/shared/searchworks4/_search_navbar.html.erb
config/routes.rb
spec/features/blacklight_customizations/masthead_search_spec.rb
spec/features/blacklight_customizations/search_types_spec.rb

The search bar should have search fields that are relevant for the mode you're in.

Get the search bar in the right state for the selected mode

---

app/views/databases/_popular_databases.html.erb

Remove Stanford-only badge from Google Scholar (because it isn't.)

---

app/components/record/mods_document_component.html.erb
app/components/record/mods_document_component.rb
app/components/searchworks4/document_section_layout.html.erb
app/components/searchworks4/metadata_field_layout_component.html.erb

Truncate some MODS data

---

app/controllers/browse_controller.rb
spec/features/callnumber_browse_spec.rb

Don't carry over browse state to a new search

---

app/components/document/tracking_bookmark_component.html.erb
app/javascript/controllers/saved_list_controller.js

Right now you can't remove articles from selections page

fix eds bookmark list page

---

app/components/document/tracking_bookmark_component.html.erb
app/javascript/controllers/bookmark_controller.js
app/views/bookmarks/index.html.erb

remove patches that need bl 3693

---

app/assets/stylesheets/searchworks4/record.css
app/components/access_panels/location_item_component.html.erb

I'm assuming https://github.com/sul-dlss/SearchWorks/pull/5752/files#diff-4e72da72b71b56120fb4b7f3acdd58015209808a5a03183fb0ac42e382e11a40L1 was a merge/rebase error?

Fix a merge issue that broke searching items

---

app/components/databases/search_bar_component.html.erb
app/views/databases/_header.html.erb
spec/features/access_points/databases_spec.rb

update databses masthead link, placeholder text

---

app/views/catalog/_email_form.html.erb

Multi-record emails should include brief.

---

app/components/feedback/feedback_modal_component.html.erb
app/javascript/controllers/feedback_modal_controller.js

We don't need to explicitly show the toast any more.

---

app/assets/stylesheets/searchworks4/record.css
app/components/articles/article_component.html.erb
app/controllers/articles_controller.rb
app/models/eds_document.rb
app/services/eds/html_scrubber.rb
app/views/articles/fulltext_html.html.erb
config/routes.rb
spec/features/article_display_spec.rb
spec/presenters/article_fulltext_link_presenter_spec.rb
spec/support/stub_article_service.rb

... and do a better job mapping their weird markup to HTML.
Fixes #5776

Extract articles+ full text to a separate pop-up

---

app/components/searchworks4/citations/citation_component.html.erb

Use a normal link for refworks

---

config/locales/blacklight.en.yml

Remove refworks icon from the translation

---

.github/workflows/ruby.yml
Jenkinsfile-Folio-Update
Jenkinsfile-Lane-Update
config/deploy.rb

Point jobs back to main

---

app/controllers/articles_controller.rb
spec/controllers/articles_controller_spec.rb

Update extract_fulltext_link for the new EDS client.

---

Jenkinsfile

Point folio-dev back at `main`

---

config/locales/searchworks.en.yml
spec/features/article_record_toolbar_spec.rb

Update article toolbar spec to fix pending tests

---

app/assets/stylesheets/print.css
app/components/access_panels/availability_component.html.erb
app/components/searchworks4/search_result/item_menu_component.html.erb
app/views/catalog/_search_results.html.erb
app/views/layouts/searchworks4.html.erb
app/views/shared/searchworks4/_user_util_links.html.erb
spec/features/blacklight_customizations/results_toolbar_spec.rb
spec/features/responsive/results_toolbar_spec.rb

Label some landmarks and add a print stylesheet that is ok-ish

---

app/javascript/controllers/bookmark_controller.js

Before:
https://github.com/user-attachments/assets/553b0b96-32c7-4c94-abb8-c25fe79ebc23
After:
https://github.com/user-attachments/assets/7b13d89b-6d9a-4ac1-87c3-aa7fcc2e362a

have pages with multiple bookmarks reflect the correct state

---

spec/features/top_nav_spec.rb

possible fix for flappy top_nav test

---

app/components/record_toolbar_component.html.erb

Nobody asked for this, I just *need* to know how much that print button gets used.

Gather analytics for record toolbar use

---

app/assets/stylesheets/print.css

Reset the aside's offcanvas properties for print.

---

app/views/catalog/_home_page.html.erb

Add missing close li tag

---

app/views/articles/_home_page.html.erb

Remove mismatched search end tag

---

app/javascript/adv-search/advanced_search_controller.jsx
spec/features/advanced_search_spec.rb

Populate two search fields by default; fixes #5829

---

app/assets/stylesheets/searchworks4/record.css
app/components/access_panels/library_location_popover_component.html.erb
app/components/access_panels/library_location_popover_component.rb
app/javascript/controllers/index.js
app/javascript/controllers/popover_controller.js
app/javascript/popover.js

create dimissible popover that doesn't disappear when interacted with

---

app/views/shared/searchworks4/_top_navbar.html.erb

Always show the featured resource dropdown; part of #5854

---

app/assets/stylesheets/searchworks4.scss
app/assets/stylesheets/searchworks4/variables.css
app/views/catalog/opensearch.xml.builder
app/views/layouts/searchworks4.html.erb

Update to latest version of the component-library

---

app/components/articles/document_list_component.html.erb

Add missing div close tag

---

app/views/catalog/_new_search.html.erb

Add missing li close tag

---

app/views/layouts/searchworks4.html.erb

Add preconnect link tags for remote asset hosts

---

app/views/search_works_record_mailer/full_email_record.html.erb

Add missing article end tag in full_email_record

---

app/views/catalog/_document_gallery.html.erb

Replace empty elsif with else

---

.rubocop.yml
app/components/access_panels/at_the_library_component.html.erb
app/components/access_panels/library_header_component.html.erb
app/components/access_panels/library_header_component.rb
app/components/searchworks4/availability_accordion_component.html.erb
app/components/searchworks4/availability_accordion_component.rb
app/views/catalog/availability_modal.html.erb
lib/holdings.rb

Availability modal

---

app/javascript/controllers/database_autocomplete_controller.js
app/javascript/controllers/exhibit_panel_controller.js
app/javascript/controllers/facet_search_controller.js

Remove extraneous console.log calls

---

app/views/catalog/_zero_results.html.erb

Move the period out of the link

---

app/views/catalog/_home_page.html.erb

Add `(SDR)` to digital collections

---

app/javascript/controllers/feedback_modal_controller.js

I think we need https://github.com/projectblacklight/blacklight/blob/68322439661b5e42b552b67d6cb2f521e5722824/app/javascript/blacklight-frontend/modal.js#L170 to restore scrolling after submit

Restore scroll after feedback modal submit

---

app/controllers/catalog_controller.rb
spec/requests/stackmap_spec.rb

Fix missing template error

---

spec/components/feedback/feedback_form_fields_component_spec.rb
spec/components/feedback/feedback_modal_component_spec.rb
spec/components/feedback/feedback_standalone_component_spec.rb

Remove unnecessary stubbing

---

app/components/searchworks4/search_result/collection_info_component.html.erb

Remove unnecessary span close tag

---

app/views/databases/_popular_databases.html.erb
config/ezproxy/lane_proxy_file.txt
config/ezproxy/law_proxy_file.txt
config/ezproxy/sul_proxy_file.txt

These were applied to `release`.
Fixes #5586 etc

Sync configs

---

app/views/databases/_popular_databases.html.erb

Finish removing ezproxy cruft from scholar.google.com link

---

app/controllers/availability_controller.rb
config/routes.rb
spec/controllers/availability_controller_spec.rb

Remove old, unused availability routes

---

app/assets/stylesheets/searchworks4/bookmarks.css
app/assets/stylesheets/searchworks4/record.css
app/assets/stylesheets/searchworks4/search.css
app/assets/stylesheets/searchworks4/typography.css
app/components/access_panels/availability_component.html.erb
app/components/access_panels/library_header_component.html.erb
app/components/access_panels/library_header_component.rb
app/components/access_panels/library_location_component.html.erb
app/components/document/tracking_bookmark_component.html.erb
app/components/document/tracking_bookmark_component.rb
app/components/icons/bookmark_icon_component.rb
app/components/record_toolbar_component.html.erb
app/components/search_result/document_gallery_component.html.erb
app/components/searchworks4/physical_availability_component.html.erb
app/components/stackmap/map_component.html.erb
app/helpers/masthead_helper.rb
app/javascript/controllers/bookmark_controller.js
app/javascript/controllers/course_reserves_controller.js
app/views/catalog/_zero_results.html.erb
app/views/catalog/mastheads/_course_reserve.html.erb
app/views/catalog/mastheads/_digital_collections.html.erb
app/views/catalog/mastheads/_dissertation_theses.html.erb
app/views/catalog/mastheads/_government_documents.html.erb
app/views/catalog/mastheads/_iiif_resources.html.erb
app/views/catalog/mastheads/_sdr.html.erb
app/views/course_reserves/index.html.erb
app/views/databases/home_page.html.erb

Use .icon-link to provide the appropriate padding + alignment for links with icons

---

app/helpers/thumbnail_helper.rb
app/views/catalog/thumbnails/_marc_collection_thumbnail.html.erb
app/views/catalog/thumbnails/_marc_thumbnail.html.erb
app/views/catalog/thumbnails/_mods_collection_thumbnail.html.erb
app/views/catalog/thumbnails/_mods_thumbnail.html.erb
spec/helpers/thumbnail_helper_spec.rb

Remove display_type template indirection for rendering thumbnails.

---

app/components/record/document_component.rb
app/components/record/marc_document_component.html.erb
app/components/record/mods_document_component.html.erb
app/presenters/concerns/catalog_fields.rb
spec/features/bookplates_spec.rb

Replace display_type with specific calls.

---

app/helpers/catalog_helper.rb
spec/features/results_page_spec.rb

Fixes #5825
Replacement for #5831

Use friendly library names in page title

---

app/helpers/collection_helper.rb
app/models/concerns/digital_collection.rb
spec/helpers/collection_helper_spec.rb
spec/models/concerns/digital_collection_spec.rb

I suspect the query building work in #4912 makes the additional lookup unnecessary.

Remove #collection_id.

---

app/helpers/collection_helper.rb
app/views/catalog/show.html.erb

Restore the PURL embed tags. Fixes #5533

---

app/components/document/tracking_bookmark_component.html.erb

https://github.com/sul-dlss/SearchWorks/pull/5876 removed these

Remove unused bookmark actions

---

app/components/articles/article_component.html.erb
app/components/articles/article_component.rb

[Refactor] Extract method for fulltext link url into the class

---

app/components/searchworks4/physical_availability_component.html.erb
app/components/searchworks4/physical_availability_component.rb
app/services/fixture_harvester.rb
spec/component_previews/searchworks4/availability_component_preview.rb
spec/components/searchworks4/availability_component_spec.rb
spec/features/access_points/digital_collections_spec.rb
spec/fixtures/solr_documents/11966809.yml

Fixes  [#5599](https://github.com/sul-dlss/SearchWorks/issues/5599).

Add another physical availability display case for finding-aid-pageable records.

---

config/environments/production.rb

Tell lookbook where to find previews in production.

---

app/components/search_result/document_gallery_component.html.erb

Capitalize 'in' on gallery card

---

app/views/articles/index.json.jbuilder

https://github.com/sul-dlss/sul-bento-app/blob/46bb8e250f8d54fc423a53966e975e55c98e663c/app/services/article_search_service.rb#L23

Restore article id in json response for Bento

---

app/models/concerns/marc_links.rb
app/models/links/link.rb
spec/models/concerns/marc_links_spec.rb

Prioritize ebsco-provided links

---

app/views/databases/_header.html.erb

Update database header to use sentence case

---

app/components/access_panels/related_component.html.erb
spec/components/access_panels/related_component_spec.rb

Fix OCLC number in worldcat link

---

app/components/access_panels/availability_component.html.erb

Tweak the expand button styles.

---

app/components/access_panels/online_component.html.erb

Tweak connection problem styles.

---

config/solr_configs/schema.xml

.. instead of playing whack-a-mole with callnumbers that we're not quite normalizing great.

Add `callnum_exact_search` field

---

app/components/searchworks4/physical_availability_component.rb

Fixes #6037 (caused by bad data that should probably be purged from solr.. Jeanette is doing some analysis.)

Handle some bad data where we're missing permanent locations.

---

config/locales/searchworks.en.yml
spec/features/article_searching_spec.rb
spec/features/results_page_spec.rb

Update search results page title. Fixes #6051

---

app/components/access_panels/online_component.html.erb
app/components/searchworks4/online_accordion_component.html.erb
spec/components/access_panels/online_component_spec.rb

Update text from 'Also available at' to 'Also online at'

---

app/javascript/controllers/long_text_controller.js

Only pass through the button style if it is set.

---

app/assets/stylesheets/searchworks4/modal.css
app/components/main_container_component.html.erb
app/components/searchworks4/record_summary_component.rb

Improve modal thumbnails

---

app/models/marc_fields/date_008.rb
app/presenters/concerns/catalog_fields.rb
spec/components/record/marc_document_component_spec.rb

Change the display of imprecise dates

---

app/assets/stylesheets/searchworks4/bookmarks.css
app/components/document/save_all_bookmarks_component.html.erb
app/components/document/save_all_bookmarks_component.rb
app/javascript/controllers/bookmark_all_controller.js
app/javascript/controllers/bookmark_controller.js
app/javascript/controllers/index.js
app/views/catalog/_search_results.html.erb
config/routes.rb
spec/features/bookmarking_items_spec.rb

Add save all records button to results view

---

app/components/searchworks4/quick_report_component.html.erb
spec/features/quick_report_spec.rb

Update feedback form button language

---

app/components/stackmap/map_component.html.erb
app/javascript/controllers/stackmap_controller.js

Hide the stackmap directions tab if there are no directions

---

app/assets/stylesheets/searchworks4/item-preview.css
app/assets/stylesheets/searchworks4/record.css
app/components/record/item/marc/callnumber_browse_component.html.erb
app/components/search_result/document_gallery_component.html.erb
app/components/searchworks4/gallery_card_preview_button_component.html.erb
app/components/searchworks4/gallery_card_preview_button_component.rb
app/javascript/controllers/gallery_card_controller.js
app/views/collection_members/_image_collection_filmstrip.html.erb
spec/features/callnumber_browse_spec.rb

Update preview styles

---

app/components/searchworks4/search_result/collection_info_component.html.erb
app/components/searchworks4/search_result/collection_info_component.rb

Start updating the collection masthead

---

app/assets/stylesheets/searchworks4/modal.css

Anchor the availability modal

---

config/ezproxy/sul_proxy_file.txt

Add thepolynesiansociety.org to proxy file

---

app/assets/stylesheets/searchworks4/typography.css
app/assets/stylesheets/searchworks4/variables.css
app/components/searchworks4/document_component.html.erb
app/components/searchworks4/document_component.rb
app/components/searchworks4/document_flag_component.html.erb
app/components/searchworks4/document_flag_component.rb
app/models/concerns/marc_links.rb
spec/features/results_page_spec.rb

Add collection flags to search results.

---

config/blacklight.yml

Set some reasonable solr timeouts.

---

app/assets/stylesheets/searchworks4/typography.css
app/assets/stylesheets/searchworks4/variables.css
app/components/access_panels/collection_component.html.erb
app/components/access_panels/grouped_library_component.html.erb
app/components/record/marc_document_component.html.erb
app/components/searchworks4/finding_aid_link_component.rb
app/components/searchworks4/search_result/collection_info_component.html.erb

Style finding aid links as buttons.

---

.solr_wrapper

Test with Solr 9.9

---

app/helpers/marc_helper.rb

Update get_uniform_title to support structured vernacular data.

---

app/helpers/facets_helper.rb

Deprioritize the microform format when selecting an icon.

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/articles_controller.rb
app/controllers/catalog_controller.rb
config/initializers/bot_challenge_page.rb
config/routes.rb
config/settings.yml

Add turnstile configuration for searches.

---

app/javascript/adv-search/advanced_search_controller.jsx

Account for the extra search field.

---

app/components/access_panels/additional_info_component.html.erb
app/components/access_panels/grouped_library_component.html.erb
app/components/access_panels/library_component.html.erb
app/components/access_panels/library_location_component.html.erb
spec/features/mhld_spec.rb

Tweak availability spacing.

---

config/initializers/bot_challenge_page.rb

Allow turnstile user agents to match fragments

---

config/initializers/rack_attack.rb

Relax rack attack /16 + /24 limits now that we have turnstile enabled
