sul-dlss/SearchWorks

app/views/layouts/searchworks.html.erb
config/settings.yml
spec/features/blacklight_customizations/layout_spec.rb

Not obscuring verification code since it's not necessarily a secret (i.e. it's directly in the head of all of our pages).  Allowing it to be settable via rails_config.

Add google site verification code for Webmaster Tools.

---

app/views/catalog/record/_callnumber_browse.html.erb

Removed no longer necessary `collapse` class
This commit introduced `visibility: hidden` to `collapse` class: https://github.com/twbs/bootstrap/commit/6cfd176ac3d0eedc5b9b50fd88bf0774af0f1222

fixes the missing browse nearby mystery

---

lib/holdings/location.rb
spec/lib/holdings/location_spec.rb

This is currently causing an error for any LANE record that has no barcoded items and only has MHLD data.

Don't try to link to a barcoded LANE item when there are only MHLDS.

---

app/assets/javascripts/jquery.plug-google-content.js
spec/features/blacklight_customizations/record_metadata_spec.rb
spec/features/blacklight_customizations/results_document_spec.rb

Closes #963 
@jchristo4 does this seem reasonable to you?  I think Google will return the numbers in the order we send them in and since we'll only try to set the image for the first match we have in the response this should address the issue where OCLC/LCCN matches are being used when an ISBN is returned first.

Only set the thumbnail URL if it's not already set.

---

Gemfile.lock

http://weblog.rubyonrails.org/2015/6/16/Rails-3-2-22-4-1-11-and-4-2-2-have-been-released-and-more/

Updated rails and related dependencies to fix security issues

---

app/assets/javascripts/jquery.managed-purl.js
app/assets/stylesheets/base.css.scss
app/assets/stylesheets/modules/access-panel-library-locations.css.scss
app/assets/stylesheets/modules/managed_purl_panel.scss
app/assets/stylesheets/modules/record-metadata-section.css.scss
app/assets/stylesheets/searchworks-mixins.css.scss
app/assets/stylesheets/searchworks.css.scss
app/assets/stylesheets/sul-variables.css.scss
app/models/concerns/digital_image.rb
app/models/concerns/index_links.rb
app/models/concerns/marc_links.rb
app/views/catalog/_managed_purl_embed.html.erb
app/views/catalog/_show_merged_image.html.erb
app/views/catalog/record/_record_metadata_merged_image.html.erb
config/settings.yml
config/settings/test.yml
config/solr_configs/schema.xml
lib/access_panels/online.rb
lib/links.rb
spec/features/purl_embed_spec.rb
spec/fixtures/marc_records/marc_856_fixtures.rb
spec/fixtures/solr_documents/11.yml
spec/fixtures/solr_documents/8923346.yml
spec/lib/access_panels/online_spec.rb
spec/lib/links_spec.rb
spec/models/concerns/digital_image_spec.rb
spec/models/concerns/index_links_spec.rb
spec/models/concerns/marc_links_spec.rb

@mejackreed I've added some tests here.  I think it's ready to :ship: for deploy this week.

Add feature to handle many managed PURLs in one record

---

lib/purl_embed.rb
spec/lib/purl_embed_spec.rb

This is an immediate solution to the PURL not existing in records.

Update PURL embed URL to include metadata panel.

---

app/assets/javascripts/jquery.requestsModal.js

This is an attempt to stop the bouncing modal issue when using the date-picker.

Don't allow requests modal iframe to scroll.

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

This is to try and get rid of the `ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked` errors we see intermittently on travis.

Add database cleaner and implement in spec helper.

---

app/assets/javascripts/jquery.stackmap.js
app/assets/stylesheets/modules/stackmap.css.scss
app/views/catalog/_stackmap_link.html.erb
app/views/catalog/stackmap.html.erb
lib/constants.rb
lib/holdings/callnumber.rb
spec/lib/holdings/callnumber_spec.rb
spec/views/catalog/stackmap.html.erb_spec.rb

StackMap Changes

---

app/views/catalog/mastheads/_government_documents.html.erb

Update government documents access point masthead text.

---

app/assets/javascripts/skip-to-nav.js
spec/features/skip_to_nav_spec.rb

Add javascript to set explicitly set focus on skip-to-nav elements.

---

app/helpers/record_helper.rb
spec/helpers/record_helper_spec.rb

Note that the functional change is in 5c0a804.
21e9881 is just rubocop autofixes.
This addresses an issue reported by a stakeholder but not ticketed.

Fix bug in mods primary vs. secondary name identification

---

app/assets/javascripts/jquery.plug-google-content.js
app/helpers/results_document_helper.rb
spec/helpers/results_document_helper_spec.rb

Closes #720
1. Normalize standard numbers to remove whitespace and useless characters before sending to into the Google API (this was causing some LCCNs to be viewed as ISBNs).
2. Instead of looping through the indeterminately sorted JSON response we are looping through the images, and selecting the piece from the JSON response based on the best key available.

Address a few issues around GBS book covers

---

app/assets/stylesheets/modules/access-panel.css.scss

Fix wrapping of library names in access panel

---

app/helpers/marc_helper.rb
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/helpers/marc_helper_spec.rb

Modifying existing marc_264 helper to add  to the whitelisted subfields.

---

app/helpers/marc_helper.rb
spec/features/marc_results_metadata_spec.rb
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/helpers/marc_helper_spec.rb

Closes #1093 
Note that 6591f9e is the commit with the functional change.  ef74181 is a little bit of a refactor.

Don't link $h in uniform titles

---

app/helpers/marc_helper.rb
app/models/concerns/marc_bound_with_note.rb
app/models/marc_field.rb
app/models/marc_fields/bound_with_note.rb
app/models/solr_document.rb
app/views/catalog/access_panels/_location.html.erb
app/views/marc_fields/_bound_with_note.html.erb
app/views/marc_fields/_marc_field.html.erb
config/application.rb
config/locales/searchworks.en.yml
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/helpers/marc_helper_spec.rb
spec/models/marc_field_spec.rb
spec/models/marc_fields/bound_with_note_spec.rb
spec/models/solr_document_spec.rb
spec/views/marc_fields/_bound_with_note.html.erb_spec.rb
spec/views/marc_fields/_marc_field.html.erb_spec.rb

Closes #1092 
Note 6d7eadc adds a Base MARC Field parsing class that handles most,if not all of the universal parsing code.
1ac3d40 build on top of that class to allow us to easily pull out the bound-with note.
My hope is that we can use (and enhance) this new MARC field parsing class for the upcoming MARC issues when possible, instead of trying to coerce the existing parsing code.

Only show bound-with note in holdings when 590$c is present

---

app/helpers/results_document_helper.rb
spec/helpers/results_document_helper_spec.rb

Connects to #1140  
which will be finished when:
- solrconfig change deployed to prod (sul-dlss/solrmarc-sw#123)
- MODS data reindexed with sul-dlss/sw-indexer-service#52
- This PR is deployed)
Also:
- connects to sul-dlss/sw-indexer-service#43 (search results piece of index BCE dates for coin collection)
- connects to sul-dlss/solrmarc-sw#111 (BCE dates for coin collection)
- connects to sul-dlss/stanford-mods#56:  display part of adds B.C. to dates before year 0, adds A.D. to dates
- connects to sul-dlss/stanford-mods#53:  display part of nice string for decades (1950s for 195u); nice string for centuries (18th century for 17uu)

Fix MODS date display in search result title

---

app/helpers/marc_helper.rb
app/models/concerns/marc_imprint.rb
app/models/concerns/marc_series.rb
app/models/concerns/series_linkable.rb
app/models/marc_field.rb
app/models/marc_fields/imprint.rb
app/models/marc_fields/instrumentation.rb
app/models/marc_fields/linked_series.rb
app/models/marc_fields/marc_field_wrapper.rb
app/models/marc_fields/unlinked_series.rb
app/models/solr_document.rb
app/views/catalog/record/_marc_bibliographic.html.erb
app/views/catalog/record/_marc_upper_metadata_items.html.erb
app/views/marc_fields/_linked_series.html.erb
config/locales/searchworks.en.yml
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/helpers/marc_helper_spec.rb
spec/models/concerns/marc_series_spec.rb
spec/models/marc_field_spec.rb
spec/models/marc_fields/linked_series_spec.rb
spec/models/marc_fields/marc_field_wrapper_spec.rb
spec/models/marc_fields/unlinked_series_spec.rb
spec/models/solr_document_spec.rb
spec/views/marc_fields/_linked_series.html.erb_spec.rb

This refactor closes #1095 and closes #94

Refactor MARC series linking helper

---

app/helpers/marc_helper.rb
app/models/marc_field.rb
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/helpers/marc_helper_spec.rb
spec/models/marc_field_spec.rb

Closes #1091 
This PR also includes adding this behavior to the base `MarcField` class although it is not actually used (yet) for parsing the fields in question.
_Note, that @jvine approved the dropping of $4 in the old MARC vernacular helper_

Fix MARC relator code translations in a few places

---

spec/fixtures/solr_documents/31.yml
spec/fixtures/solr_documents/32.yml
spec/fixtures/solr_documents/33.yml
spec/fixtures/solr_documents/38.yml
spec/fixtures/solr_documents/39.yml
spec/fixtures/solr_documents/40.yml
spec/fixtures/solr_documents/41.yml
spec/fixtures/solr_documents/42.yml
spec/fixtures/solr_documents/43.yml

**Note: This only applies to the fixtures in dev/test**

Update formats in fixture data to ones that correspond with icons.

---

app/assets/stylesheets/modules/bookmarks.scss
app/assets/stylesheets/modules/record-view.scss
app/assets/stylesheets/modules/top-navbar.scss
app/views/shared/_top_navbar.html.erb

Couple of CSS changes

---

spec/tasks/fixtures_indexer_spec.rb

We currently get intermittent failures when the document's catalog date is 1 second off (since one fixture sets its cataloged date to the current time).
This changes the test to ensure that documents are being added but does not evaluate that all the fields are identical (which really is not necessary).

Update fixture indexer spec be more tolerant of changing catalog dates.

---

app/models/marc_fields/linked_serials.rb
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/models/marc_fields/linked_serials_spec.rb

This fixes a bug that was reported automatically via squash.

Use canonical tag for fetching label in linked serials.

---

app/views/catalog/thumbnails/_item_thumbnail.html.erb
spec/views/catalog/thumbnails/_item_thumbnail.html.erb_spec.rb

Do not render Book Cover image when there is a known stacks image.

---

lib/constants.rb

I think this was just an oversight.  The first image below (10624866) is a non-in process item.  The 2nd image (10448245) is an in-process item just as a sanity check.

Add RUMSEYMAP as a request library.

---

app/views/catalog/_managed_purl_embed.html.erb

Drop druid from thumbnail of multi-managed-purl switcher.

---

lib/constants.rb

Make TECH-DESK NON-Requestable.

---

app/assets/javascripts/jquery.requestsModal.js

If the timer expires we set the height to something that should be large enough to handle the WebAuth form.
Part of sul-dlss/sul-requests#492
_Note: The bottom of the page is cutoff by the browser not the modal and is scrollable_

Set a 2.5 second timer for receiving height updates from requests.

---

app/helpers/marc_helper.rb
app/models/concerns/marc_metadata.rb
app/models/marc_fields/linked_author.rb
app/views/catalog/_marc_search_results_document_fields.html.erb
app/views/catalog/record/_marc_contributors.html.erb
app/views/marc_fields/_linked_author.html.erb
app/views/marc_fields/_linked_author_index.html.erb
config/locales/searchworks.en.yml
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/helpers/marc_helper_spec.rb
spec/lib/search_works_marc_spec.rb
spec/models/marc_fields/linked_author_spec.rb
spec/views/catalog/_index_marc.html.erb_spec.rb
spec/views/marc_fields/_linked_author.html.erb_spec.rb
spec/views/marc_fields/_linked_author_index.html.erb_spec.rb

This PR fixes #1321. It introduces a new `MarcField` class to handled linked "authors" so that we can implement 110 and 111 records. Currently, we're just using data from Solr fields to display and link the record. The linking semantics are more nuanced as described in #1321 so we need to generate them directly from MARC. This PR also ports over the 100 records previously handled by `link_to_author_from_marc`. The changes appear in both search results and show pages.

add new LinkedAuthor class for rendering linked "authors" and 711 $j suppression

---

app/views/catalog/record/_marc_bibliographic.html.erb

This PR fixes #1341 by changing the label for 555 content in the bibliographic section.

Change label for 555 finding aids

---

app/models/concerns/marc_metadata.rb
app/models/marc_fields/place_name.rb
app/views/catalog/record/_marc_bibliographic.html.erb
config/locales/searchworks.en.yml
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/models/marc_fields/place_name_spec.rb

Closes #1338 
- Changes the 'Location' delimiter to --
- Uses the MarcField class convention

Add PlaceName MarcField class

---

config/initializers/deprecation_silencer.rb

Hopefully this will help alleviate the issues we've been seeing w/ our disk filling up in production.

Add an initializer to silence deprecation warnings in production.

---

app/helpers/marc_helper.rb
app/models/concerns/marc_metadata.rb
app/models/marc_fields/linked_related_works.rb
app/views/catalog/record/_marc_bibliographic.html.erb
app/views/marc_fields/_linked_related_works.html.erb
config/locales/searchworks.en.yml
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/helpers/marc_helper_spec.rb
spec/models/marc_fields/linked_related_works_spec.rb
spec/views/marc_fields/_linked_related_works.html.erb_spec.rb

This PR fixes #1340. This code extracts the logic from the marc_helper methods which is non-trivial, and I deleted the (newly) unused code from marc_helper.

add new LinkedRelatedWorks MarcField to handle 730 related works

---

app/models/solr_document.rb

Fixes a deprecation warning:
```
DEPRECATION WARNING: Blacklight::Document#[]= is deprecated; use obj.to_h.[]= instead. (called from initialize at /Users/drh/workspace/SearchWorks/app/models/solr_document.rb:37)
DEPRECATION WARNING: Blacklight::Document#initialize expects a hash-like object, received SolrDocument. (called from initialize at /Users/drh/workspace/SearchWorks/app/models/solr_document.rb:38)
```

fix deprecation warning about SolrDocument initializer

---

app/controllers/catalog_controller.rb
app/controllers/hours_controller.rb

This PR fixes missing template 500 errors for bad requests to json apis.

fix missing public/500 template for bad requests

---

Gemfile.lock

This addresses the session issues we were seeing when initially pushing to prod yesterday.

Updating to blacklight 6.10.1.

---

app/assets/javascripts/article.js
app/assets/stylesheets/modules/article.scss
app/assets/stylesheets/modules/home-page.scss
app/assets/stylesheets/searchworks.scss
app/controllers/article_controller.rb
app/helpers/article_helper.rb
app/views/article/new.html.erb
config/routes.rb
spec/controllers/article_controller_spec.rb
spec/helpers/article_helper_spec.rb
spec/routing/article_routes_spec.rb
spec/views/article/new.html.erb_spec.rb

This PR fixes #1379.
Notes:
- I kept the empty helper/javascript/css that the controller generator -- I'm assuming that we'll need them later
- I wasn't sure if we wanted the "RELATED" links to be configurable or not? They are hardcoded into the view template like the current home page has. If so, I suggest we make a different ticket for that.
- The banner still says "SearchWorks catalog" but that's addressed in another ticket: #1378 
- The styling is not exactly like the screenshot in the #1379 ticket because I'm using the existing styling for the SearchWorks home page, i.e., the underlined headers, etc.
- The rails route is `/article/home` is an alias to a restful route `/article/new` as I'm assuming that we'll want more restful routes

adds a new Article search landing page at /article/home

---

app/views/bookmarks/_tool_dropdown.html.erb

Fixes #1387 
This appears to only be failing at the apache level, which is why we never got this locally or in tests.
This is currently deployed to stage if anybody wants to test it out.

Update the bookmark email path per BL6.

---

app/assets/stylesheets/modules/search-bar.scss
app/helpers/application_helper.rb
app/helpers/article_helper.rb
app/views/catalog/_search_form.html.erb
app/views/catalog/_search_targets_widget.html.erb
config/locales/searchworks.en.yml
spec/features/article_searching_spec.rb
spec/features/home_page_spec.rb
spec/helpers/application_helper_spec.rb
spec/helpers/article_helper_spec.rb

Closes #1378 
There is some left to be desired w/ the styling, but knowing that this search bar area is going to go through some significant changes for article search we figured we shouldn't spend too much time on it.

Add a dropdown to switch between Catalog and Article Search

---

lib/constants.rb
lib/holdings/callnumber.rb
spec/lib/holdings/callnumber_spec.rb

This PR fixes #1304.
Marked **WIP** until we can verify that the stackmap.com API is working for the ART library.

add support for stackmap blacklists and add ART as a new stackmapable library

---

Gemfile.lock
app/controllers/article_controller.rb
app/controllers/catalog_controller.rb
app/helpers/results_document_helper.rb
app/presenters/concerns/presenter_format.rb
app/presenters/index_document_presenter.rb
app/presenters/show_document_presenter.rb
app/views/article/_index_default.html.erb
app/views/article/index.html.erb
app/views/browse/_index_header_default.html.erb
app/views/catalog/_index_brief.html.erb
app/views/catalog/_index_header_default.html.erb
app/views/catalog/_index_header_gallery.html.erb
app/views/catalog/_show_header_default.html.erb
lib/constants.rb
spec/helpers/results_document_helper_spec.rb
spec/presenters/presenter_format_spec.rb

Closes #1394 
Things that are not necessarily in this PR, and can prob. be deferred are:
* Allow bookmarks toggle to work (this is going to take some serious consideration)
* Remaining citation details (pending convo w/ EBSCO)

Update styling of article search results documents

---

app/assets/stylesheets/layout.scss
app/assets/stylesheets/modules/buttons.scss
app/assets/stylesheets/modules/search-bar.scss
app/assets/stylesheets/modules/subnavbar.scss
app/assets/stylesheets/modules/top-navbar.scss
app/assets/stylesheets/searchworks.scss
app/assets/stylesheets/sul-variables.scss
app/controllers/article_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_search_bar_advanced_widget.html.erb
app/views/catalog/_search_bar_nav_list.html.erb
app/views/catalog/_search_bar_selections_widget.html.erb
app/views/layouts/searchworks.html.erb
app/views/shared/_search_bar.html.erb
app/views/shared/_search_navbar_top_menu.html.erb
app/views/shared/_search_subnavbar.html.erb
app/views/shared/_top_navbar.html.erb
config/locales/searchworks.en.yml
spec/features/advanced_search_spec.rb
spec/features/blacklight_customizations/search_toolbar_spec.rb
spec/features/blacklight_customizations/search_types_spec.rb
spec/features/course_reserves_browse_spec.rb
spec/features/responsive/search_toolbar_responsive_spec.rb
spec/features/responsive/subnav_responsive_spec.rb
spec/features/show_page_spec.rb
spec/features/top_nav_spec.rb

This PR fixes #1396.  I will deploy this branch to the sandbox for testing.
Notes for things that do not work:

Restructure the banner into a red search bar and a grey navbar

---

app/assets/stylesheets/modules/article.scss
app/controllers/article_controller.rb
app/helpers/article_helper.rb
app/presenters/concerns/presenter_fulltext_links.rb
app/presenters/index_document_presenter.rb
app/presenters/show_document_presenter.rb
app/views/article/_index_default.html.erb
app/views/article/show.html.erb
spec/helpers/article_helper_spec.rb
spec/presenters/presenter_fulltext_links_spec.rb

Show fulltext links on results and show pages

---

app/controllers/article_controller.rb
spec/controllers/article_controller_spec.rb

This PR fixes #1412.
Verified that it's working correctly with Bill and Eric on Slack. Basically you can look at the Faraday logs to see the API traffic (set EDS_DEBUG=true in your setteings). It should not issue a CreateSession call unless you clear your browser cookies.

persist the EDS session token between Blacklight sessions

---

Gemfile.lock
app/controllers/article_controller.rb
app/views/article/index.html.erb

Closes #1398 
Consideration for pulling into a separate ticket: More facet modal
A few notes on behavior (not sure if these things are configureable on the ebsco side):
* The facets appear to be `OR` not `AND` like our catalog search facets are
* Some facets appear to not return the selected value in the facet response (e.g. Language), so the only way to remove the facet would be by the breadcrumb.
* Some facets appear to not be returned at all once a value is selected (e.g. Publisher), which might just be a symptom of the issue above.

Configure and render facets.

---

app/assets/stylesheets/modules/subnavbar.scss

A minor tweak to the gray navbar alignment.

right align the Selections pulldown in the gray bar

---

app/controllers/article_controller.rb
app/views/article/_index_brief_default.html.erb
app/views/article/_search_header.html.erb

This PR fixes #1424. The View menu is pulled right for now.

add Brief index view

---

app/controllers/article_controller.rb
app/views/article/_search_header.html.erb
spec/features/article_searching_spec.rb
spec/features/sort_and_per_page_dropdown_spec.rb
spec/support/stub_article_service.rb

This PR fixes #1449. Note in the screenshot the styling is done in another PR. It also relocates some sample Article search results into the `StubArticleService` class for reuse.

add Sort dropdown for Article search

---

app/assets/stylesheets/modules/sort-and-per-page-toolbar.scss
app/views/kaminari/blacklight_compact/_next_page.html.erb
app/views/kaminari/blacklight_compact/_paginator.html.erb
app/views/kaminari/blacklight_compact/_prev_page.html.erb
spec/features/blacklight_customizations/results_toolbar_spec.rb
spec/features/responsive/results_toolbar_spec.rb

This PR fixes #1423. See screenshots for various cases.

Change Prev/Next from disabled to hidden on search results

---

app/views/article/_index.html.erb
spec/features/article_searching_spec.rb

Closes #1428 
This PR adds the sidebar nav to article search results. Users can jump to the top or bottom of the search results. 
I also added a page object to DRY out our article search spec a bit.

Add top/bottom sidenav to article search results

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/modules/record-view.scss
app/assets/stylesheets/modules/search-bar.scss
app/assets/stylesheets/searchworks-mixins.scss
app/views/catalog/_search_targets_widget.html.erb

This PR makes updates to the search bar UI. 
- Restricts dejavu font to record titles and uses Source Sans Pro for other h1s
- Adds `<h1>` to the search context dropdown for accessibility purposes
- Adds spans for styling dropdown labels
- Adjusts positioning of the search context dropdown

Searchbar dropdown UI updates

---

app/controllers/article_controller.rb
spec/features/article_searching_spec.rb
spec/support/stub_article_service.rb

Closes #1473
This PR
- adds `eds_subjects` to our first stubbed article
- only unlinks subject terms in the search results
- reorganizes tests in `article_searching_spec.rb`

Unlink subject terms in article search results

---

.gitignore
app/controllers/article_controller.rb
app/helpers/blacklight_url_helper.rb
app/models/article_search_builder.rb
app/models/eds/repository.rb
app/services/eds/search_service.rb
config/routes.rb
config/settings.yml
spec/controllers/article_controller_spec.rb
spec/models/eds/repository_spec.rb
spec/routing/article_routes_spec.rb
spec/services/eds/search_service_spec.rb

This PR is connected to #1471.
I refactored Eds::SearchService/Repository which allows us to use our own `ArticleSearchBuilder` rather than the existing Catalog's `SearchBuilder` (which has a processing chain that we shouldn't use). 
The core issue is that the Previous/Next buttons weren't working on the show page (and I also believe on the index page too), so this PR mainly cleans up the code path to reduce the potential for problems. I've added support for the `track` action on Articles in the routing, and updated the `id` constraints to match the EDS document id rules.
The refactoring also allows us to use the Blacklight `index`, `show`, and `track` methods as-is in `ArticleController` rather than define them ourselves (and lose features like the `.json` API).
For …

Use ArticleSearchBuilder to pass queries onto EDS API

---

app/models/article_search_builder.rb

This PR uses `page` rather than `start` for the EDS `page_number`. Fixes #1487 
From EBSCO:
> `page_number`: Starting page number for the result set returned from a search (if results per page = 10, and page number = 3 , this implies: I am expecting 10 records starting at page 3).
> `results_per_page`: The number of records retrieved with the search results (between 1-100).

use page rather than start for page number

---

spec/models/article_search_builder_spec.rb

This PR adds the missing spec for `ArticleSearchBuilder`

add ArticleSearchBuilder spec

---

app/assets/stylesheets/modules/search-bar.scss
config/locales/searchworks.en.yml

Closes #1442
This PR fixes the alignment of our search dropdown in smaller view sizes. @jvine Let me know your thoughts on the `width: 100%` . I did a quick attempt at trying to keep the dropdown its original width, but keeping things right aligned was a little finicky. 
I also restored the `h3` spans on the dropdown...I think they disappeared during rebasing the other day.

Add responsive behavior to search dropdown options

---

app/assets/stylesheets/modules/sort-and-per-page-toolbar.scss
app/assets/stylesheets/modules/sul-toolbar.scss

Closes #1475 
This PR ensures that `.sul-toolbar` appears 40px in the record view.

Fix sul-toolbar height in record view

---

app/views/shared/_search_subnavbar.html.erb
spec/features/article_searching_spec.rb

Closes #1456 
This PR removes Advanced search, Course reserves, and Selections from the subnavbar when using article search. Advanced search and Selections may be re-introduced later, per discussion in #1456 
>- do not show Course reserves in Article search
>- do not show Advanced search in Article search until we have that specific feature
>- suppress Selections until we know how to handle Article bookmarks

Remove catalog-related subnav menus from article search context

---

app/controllers/article_controller.rb
spec/features/article_record_toolbar_spec.rb

This PR fixes #1493. The implementation is geared toward making it easy to turn the navigation back on when we get a revised EDS gem. 
So, we don't show the Back to results, Previous, Next buttons or the "1 of n" text.

remove record toolbar navigation temporarily

---

config/routes.rb
spec/routing/article_routes_spec.rb

This PR permits tildes `~` to be used in the EDS `id` parameter

permit tildes in the EDS identifiers

---

app/presenters/concerns/presenter_fulltext_links.rb
spec/presenters/presenter_fulltext_links_spec.rb
spec/views/article/access_panels/_online.html.erb_spec.rb

This PR is connected to #1476. It rewrites the `PresenterFulltextLinks.fulltext_links` to support re-labeling and prioritization.

prioritize and relabel full text links

---

app/controllers/article_controller.rb
app/helpers/article_helper.rb
app/models/article_search_builder.rb
spec/helpers/article_helper_spec.rb
spec/models/article_search_builder_spec.rb

This PR is connected to #1466. Instead of stripping out HTML, we're marking them HTML-safe in this PR.
It won't close the #1466 ticket until the UTF-8 encoding errors are fixed (see comments in ticket).

Marks various EDS metadata as HTML-safe and disables unused highlighting

---

app/assets/stylesheets/modules/record-metadata-section.scss
app/controllers/article_controller.rb
app/helpers/article_helper.rb
app/views/article/_show_default.html.erb
config/locales/searchworks.en.yml
spec/features/article_display_spec.rb
spec/helpers/article_helper_spec.rb

Fixes part of #1482 
Adds HTML full text to the article record view. 
- Full text can only be accessed in authenticated mode
- Adds a helper_method, `sanitize_fullltext` that strips out EBSCO's `<anid>` tag
- Full Text and Summary are currently excluded from the sidenav sections
- Full text hide/show behavior has been split off to another ticket #1509

Display HTML full text in article show page

---

spec/features/blacklight_customizations/emailing_records_spec.rb

This PR updates how `submit` is triggered in `emailing_records_spec.rb`. Once we rebase these changes into `article-search`, this will hopefully address our failing Travis builds.

Update emailing record spec button trigger

---

Gemfile.lock

The latest ebsco-eds gem adds support for `eds_publication_year_range_facet` and the DE (descriptor) field code.

upgrade to ebsco-eds 0.2.7.pre

---

app/models/eds/repository.rb
spec/models/eds/repository_spec.rb

This PR allows double underscores to be included in the accession id.

update EDS ID spliting logic

---

app/assets/javascripts/article.js
app/assets/stylesheets/modules/access-panel-online.scss
app/assets/stylesheets/modules/record-metadata-section.scss
app/models/concerns/eds_document.rb
app/models/solr_document.rb
app/views/article/_show_default.html.erb
app/views/article/record/_html_fulltext.erb
spec/features/article_display_spec.rb
spec/models/concerns/eds_document.rb
spec/models/solr_document_spec.rb

Closes #1509 
This PR adds hide/show functionality for HTML fulltext in the article record view:
- Hides full text by default
- Clicking on the section header (green bar) toggles fulltext
- `View full text / Show full text` does not appear in records where HTML full text is unavailable
- adds a concern for `EdsDocument`

Add article HTML full text hide/show in record view

---

app/controllers/article_controller.rb
app/models/eds/repository.rb
app/models/ip_range.rb
config/initializers/eds.rb
config/settings.yml
spec/models/ip_range_spec.rb

This PR is connected to #1529. It implements simple IP-based authentication which toggles the EDS API's `guest` mode parameter. The `IPRange` class and its specs comes from the sul-requests application.
I've put a `production.local.yml` on the sandbox that has the IP ranges. We need to do further testing on these ranges (which is why this PR does not close the ticket). The set is pretty different than sul-requests' production values.
For local testing, make sure you clear your browser cookies and add this to your `development.local.yml` to authenticate yourself:
```yml
STANFORD_NETWORK:
singletons:
- 127.0.0.1
ranges: []
```
Note we may need to rework this when we integrate Shibboleth workgroup-based authentication, but for now this PR takes a simple approach.

add IP-based authentication for Article Search

---

Gemfile.lock
app/assets/javascripts/article.js
app/assets/stylesheets/modules/research-starter.scss
app/assets/stylesheets/searchworks.scss
app/assets/stylesheets/sul-variables.scss
app/controllers/article_controller.rb
app/helpers/article_helper.rb
app/helpers/blacklight_helper.rb
app/models/article_search_builder.rb
app/models/concerns/eds_document.rb
app/presenters/concerns/presenter_research_starter.rb
app/presenters/show_document_presenter.rb
app/views/article/_index.html.erb
app/views/article/_index_brief_default.html.erb
app/views/article/_index_default.html.erb
app/views/article/_research_starters.html.erb
app/views/article/_show_header_reference.html.erb
app/views/article/_show_reference.html.erb
app/views/article/record/_html_fulltext.erb
spec/helpers/article_helper_spec.rb
spec/models/article_search_builder_spec.rb
spec/presenters/presenter_research_starter_spec.rb

This PR fixes #1504 and fixes #1518. 
Notes:
- If the user is not authenticated, then the show page will not have any full text content. We may need to include some indication for the user to login to see the research starter full text.

add Research Starters to page 1 of results and as a show page

---

spec/models/concerns/eds_links_spec.rb

This gets rid of the following deprecation warnings:
```
DEPRECATION WARNING: Blacklight::Document#[]= is deprecated; use obj.to_h.[]= instead. (called from block (3 levels) in <top (required)> at /Users/drh/workspace/SearchWorks/spec/models/concerns/eds_links_spec.rb:76) (1 times); e.g.: 
```

in spec avoid deprecated document[]= method

---

app/models/concerns/eds_links.rb
spec/lib/access_panels/online_spec.rb
spec/models/concerns/eds_links_spec.rb
spec/views/article/access_panels/_online.html.erb_spec.rb

This PR closes #1532.  This PR refactors the EdsLinks code (again), which hopefully simplifies it. Due to the application logic changes for #1532, we've introduced `type` as a filter (so it's both `type` and `label` now that triggers the filters).

add support for "Open Access" fulltext links

---

app/models/concerns/eds_links.rb
app/views/article/_index_brief_default.html.erb
app/views/article/_index_default.html.erb
app/views/article/access_panels/_online.html.erb
lib/links.rb
spec/features/article_searching_spec.rb
spec/models/concerns/eds_links_spec.rb
spec/support/stub_article_service.rb
spec/views/article/access_panels/_online.html.erb_spec.rb

This PR fixes #1530 by adding a label/icon to fulltext links on the search and show pages. It modifies the SearchWorks `Link` class to support "ILL" links. Also, permits PDF eBook links to show the same as regular PDF links.

add label/icon to full text links

---

app/models/eds/repository.rb
config/settings.yml

This PR allows us to override the EDS cache location (which defaults to `/tmp`) via `Settings.EDS_CACHE_DIR`

allow configuration of the EDS cache directory

---

config/settings.yml

Closes #1450 
@drh-stanford do you think this is a reasonable number to increase the timeout to?

Increase EDS open timeout config from 2 to 5 seconds.

---

app/assets/stylesheets/modules/article.scss

This PR is connected to #1538. It makes any `<searchLink>` that we mark as HTML safe show in italics.

add italic style for EDS markup searchLink

---

app/controllers/article_controller.rb
app/helpers/article_helper.rb
spec/helpers/article_helper_spec.rb

This PR is connected to #1538. It tries to italicize the first phrase when there's no markup already given back by EDS. See the spec for various cases.

italicize the first phrase of composed title

---

app/assets/stylesheets/modules/search-bar.scss
app/helpers/application_helper.rb
app/views/catalog/_search_targets_widget.html.erb
spec/features/article_searching_spec.rb

Closes #1556 
This PR updates the search dropdown. The active search context is highlighted in yellow and the `<a>` tag is removed. Clicking on the active option (1) closes the dropdown menu (2) keeps the user on the same page.
```
<ul class="dropdown-menu" role="menu">
<li>
<a href="/?q=kittens&amp;search_field=search"><span class="h3">catalog</span> <span class="help-block">books &amp; media in the Stanford Libraries' collections</span></a>
</li>
<li class="active">
<span class="h3">articles</span> <span class="help-block">journal articles, e-books, and other licensed e-resources</span>
</li>
</ul>
```

Disable search dropdown link for current context

---

app/controllers/article_controller.rb
app/helpers/article_helper.rb
spec/helpers/article_helper_spec.rb

Closes #1551
This PR removes `<relatesTo>` tags in `eds_author_affiliations`. @jvine, I didn't see any markup to relate specific authors to their  affiliations. I'm not sure if that's a feature available in the API yet.

Remove XML from EDS author affiliations

---

Gemfile.lock

This PR upgrades to the latest EDS gem which has file caching fixes. Namely, it uses the guest mode as part of the cache key.

upgrade to the 0.3.1.pre EDS gem

---

app/controllers/article_controller.rb
spec/controllers/article_controller_spec.rb

This PR is connected to #1531. 
It stores the guest mode in the Blacklight session at the time the EDS session was created. 
The session cookie must have both the EDS session token and the guest mode stored, otherwise, it'll create a new EDS session and calculate the guest mode (based on IP address).
1. User visits site for first time from off-campus
1. An EDS session is created with guest mode ON
1. User visits site from on-campus later and executes a search
1. The EDS session is reused, but we send guest mode OFF to the EDS API  (which is incorrect as the EDS session is tied to the original guest mode in the EDS service and is ignored and will return guest mode ON results, thus causing confusion).
1. User visits site for first time from on-campus
1. An EDS session is created with guest …

store guest mode in Blacklight session

---

Gemfile
Gemfile.lock
app/controllers/article_controller.rb
app/controllers/catalog_controller.rb
app/controllers/concerns/email_validation.rb
app/mailers/search_works_record_mailer.rb
app/models/concerns/searchworks/document/email.rb
app/views/article/_email_form.html.erb
app/views/catalog/_email_form.html.erb
app/views/search_works_record_mailer/article_email_record.html.erb
app/views/search_works_record_mailer/article_full_email_record.html.erb
app/views/search_works_record_mailer/email_record.html.erb
app/views/search_works_record_mailer/email_record.text.erb
app/views/shared/_email_form.html.erb
app/views/shared/record/_record_toolbar_tools_subset.html.erb
config/environments/development.rb
config/routes.rb
spec/controllers/article_controller_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/features/blacklight_customizations/emailing_records_spec.rb
spec/mailers/search_works_record_mailer_spec.rb

Fixes part of #1448 
Related: #1552, #1553 
- some cleanup to apply to current SW catalog as well as articles
- output is formatted HTML and similar to the results view:

Add article email content for brief records

---

config/routes.rb
spec/routing/article_routes_spec.rb

This PR fixes #1577, although we don't have a spec on allowable characters in the EDS' accession identifiers.
An example: http://localhost:3000/article/awn__sajae-138570-%3b-1165365

include any punctuation character as EDS accession id

---

app/assets/stylesheets/modules/record-toolbar.scss
app/assets/stylesheets/modules/search-bar.scss
app/assets/stylesheets/modules/sul-toolbar.scss
app/views/articles/record/_record_toolbar.html.erb
app/views/articles/show.html.erb
app/views/catalog/record/_record_toolbar.html.erb
app/views/catalog/show.html.erb
app/views/shared/record/_record_toolbar.html.erb
spec/features/article_record_toolbar_spec.rb
spec/features/blacklight_customizations/record_toolbar_spec.rb

Closes #1494
This PR
- fixes responsive behavior for the show page record toolbar
- moves record toolbar to a shared partial
- fixes search target dropdown alignment

Fix responsive behavior for show page record toolbar

---

app/helpers/application_helper.rb
spec/features/article_searching_spec.rb

Finishes work on #1556 
This PR :
- updates the `link_to_catalog_search` and `link_to_article_search` helpers. 
- disables clicking on the current search context / uses appropriate styling in the search dropdown

Disable selecting current context from search dropdown in show view

---

app/assets/stylesheets/modules/course_reserve_browse.scss

Update course reserves toolbar styling

---

app/views/articles/access_panels/_online.html.erb
app/views/articles/access_panels/_sfx.html.erb
spec/views/article/access_panels/_online.html.erb_spec.rb

Closes #1575 
This PR changes the titles of the following access panels (articles only):
- Online: "Available online" -> "Best source"
- SFX: "All full-text sources" -> "All available sources"

update online and SFX panel wording

---

app/views/articles/_index_default.html.erb
spec/features/article_searching_spec.rb

Closes #1548 
@jvine does this look okay?

Truncate eds author data in search results.

---

Gemfile.lock
app/models/concerns/eds_document.rb
app/views/articles/_index_default.html.erb
app/views/articles/_show_default.html.erb
spec/features/article_display_spec.rb
spec/features/article_searching_spec.rb
spec/models/concerns/eds_document.rb
spec/support/stub_article_service.rb

Closes #1570 
This PR
- upgrades to the latest version of the `ebsco-eds` gem. This makes `:eds_ebook_pdf_fulltext_available`, `:eds_ebook_epub_fulltext_available`, `:eds_pdf_fulltext_available`, `:eds_html_fulltext_available` available.
- adds a 'Full text' label, and a link to the article record with the text `View on detail page`
[Example search](https://sw-webapp-sandbox-f.stanford.edu/articles?utf8=%E2%9C%93&f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&search_field=search&q=Guzman%2C+Andrew+T.%3A+Overheated%3A+The+Human+Cost+of+Climate+Change)

Add HTML full text link to article results

---

app/controllers/articles_controller.rb
app/models/concerns/eds_links.rb
app/views/articles/_index_brief_default.html.erb
app/views/articles/_index_default.html.erb
app/views/articles/access_panels/_online.html.erb
config/locales/searchworks.en.yml
config/routes.rb
lib/links.rb
spec/controllers/article_controller_spec.rb
spec/routing/article_routes_spec.rb
spec/views/article/access_panels/_online.html.erb_spec.rb

This PR fixes #1557 and fixes #1580. It affects the PDF links on the *search* results only (the show pages were already working). To implement these links, we need to add a new controller method that does a EDS Retrieve to get the link (it's not available from the EDS Search data). The link shown on the search results page looks like `/article/12345/pdf/fulltext` or `/article/12345/ebook-pdf/fulltext`, etc. Those links will do a Retrieve and then redirect the user to the actual PDF link.
Also, I disabled turbolinks as it seems to be causing problems negotiating the content type for the PDFs (i.e., you'd get raw PDF back in the window).
On failure, it'll display a flash error message and log the exception to Honeybadger.

add support for redirect-based PDF links

---

app/assets/javascripts/article.js
app/views/articles/record/_html_fulltext.erb
spec/features/article_display_spec.rb

Change article fulltext html to be open by default and add a chevron.

---

app/controllers/articles_controller.rb
app/helpers/article_helper.rb
spec/helpers/article_helper_spec.rb

Remove markup from Series & Document Type

---

app/assets/stylesheets/modules/facets.scss

`Source Type` facet counts are disabled until further work with the EDS API.

Disable article Source Type facet counts

---

app/assets/stylesheets/modules/facets.scss

This PR fixes #1650 by putting the facet counts back for the Source Type facet:

restore facet counts for Source Type facet

---

config/locales/blacklight.en.yml
config/locales/searchworks.en.yml
spec/features/article_home_page_spec.rb
spec/features/article_searching_spec.rb

Closes #1643
This PR changes "articles" to "articles+" in response to user feedback. Changes are made in the following areas:

Update articles to articles+ in nav and titles

---

app/assets/javascripts/search_navbar_services_menu.js
app/assets/stylesheets/modules/subnavbar.scss
app/views/shared/_search_navbar_services_menu.html.erb
app/views/shared/_search_navbar_top_menu.html.erb
app/views/shared/_search_subnavbar.html.erb
app/views/shared/_top_navbar.html.erb

Fixes #1444 
This PR:
- updates the link content of the Library Services menu
- increases the width of the menu to 300px and adjusts submenu padding
- renames `search_navbar_top_menu` to `search_navbar_services_menu` in several files to reflect its place in the redesign

Update library services menu

---

app/assets/stylesheets/modules/constraints.scss
app/assets/stylesheets/modules/results-documents.scss
app/views/articles/_constraints.html.erb
app/views/articles/_index.html.erb
app/views/catalog/_constraints.html.erb
app/views/catalog/_facets.html.erb
app/views/catalog/_index.html.erb
config/locales/blacklight.en.yml
config/locales/searchworks.en.yml
spec/features/access_points/databases_spec.rb
spec/features/article_searching_spec.rb
spec/features/blacklight_customizations/facets_spec.rb
spec/features/blacklight_customizations/results_toolbar_spec.rb
spec/features/blacklight_customizations/search_toolbar_spec.rb
spec/features/blacklight_customizations/zero_results_spec.rb
spec/features/bookplates_spec.rb
spec/features/collections_search_spec.rb
spec/features/search_num_of_results_spec.rb

Closes #1600 
This PR makes several UI changes to make the current search context clearer to users.
1. 'Start over' button reflects search context
2. Change 'Limit your results' to 'Refine your results`
3. Left-align number of results; add search context to text
4. Move RSS icon to the other side of number of results; fix vertical alignment

Add more search context wording to results page

---

Gemfile.lock
app/models/eds/repository.rb
config/settings.yml

This PR fixes #1426.
To use, you need to add the correct `EDS_HOSTS` setting to your configuration. See https://github.com/sul-dlss/shared_configs/pull/354. I've added it to `production.local.yml` on the article preview box.

upgrade to eds 0.3.7.pre for pagination workaround

---

app/controllers/articles_controller.rb
app/views/articles/_facet_eds_publication_type.html.erb
app/views/catalog/_facet_limit.html.erb
config/locales/searchworks.en.yml
spec/features/source_type_facet_spec.rb
spec/support/stub_article_service.rb

Closes #1638 
This PR adds a warning to the `Source type ` facet in article search. After one source type is selected, the user is informed that additional selections will expand (rather than narrow) search results.

Add warning for article source type facet behavior

---

config/settings.yml

This PR makes the ebscohost.com configuration public for https://github.com/sul-dlss/SearchWorks/pull/1666
This PR is connected to #1603

add ebscohost.com configuration to default settings.yml

---

app/views/catalog/_home_page.html.erb
app/views/shared/_home_page_bento.html.erb

This PR changes the `image_tag` on the home pages to be explicit about the image format for the asset pipeline to hopefully fix a problem where rails isn't finding the asset in RAILS_ENV=production

add image suffixes to home page assets

---

app/views/shared/_home_page_bento.html.erb

This PR is connected to #1676 and adds a missing `Articles+` link.

add missing Articles+ link on home page

---

app/views/articles/_home_page.html.erb

remove panel-heading for right-hand panels on articles+ homepage

---

Gemfile.lock
app/models/eds/repository.rb
config/routes.rb
spec/controllers/concerns/eds_paging_spec.rb
spec/support/stub_article_service.rb

This PR fixes #1603. We've changed the EDS gem such that it passes the accession id verbatim rather than doing `s/_/./` substitutions on it (which mangle the id in some cases, hence the errors in #1603). 
Since the id's constraints have changed, I discovered that our tracking URL was pointing to `/catalog/xxx/track` rather than `/articles/xxx/track` so I've fixed the named route.
I've also added a `.zzz` to one of the identifiers in the EDS spec stubs so we have punctuation in at least one of the stub hits -- the EDS document ids can have all sorts of punctuation in them -- see https://github.com/sul-dlss/SearchWorks/blob/1603-delimiters/spec/routing/article_routes_spec.rb#L13

remove s/_/./ on the accession identifiers and permit any non-/ character as part of the id

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/articles_controller.rb
app/models/concerns/eds_document.rb
app/models/eds/repository.rb
app/models/eds/session.rb
app/models/solr_document.rb
app/presenters/sms_presenter.rb
app/services/eds/search_service.rb
app/views/record_mailer/sms_record.text.erb
app/views/search_works_record_mailer/article_email_record.html.erb
app/views/shared/record/_record_toolbar_tools_subset.html.erb
config/initializers/bitly.rb
config/settings.yml
spec/lib/sms_spec.rb
spec/models/eds/repository_spec.rb
spec/models/solr_document_spec.rb
spec/presenters/sms_presenter_spec.rb
spec/services/eds/search_service_spec.rb

Originally outlined in: #1641 , closes #1641 
Previously an article sms was blank. Now:
```
Forasmuch as there have been many disputes and controversies for a long time, concerning the titles to a great part of the lands in ...
http://bit.ly/2wpCGmG 
```
And for Stanford urls (deployed apps) it will get the stanford custom domain.
One a new 6.x version of Blacklight is released with https://github.com/projectblacklight/blacklight/pull/1771/commits/bb6ba0f2ca42dbf08bc8817b424092b7cb7f3678 we can remove our implementation of `to_semantic_values`

Adds  implementation of an article sms and bitly + shortning!

---

app/assets/stylesheets/modules/sfx-panel.scss
app/assets/stylesheets/searchworks.scss
app/models/sfx_data.rb
app/views/articles/access_panels/_sfx.html.erb
spec/features/article_display_spec.rb
spec/models/sfx_data_spec.rb

Closes #1614 
* Only selects SFX items where the `is_related` is `no`.
* Generates a link to the full sfx menu for the item.

Updates to SFX panel 

---

app/models/concerns/eds_links.rb
spec/features/article_display_spec.rb
spec/lib/access_panels/sfx_spec.rb
spec/models/concerns/eds_links_spec.rb

This PR fixes #1696. The problem was that non-fulltext links (e.g., `cataloglink`) were sneaking in for some cases (i.e., it thought they were open access links). It was fixed by filtering out bad links using `.present?`
Test case is `mzh__2017307227`

ensure that all links meet type requirements so non-fulltext links are excluded

---

app/controllers/articles_controller.rb

This PR fixes #1661 by adding publication status to the Details section of the record view.

add Publication Status to record view

---

app/controllers/articles_controller.rb
app/controllers/catalog_controller.rb
spec/features/article_home_page_spec.rb

This PR fixes #1711 
Note that it also affects the switching between catalog/articles+ for fielded search.

in field search, remove Abstract, Series, ISSN, and ISBN, and relabel Article and Journal titles

---

app/assets/stylesheets/modules/alert.scss
app/views/articles/_home_page.html.erb

Add a temporary flash alert on the article home page.

---

app/assets/stylesheets/modules/home-page.scss
app/views/articles/_home_page.html.erb
app/views/shared/_home_page_bento.html.erb

Addresses #1676 until further updates
This PR:
- adds a URL to "More about article access at Stanford libraries"
- changes URL for library website
- suppresses "All of the above" link to bento search for now

Update home page link URLs and suppress bento link

---

app/views/articles/_home_page.html.erb

Closes #1726 
This PR:
- updates the "Welcome to articles+ beta!" flash message text
- adds a link to toggle the feedback form

Add feedback link to articles+ beta flash message

---

app/controllers/articles_controller.rb
app/controllers/catalog_controller.rb
app/controllers/concerns/backend_lookup.rb
app/views/shared/_zero_results.html.erb
config/routes.rb
spec/features/zero_results_spec.rb
spec/routing/article_routes_spec.rb
spec/support/stub_article_service.rb
spec/views/shared/_zero_results.html.erb_spec.rb

Closes #1705 
Example search from ticket:
- [localhost](http://localhost:3000/articles?utf8=%E2%9C%93&f%5Beds_language_facet%5D%5B%5D=%ED%95%9C%EA%B5%AD%EC%96%B4&f%5Beds_publication_type_facet%5D%5B%5D=Videos&f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text&search_field=title&q=kittens)
- [preview](http://sw-webapp-sandbox-f.stanford.edu/articles?utf8=%E2%9C%93&f%5Beds_language_facet%5D%5B%5D=%ED%95%9C%EA%B5%AD%EC%96%B4&f%5Beds_publication_type_facet%5D%5B%5D=Videos&f%5Beds_search_limiters_facet%5D%5B%5D=Direct+access+to+full+text&search_field=title&q=kittens)

Update zero results page to be article/catalog controller agnostic.

---

app/models/eds/repository.rb
app/models/solr_document.rb
spec/controllers/concerns/eds_paging_spec.rb
spec/models/solr_document_spec.rb
spec/support/stub_article_service.rb

Fixes #1716 
I'm working on updating Blacklight, but I don't want this to hold up a release and I think that we're functionally equivalent at the moment.

Override SolrDocument#id to escape slashes in IDs.

---

app/assets/stylesheets/modules/home-page.scss
app/views/articles/_home_page.html.erb
app/views/catalog/_home_page.html.erb
app/views/shared/_home_page_bento.html.erb

Closes #1729 
This PR changes `<h4>` to `<h3>` tags on both the Catalog and Articles+ home pages.

Use h3 for homepage sub-headings

---

app/views/shared/feedback_forms/_form_fields.html.erb

This PR fixes #1757 
HTML5 validation for all fields that looks like so:

make all user input fields required for report connection problem form

---

config/deploy.rb
config/settings.yml

@jkeck This PR uses Rails.root/tmp/faraday_eds_cache for the EDS cache folder.

move faraday_eds_cache to Rails.root/tmp

---

app/assets/javascripts/backend_lookup.js

I saw this during the demo yesterday.

add locale integer parsing for result count | parity with mini-bento

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

Tested this w/ @snydman and he has many affiliations (that are returned semicolon delimited).

Handle users with multiple (semicolon delimited) affiliations.

---

app/controllers/articles_controller.rb
config/locales/searchworks.en.yml
spec/controllers/article_controller_spec.rb

If we either put a login link w/o a referrer OR a login link w/ the referrer (which in the context of the flash message is the fulltext method) we get an error message from Shibboleth saying the session is stale.
@jvine said a good stop-gap would be to just not link the text given that the login link is available on every page.

Remove login link from EDS Guest flash error message.

---

app/helpers/article_helper.rb
app/views/articles/access_panels/_online.html.erb
app/views/articles/index.json.jbuilder
spec/features/article_searching_spec.rb

This PR fixes #1753. The simple rendering of the link, which the JSON API surfaces, is migrated to a helper method, but there's more complex renderings in the index pages that I didn't migrate.
like so http://localhost:3000/articles?q=climate+change&format=json
^^^The link is relative so the Bento app will need to inject the host.
^^^Other links are fully qualified

add preformatted HTML for fulltext link to JSON API

---

lib/tasks/searchworks.rake

`prune_eds_cache` (existing task) cleans the cache by expiring all old files, whereas `clear_eds_cache` deletes all files regardless of their TTLs. The `prune_eds_cache` task is already run hourly via [config/schedule.rb](https://github.com/sul-dlss/SearchWorks/blob/master/config/schedule.rb#L8)
```
$ bundle exec rake -T | grep searchworks | grep cache
rake searchworks:clear_eds_cache                     # Clear all files in EDS cache
rake searchworks:prune_eds_cache                     # Prune expired files in EDS cache
$ bundle exec rake searchworks:prune_eds_cache
Cleaning cache in /Users/drh/workspace/SearchWorks/tmp/faraday_eds_cache
$ bundle exec rake searchworks:clear_eds_cache
Clearing cache in /Users/drh/workspace/SearchWorks/tmp/faraday_eds_cache
```

add searchworks:clear_eds_cache task

---

app/views/shared/_home_page_bento.html.erb

Closes #1772 
Removes "Covers ~87% of our subscribed databases" from the Articles+ section of the mini-bento.

Remove coverage number from Articles+ mini-bento

---

app/controllers/sfx_data_controller.rb
app/models/sfx_data.rb
app/views/articles/access_panels/_sfx.html.erb
spec/controllers/sfx_data_controller_spec.rb

We now just URI encode the URL in the data attribute and keep it encoded through the entire stack.
Closes #1647 
(note that this PR won't work until #1778 is merged as the entire feature is broken right now due to redirects)

Change/simplify encoding strategy for SFX links in the SFX panel.

---

app/views/catalog/_home_page.html.erb

Closes #1773 
Changes "Databases" link in catalog homepage "Featured Resources" from `/selected-databases` to `/databases`.

Update databases link in featured resources

---

app/models/concerns/eds_links.rb
spec/features/article_searching_spec.rb
spec/mailers/search_works_record_mailer_spec.rb
spec/models/concerns/eds_links_spec.rb
spec/views/article/access_panels/_online.html.erb_spec.rb

Closes #1784 
This PR changes "Find it in print or via interlibrary services" to "Find full text or request".

Change request options link text

---

app/helpers/article_helper.rb
app/presenters/article_fulltext_link_presenter.rb
app/views/articles/_index_default.html.erb
app/views/articles/access_panels/_online.html.erb
app/views/articles/index.json.jbuilder
spec/features/article_searching_spec.rb
spec/presenters/article_fulltext_link_presenter_spec.rb

This PR refactors `render_fulltext_link` into a presenter as well as changes the functionality to handle the links that are presented on the search result instead of what's on the record view.
This change is necessary for the bento app (and referenced in sul-dlss/sul-bento-app#57).

Refactor render_fulltext_link into a presenter

---

app/presenters/article_fulltext_link_presenter.rb

Closes #1796 and fixes sul-dlss/sul-bento-app#68 once deployed to production.
This PR uses absolute URLs for the article brief view PDF icon. 
`<img height="20px" alt="PDF" src="/assets/pdf-icon-32b0b2f9280075f9a41fbf98446d3ed2a53cad1271f3bfec84029861f8e78b94.svg">`
`<img height="20px" alt="PDF" src="http://localhost:3000/assets/pdf-icon-32b0b2f9280075f9a41fbf98446d3ed2a53cad1271f3bfec84029861f8e78b94.svg">`

Use absolute URLs for article icons

---

app/views/articles/_show_default.html.erb
spec/features/article_display_spec.rb

Don't display article metadata for restricted articles.

---

app/views/record_mailer/sms_record.text.erb
spec/mailers/record_mailer_spec.rb

Update how document links are generated in SMS records.

---

lib/constants.rb

Closes #1633 
This PR changes the translation for the `RET-REF` location from "Reference" to "Retired Reference".

Update translation for location code RET-REF

---

app/assets/stylesheets/modules/home-page.scss
app/helpers/application_helper.rb
app/views/catalog/_search_targets_widget.html.erb
app/views/shared/_home_page_bento.html.erb
app/views/shared/_search_context_sidebar.html.erb
spec/features/article_searching_spec.rb
spec/features/home_page_spec.rb
spec/helpers/application_helper_spec.rb
spec/views/shared/_home_page_bento.html.erb_spec.rb

Closes #1695 
This PR:
- directs 'All' links to https://library.stanford.edu/all" and passes simple search queries
- adds 'All' to the search dropdown
- adds 'All of the above' search to home page mini bento

Enable bento links

---

app/controllers/articles_controller.rb
spec/controllers/article_controller_spec.rb

An error can be expected to be thrown in the case of a guest user (due to data that EDS returns).
Fixes #1765

Only notify HB of full text link errors when the user is not a guest.

---

app/views/shared/_home_page_bento.html.erb

A little typo fix requested by @snydman and @jkeck.
>Search a combined index of 100s of databases, and connect directly to the article or resource.
>Search a combined index of 100s of databases and connect directly to the article or resource.

Remove comma from homepage bento Articles section

---

app/views/catalog/_accordion_section_summary.html.erb
spec/views/catalog/_accordion_section_summary.html.erb_spec.rb

This was being caused by data in the summary.

Sanitize summaries in search results.

---

Gemfile.lock
app/assets/javascripts/jquery.preview-gallery.js

Fixes an issue where when navigating off a show page and then pressing
back instantiates the previewGallery, causing an infinite loop which
will crash the browser.

Trap and return early when itemsRow is NaN or 0

---

Gemfile
Gemfile.lock

Already deployed to prod in a hotfix, fixes a regression introduced in updating the eds gem.

pin to 0.3.19.pre as /articles in production is failing

---

app/assets/stylesheets/modules/mastheads.scss
app/models/search_builder.rb
app/views/catalog/_database_prefix.html.erb
app/views/catalog/mastheads/_databases.html.erb
app/views/catalog/mastheads/_selected_databases.html.erb
spec/features/access_points/databases_spec.rb
spec/features/access_points/selected_databases_spec.rb
spec/models/search_builder_spec.rb

Closes #1658
This PR:
- Partially reverts #1953 and restores the A - Z filter for Databases (see discussion with @jvine in #1658)
- Updates text and styling for the [Databases](https://searchworks.stanford.edu/databases) and [Selected Databases](https://searchworks.stanford.edu/selected_databases) mastheads

Restore A-Z filter for Databases masthead + update styling

---

app/views/catalog/_database_prefix.html.erb
spec/features/access_points/databases_spec.rb

Fixes #1978 🤞
After #1953 was merged, the default sort for the `/databases` page is relevance.
This PR explicitly adds a `&sort=title` param to the `/databases` A-Z filter links.
[Stage](https://searchworks-stage.stanford.edu/catalog?utf8=%E2%9C%93&f%5Bformat_main_ssim%5D%5B%5D=Database&prefix=c&search_field=search&q=government) (Relevance sort by default) - `/?f%5Bformat_main_ssim%5D%5B%5D=Database&prefix=c`
Local dev - `/?f%5Bformat_main_ssim%5D%5B%5D=Database&prefix=c&sort=title`

Title sort Database A-Z filter results

---

app/views/shared/_email_form.html.erb

Remove word "links" from the email form

---

app/views/layouts/searchworks.html.erb

I'm seeing some failing tests locally w/o this.

Only use WebFont loader if it is available.

---

app/assets/stylesheets/modules/librarian-view.scss
app/assets/stylesheets/searchworks.scss
lib/holdings/mhld.rb
spec/lib/holdings/mhld_spec.rb

Fixes #2021 in a two-prong approach.
Uses preferred approach for access panel styling:
Uses preferred approach for librarian view as I suspect we do not want to sanitize this data:

add styling and sanitzing for mhld display styles

---

CHANGELOG.md
app/assets/stylesheets/modules/feedback-form.scss
app/assets/stylesheets/modules/image-icons.scss
app/views/shared/feedback_forms/_chat_with_librarian.html.erb
app/views/shared/feedback_forms/_form.html.erb

Fixes #2032 
This PR adds adds a link to the Searchworks status dashboard to the feedback form. Minor styling and wording changes are included as well.

Add system status link to feedback form

---

Gemfile
Gemfile.lock

Closes #1950 🤞
See: https://github.com/ebsco/edsapi-ruby/commit/813110c43e20320aab1e53ce8769ba8a1b74d089
We'll want to deploy to stage first and test this out. We'll be discussing release management and GitHub workflow at our next meeting with EBSCO.

Upgrade to EDS v1.0.1

---

app/views/shared/_search_navbar_services_menu.html.erb
app/views/shared/_su_footer.html.erb
app/views/shared/feedback_forms/_form.html.erb

The text will likely also need an update at somepoint, but this at least helps us not point to something that isn't there.

update link urls to point new status page url

---

app/views/catalog/_accordion_section_online.html.erb
spec/views/catalog/_accordion_section_online.html.erb_spec.rb

Fixes #1945 
A good fixture search: http://127.0.0.1:3000/catalog?utf8=%E2%9C%93&search_field=search&q=9238380
The logic I'm using here based off of the linked tickets are whether or not the item has managed purls. Happy to add additional changes to that based off of any cases I may be missing.

do not show Google Books section if managed purls are present

---

CHANGELOG.md

~Potentially controversial, as I'm no longer listing full links just referencing the numbers as I think GitHub will auto-magically link them for me.~
Nope I guess they only do this in release notes 😢

updates changelog for recent unreported changes

---

CHANGELOG.md
app/models/performance_alerts.rb
config/initializers/okcomputer.rb
config/settings.yml
spec/models/performance_alerts_spec.rb

Part of sul-dlss/searchworks-status#5
If this seems reasonable, I'll submit a shared configs pr w/ the proper API key configured.
We can then add the relevant checks to the `searchworks-status` codebase to trigger the issue state for the appropriate services.

Add optional OKComputer checks for New Relic performance alerts

---

app/assets/stylesheets/modules/record-toolbar.scss
app/views/shared/record/_record_toolbar_tools_subset.html.erb
spec/features/blacklight_customizations/record_toolbar_spec.rb

This resolves an issue where RefWorks import failed on non-latin like
languages (e.g Russian, Sanskrit). Fixes #1944
- 12786465 Sanskrit
- 12422691 Russian
One thing I have found is that some records will get imported into RefWorks, but the citation is kind of crappy. I think this is a different issue that could be addressed elsewhere.

move refworks on showpage to use post form instead of callback url

---

app/models/concerns/eds_export.rb
app/models/solr_document.rb
app/views/shared/record/_record_toolbar_tools_subset.html.erb
config/locales/blacklight.en.yml
config/routes.rb
spec/features/article_record_toolbar_spec.rb
spec/models/concerns/eds_export_spec.rb

Fixes #2058 
TODO:
If you have a zotero plugin (and assuming Endnote /shrug) it will pickup the export and import it in automagically for you :magic:

add support for importing an Article record into RefWorks

---

app/assets/stylesheets/modules/selected-databases.scss

Remove extra padding for selected database links

---

CHANGELOG.md
Gemfile
Gemfile.lock

This is related to #1704.  Not sure if it closes it or not, but it stops these records from throwing errors (and appears to no longer display the raw HTML as described in the ticket).

Update ebsco-eds to 1.0.5

---

app/models/concerns/iiif_concern.rb
spec/views/catalog/_show_mods.html.erb_spec.rb

This fixes an issue where the IIIF manifest url could be encoded as
an array.

ensure that one url is sent in the encoded url (not an array)

---

app/assets/stylesheets/modules/record-metadata-section.scss
app/views/articles/_show_default.html.erb
app/views/catalog/access_panels/_location.html.erb
app/views/catalog/record/_marc_metadata_sections.html.erb
app/views/catalog/record/_metadata_panels.html.erb
app/views/catalog/record/_mods_metadata_sections.html.erb
app/views/catalog/record/_record_metadata_default.html.erb
spec/features/bookplates_spec.rb
spec/features/file_collection_spec.rb
spec/features/image_collection_spec.rb
spec/features/merged_file_collection_spec.rb
spec/features/merged_image_collections_spec.rb
spec/features/merged_image_spec.rb
spec/mailers/search_works_record_mailer_spec.rb
spec/views/catalog/record/_marc_metadata_sections.html.erb_spec.rb
spec/views/catalog/record/_mods_metadata_sections.html.erb_spec.rb

Restyle record metadata and panel headers 

---

CHANGELOG.md
app/assets/stylesheets/modules/availability-icons.scss
app/views/catalog/access_panels/_location.html.erb
lib/constants.rb
lib/holdings.rb
lib/holdings/in_process.rb
lib/holdings/library.rb
lib/holdings/status.rb
spec/lib/holdings/in_process_spec.rb
spec/lib/holdings/library_spec.rb
spec/views/catalog/access_panels/_location.html.erb_spec.rb

Fixes #2059 
This PR adds custom support for request links of Hoover Archives content in SearchWorks.

Adds support for updated Hoover Archive requests

---

CHANGELOG.md
app/assets/javascripts/analytics.js

Fixes #2114 
The URL will be reported which i think is sufficient to accomplish: 
> the kind of page the link was clicked from (home page, results, record view, Selected databases, no results)

tracks external link clicks using Google Analytics

---

app/assets/stylesheets/modules/online-resource-links.scss

Fixes #2111 
Added in https://github.com/sul-dlss/SearchWorks/commit/e6dbd6f90da1c2d9972c9733a9c73b200fc92abe
I don't think the explicit width is necessary here.

remove explicit width to accomodate different text for class

---

app/views/catalog/_index_header_gallery.html.erb

Fixes #2121 
http://127.0.0.1:3000/browse?barcode=36105015805067&start=1071767&view=gallery

move gallery "online" label

---

app/assets/javascripts/analytics.js

This PR updates our approach to using the now recommended analytics.js approach. See https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs
Partially adapted from our existing approach and http://reed.github.io/turbolinks-compatibility/google_analytics.html
We need to do this for the following reasons:
- ga.js has been deprecated for years
- analytics.js allows us to use beacon as the transport mechanism for events, thus not having to hijack link clicks anymore
Risks: our data reporting may change slightly. But this is definitely worth it.

updates Google Analytics to use analytics.js fixes #2096

---

app/assets/javascripts/alternate_catalog.js
app/assets/javascripts/analytics.js
app/views/shared/_zero_results.html.erb

Fixes #2115 
This PR handles the following cases:
- Adds an additional event category for when an external link is clicked from a zero results page
- Adds an event for when both the "remove limits" and "search all fields" links are clicked
- When "alternate results" content is added to page, track when those links are clicked - both on zero-results page and in normal search results.
- Track when a zero results page gets loaded

adds zero results action tracking

---

lib/holdings/callnumber.rb

document was added as an accessor in 02f4d26d34c227e065a23c77b278fe48b901f02e.
However, when we render availability as json this puts a SolrDocument in every item in the holdings.
For records with a lot of items this blows that json response's size up to a huge amount.

Remove document accessor from json response.

---

app/helpers/record_helper.rb
app/models/concerns/mods_data.rb
app/views/catalog/_mods_search_results_document_fields.html.erb
app/views/catalog/_summary_data.html.erb
config/solr_configs/solrconfig.xml
spec/fixtures/solr_documents/31.yml
spec/fixtures/solr_documents/47.yml
spec/views/catalog/_index_mods.html.erb_spec.rb
spec/views/catalog/_index_mods_collection.html.erb_spec.rb
spec/views/preview/_show_mods.html.erb_spec.rb

In conjunction with https://github.com/sul-dlss/searchworks_traject_indexer/pull/224 this fixes #1987 
~~This approach could be controversial, so I'll outline my rationale:~~
~~To keep current functionality we would need to create/invent a custom data structure that should be understood by both the indexer and SearchWorks. This seemed potentially brittle given that the mods logic could change and without knowing if we have changing future requirements. Though this approach assumes that the content is indexed and displayed with the same version of the ModsDisplay gem.~~
~~If the ModsDisplay gem is updated in SearchWorks, the change will also need to happen in the indexer. Need to discuss w/ @jvine about the ModsDisplay updates and how the name may change.~~
This PR is updated now to be …

move away from mods parsing in search results

---

app/views/catalog/access_panels/_online.html.erb
spec/features/access_panels/online_books_spec.rb
spec/features/access_panels/online_spec.rb
spec/integration/external-data/access_panels_spec.rb
spec/views/catalog/access_panels/_online.html.erb_spec.rb

Change online panel heading text

---

app/views/catalog/mastheads/_digital_collections.html.erb
app/views/catalog/mastheads/_sdr.html.erb
spec/features/access_points/digital_collections_spec.rb

Closes #2033
This PR updates the links and text for the Digital Collections and SDR mastheads.

Update mastheads: Digital collections, SDR

---

lib/holdings/location.rb
spec/lib/holdings/location_spec.rb

Fixes #2100 
Confirmed correct behavior in https://github.com/sul-dlss/SearchWorks/issues/2100#issuecomment-439478320
4082969

Fixes #2100 enable "SEE-OTHER" locations to display in results view

---

app/views/bookplates/_bookplate.html.erb

Closes #2086 
(Did not include a CHANGELOG update because this is not user facing...yet)

Wrap bookplate fund name link in a <p>

---

CHANGELOG.md
app/views/catalog/access_panels/_online.html.erb

Remove GoogleBook link for items that have SFX data in the Online panel.

---

app/assets/stylesheets/modules/panel-in-collection.scss
app/models/concerns/extent.rb
app/views/catalog/access_panels/_appears_in.html.erb
app/views/catalog/access_panels/_in_collection.html.erb
app/views/catalog/record/_metadata_panels.html.erb
spec/features/access_panels/in_collection_spec.rb
spec/models/concerns/extent_spec.rb
spec/views/catalog/access_panels/_appears_in.html.erb_spec.rb
spec/views/catalog/access_panels/_in_collection.html.erb_spec.rb

SDR display - Record view - Update Context Panels

---

app/assets/stylesheets/modules/article.scss
app/assets/stylesheets/modules/facets.scss
app/assets/stylesheets/modules/gallery-view.scss
app/assets/stylesheets/modules/item-preview.scss
app/assets/stylesheets/modules/mastheads.scss
app/assets/stylesheets/modules/record-view.scss
app/assets/stylesheets/modules/subnavbar.scss
app/assets/stylesheets/modules/thumbnail.scss
app/views/articles/record/_html_fulltext.erb
app/views/catalog/_accordion_section_course_reserves.html.erb
app/views/catalog/mastheads/_collection.html.erb
app/views/catalog/mastheads/_databases.html.erb
app/views/catalog/mastheads/_digital_collections.html.erb
app/views/catalog/mastheads/_sdr.html.erb
app/views/catalog/mastheads/_selected_databases.html.erb
app/views/preview/_show_header_default.html.erb

Paired w/ @jvine on this.  Lot's of small little things, several things that didn't get covered in previous changes.
Only "new" work is moving the collection masthead to be us `flex` to help in the case where this is no summary.

Several CSS tweaks to wrap up some of the recent changes

---

app/views/catalog/access_panels/_online.html.erb
spec/features/access_panels/online_books_spec.rb
spec/features/access_panels/online_spec.rb
spec/integration/external-data/access_panels_spec.rb
spec/views/catalog/access_panels/_online.html.erb_spec.rb

Part of #2024 
This PR allows the "Online" panel to have different sub-headings for SDR objects.
Example:
More test items:
http://searchworks.stanford.edu/view/12317454
http://searchworks.stanford.edu/view/12796410

Separate SDR item online panel

---

app/views/catalog/mastheads/_collection.html.erb
spec/features/access_points/collection_spec.rb

Part of #2126 / #2024 / fixes https://github.com/sul-dlss/SearchWorks/pull/2126#discussion_r234844438 
This PR updates the Collection masthead so that it matches the new SDR item record view. 
(See similar changes in #2178)

Update collection masthead to match record view

---

CHANGELOG.md
app/assets/stylesheets/modules/brief-view.scss

Fix online label in brief view.

---

app/helpers/request_link_helper.rb
spec/helpers/request_link_helper_spec.rb

The SSRC form is managed separately from our requests form and therefor should not be
rendered in our modal (since it cannot appropriately report success amongst other things)

Don't put the request-modal popup data attributes on SSRC request links.

---

Gemfile.lock

[CVE-2019-15587](https://nvd.nist.gov/vuln/detail/CVE-2019-15587)

Update dependencies to address loofah vulnerability.

---

config/schedule.rb
lib/tasks/searchworks.rake

This should hopefully help with the disk filling up issue that's happening on the bot nodes.
This could just be a temporary fix until we have a more robust Rack::Attack caching solution (e.g. Redis) or we could see if this will work "Well Enough" for our user facing nodes as well w/o having to setup the additional infrastructure.  Given that we're only using this for throttling (and not fail2Ban etc) this short lived 1 day cache should work okay for us for now.

Clear Rack::Attack cache on cron

---

app/views/layouts/searchworks.html.erb

These are errors that are seemingly coming from plugins or by our dependencies in ways that we can't really do anything about (e.g. reCaptcha)

Add some JS errors to the Honeybadger ignore patterns.

---

Gemfile
Gemfile.lock

ambethia/recaptcha#356 aims to address this issue, and will hopefully be released as 5.5.0
This is causing reCaptcha restricted emails to not be sent (even w/ a valid recaptcha challenge)

Don't use recaptcha 5.4.0

---

config/locales/searchworks.en.yml

Add a notice to global alert about a current SFX outage.

---

lib/holdings/library.rb
spec/lib/holdings/library_spec.rb

Fixes #2436
@saseestone : I assume/hope we also want to remove similar panels with this data (like under Check Availability on search results, in the call number bar for the gallery view, etc)?

Remove eReserves from 'At the Library' panels

---

app/models/concerns/mods_data.rb
spec/models/concerns/mods_data_spec.rb

Closes #2435
Ultimately this should be addressed at the index level but will require both a fix and a re-index of all MODS content before we'll see a change in production (but we can get a quick fix for this in the app in the meantime).
`summary_display` a copyField whose source is `summary_search`.  `summary_search` does not have this duplicate content so not sure why it is ending up in the copy field destination.  If anybody can point me towards a quick fix for that I would be happy to submit it, otherwise I'll open a ticket in the indexer to look into this root cause more.

De-dup mods abstracts coming from summary_display.

---

app/views/catalog/record/_marc_contents_summary.html.erb

This is consistent with the data in the results view.
Closes #2433

Pass MARC TOC elements through the render_struct_field_data helper.

---

app/views/catalog/_index_online_section.html.erb
app/views/catalog/access_panels/_temporary_access.html.erb

Make TemporaryAccess links always have a Stanford S icon.

---

app/models/concerns/hathi_links.rb
app/models/hathi_trust_links.rb
app/models/solr_document.rb
app/views/catalog/_index_online_section.html.erb
app/views/catalog/access_panels/_temporary_access.html.erb
lib/access_panels/online.rb
lib/access_panels/temporary_access.rb
spec/lib/access_panels/online_spec.rb
spec/lib/access_panels/temporary_access_spec.rb
spec/models/concerns/hathi_links_spec.rb
spec/models/hathi_trust_links_spec.rb

Part of #2455 
The goal for this is to have no change to existing links that are truly Stanford only, and that the public domain links can be pulled into the regular Online section w/o forcing the user through Stanford auth.

Refactor HathiTrust Publicly Accessible Links to Online Panel

---

app/models/request_links/hoover_archive_request_link.rb
app/models/request_links/hoover_request_link.rb
spec/models/request_links/hoover_archive_request_link_spec.rb
spec/models/request_links/hoover_request_link_spec.rb

Don't link to Hoover Library/Archive requests when available via ETAS.

---

app/controllers/concerns/email_validation.rb
app/controllers/feedback_forms_controller.rb
config/locales/searchworks.en.yml
spec/controllers/catalog_controller_spec.rb
spec/controllers/feedback_forms_controller_spec.rb

Now that we're only allowing Captcha authenticated anonymous users to submit feedback/record emails so it seems like we can ease the rule about blocking content with URLs as spam.
I'm interested in the take of others (in particular those who manage the feedback @trapido / @jlkalchik) on allowing users to send links via feedback now.  It would be tough to say what legitimate spam is being blocked by that filter (my assumption would be zero as it would get stopped by the Captcha).  I'm guessing we're only seeing actual users being frustrated by this filter now, and we can/should remove it.
I'm also not sure if we can/should provide more guidance to the user that we report the URL of the page they submit the feedback/etc from (because it seems like more often than not that's the URL they're …

Allow users to report URLs in their feedback and record emails.

---

app/assets/javascripts/course_reserves.js

Fixes https://github.com/sul-dlss/course_reserves/issues/219
Note: per https://m.phillydevshop.com/turbolinks-5-and-datatables-a882c29d6eff the table state will be lost on navigation. This seems preferred over the duplication.

Destroys datatable for crez on page nav

---

app/views/catalog/_field_from_marc.html.erb
app/views/marc_fields/_marc_field.html.erb

I wasn't sure if we had a compelling reason not to do so.  Was noticing some records w/ some unlinked URLs in note fields and remembered that we have talked about doing this in the past.  🤷

Use auto_link when generically rendering MARC metadata fields

---

app/controllers/catalog_controller.rb
app/views/catalog/index.json.jbuilder
spec/controllers/catalog_controller_spec.rb

This is to facilitate the Online link described in sul-dlss/sul-bento-app#293

Augment JSON API documents to include link data (similar to Articles+)

---

app/assets/stylesheets/modules/home-page.scss
app/views/shared/_home_page_bento.html.erb
spec/views/shared/_home_page_bento.html.erb_spec.rb

Part of #2518 
_Note: This PR does not add the LibGuides & Exhibits blocks, but adds some affordances to make them easier.  They will be added once we're ready in #2521_

Update Bento Home Page Section

---

Gemfile
Gemfile.lock

Version 4.7.2 should address this as a fix has already been merged (but not released).
See honeybadger-io/honeybadger-ruby#371

Don't use Honeybadger 4.7.1

---

app/assets/stylesheets/modules/home-page.scss
app/assets/stylesheets/modules/search-bar.scss
app/views/catalog/_home_page.html.erb
app/views/catalog/_search_targets_widget.html.erb
app/views/layouts/searchworks.html.erb
app/views/shared/_home_page_bento.html.erb
app/views/shared/_search_bar.html.erb
config/locales/searchworks.en.yml
spec/features/article_searching_spec.rb

Closes #2516 
Paired with @jvine and @camillevilla on this

Update search bar banner styling and layout

---

app/models/lib_guides_api.rb
spec/models/lib_guides_api_spec.rb

Escape user's search terms before sending to the LibGuides API.

---

Gemfile
Gemfile.lock
app/views/layouts/searchworks.html.erb
config/locales/searchworks.en.yml

Custom alerts can now be managed with https://github.com/sul-dlss/global_alerts/blob/main/sul.yaml file

Replace custom alert implementation with global_alerts gem

---

app/views/layouts/searchworks.html.erb

Move the masthead down into the main section below alerts/flashes.

---

app/assets/stylesheets/modules/subnavbar.scss
app/views/shared/_search_navbar_services_menu.html.erb
app/views/shared/_search_subnavbar.html.erb
spec/features/article_searching_spec.rb
spec/features/blacklight_customizations/search_toolbar_spec.rb
spec/features/responsive/search_subnavbar_responsive_spec.rb

Update library services menu and add COVID status link

---

config/settings.yml

Disabling for now until we can add some text to indicate to users
that they are now in this mode because of not receiving results
Related to #2561

Disable smarttext search mode

---

app/models/concerns/marc_json_extension.rb
app/models/solr_document.rb
spec/models/solr_document_spec.rb

I'm considering serializing the MARC record as json to (🤞 ) cut down on size and improve indexing/parsing performance too.

Extend SolrDocument to support loading in json-serialized marc data

---

Gemfile
Gemfile.lock

A teeny update to the ebsco-eds gem that needs to get tested out in stage:
https://github.com/ebsco/edsapi-ruby/compare/v1.1.0...v1.1.1
Anything useful for #2574?

Patch update for EBSCO EDS API

---

app/views/collection_members/_image_collection_filmstrip.html.erb

Relabel 'images' to 'parts' in collection film strip

---

app/models/request_link.rb
config/solr_configs/schema.xml

Fixes #2643
This commit re-adds INPROCESS and ON-ORDER as current locations for spec-coll items that are not requestable. It also adds MISSING as a current location for spec-coll items that are not requestable. This has the effect of disabling the Request button for these items.

Change behavior governing what spec-coll items are requestable

---

app/assets/stylesheets/bootstrap-variables.scss
app/assets/stylesheets/modules/feedback-form.scss
app/helpers/feedback_form_helper.rb
app/views/shared/_search_subnavbar.html.erb
app/views/shared/_top_navbar.html.erb
app/views/shared/feedback_forms/_chat_with_librarian.html.erb
app/views/shared/feedback_forms/_connection_form.html.erb
app/views/shared/feedback_forms/_form.html.erb
app/views/shared/feedback_forms/_form_fields.html.erb
app/views/shared/feedback_forms/_reporting_from.html.erb
app/views/shared/quick_reports/_form.html.erb
spec/features/quick_report_spec.rb

Fixes #2497
This PR makes visual changes to the feedback form and the connection form in
SearchWorks. Also includes:
* Fix test
* Increase contrast of info/success/warning/danger states (including alerts)
* This brings Bootstrap 5 colors, which provide better accessibility, into Bootstrap 3
* Remove an unused CSS class
What do you think, @ggeisler ? Anything I missed, or any feedback to offer?

Bring feedback form closer to compliance w/ current expected look & feel

---

app/models/marc_fields/added_entry.rb

This might happen if the data is coming from an unmatched vernacular field.
Fixes #2670

Guard against the 740 field not existing

---

app/controllers/feedback_forms_controller.rb
app/helpers/feedback_form_helper.rb
app/views/shared/feedback_forms/_form.html.erb
app/views/shared/feedback_forms/_form_fields.html.erb
app/views/shared/quick_reports/_form.html.erb
config/initializers/new_framework_defaults_5_2.rb
spec/features/feedback_form_spec.rb

We may render the feedback form (at least) twice -- once for general
feedback, and once for connection problems.
The explicit `name` is unfortunate, but Rails 6.x adds a 'prefix'
attribute to form_with that will replace the scope attriubte and
all those explicit form control `name`  attributes.

Use form_with to generated scoped form element ids for feedback forms

---

app/assets/stylesheets/modules/home-page.scss

Remove some extra bottom margin from featured resources panels

---

app/assets/stylesheets/modules/gallery-view.scss
app/controllers/catalog_controller.rb

Now that we're not using blacklight-gallery... we don't need code to disable slideshow view.

Remove unused slideshow view code

---

app/views/shared/_search_subnavbar.html.erb

Update COVID page link to 2021 access

---

app/models/request_link.rb

> @seestone: [See] https://searchworks-uat.stanford.edu/view/13323342
> It’s SPEC-COLL but getting a request link.
> It’s because the current loc isn’t INPROCESS, but ENDPROCESS.  Two locations used for slightly different “end processes”…but both meaning you can’t get it yet
> so we need to add ENDPROCESS to the list of SPEC-COLL that shouldn’t get a link

Add `ENDPROCESS` to the list of special collection of SPEC-COLL exceptions

---

app/views/browse/index.html.erb

Fixes #2786, more or less. This seems to happen (mostly) when crawlers have old, cached data and an item barcode changes. There's probably something better we could do, but not breaking with a 500 error is at least a start.

Don't assume a given barcode exists for an item

---

app/models/search_builder.rb
spec/models/search_builder_spec.rb

- Apply database title prefix query to `:fq` instead of `:q`
- Validate value of `:prefix` param before generating the query
- Adjust tests
- Remove `:qt` param assignment
Closes #2790 
Shown working on stage:

Refactor to fix database 0-9 filter.

---

app/models/concerns/eds_links.rb
app/views/articles/access_panels/_online.html.erb
spec/models/concerns/eds_links_spec.rb
spec/views/article/access_panels/_online.html.erb_spec.rb

Set category 2 links (PDF and PDF E-Book) to Stanford only and add "S" icon in show view when displaying these links.
QUESTION: Not sure whether we should be showing the "S" icon on the index view as well?
Partially addresses #2771

EDS PDF download links display with "S" icon (Stanford Only).

---

lib/constants.rb

We want this:
We don't want this:

Add TANNER to HOURS_LOCATIONS constants.

---

app/assets/stylesheets/modules/subnavbar.scss
app/views/shared/_search_subnavbar.html.erb

Remove 2022 Access link from subnavbar.

---

.solr_wrapper
config/deploy/preview_articles.rb

For now, allow any branch to deploy to sandbox-f. linked-data-experiments branch is out of date and uses a version of mimemagic that got removed from rubygems.

Allow any branch to deploy to sandbox-f

---

app/helpers/access_panel_helper.rb

Pre-Blacklight 7:
After this change:

Guard against missing library thumbnails (probably from bad data); fixes #2877

---

app/components/blacklight/constraint_layout_component.html.erb

This is a work-around for #2876, at least restoring parity with the old behavior. I though Blacklight handled the de-mangling, but maybe we've opted out of that somewhere along the line.

Guard against mangled urls when displaying constraints

---

app/controllers/articles_controller.rb
app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
app/views/browse/index.html.erb
app/views/catalog/_database_prefix.html.erb
app/views/catalog/_search_results.html.erb
config/application.rb
lib/search_query_modifier.rb
spec/controllers/concerns/advanced_search_params_mapping_spec.rb
spec/helpers/catalog_helper_spec.rb
spec/lib/search_query_modifier_spec.rb
spec/views/shared/_zero_results.html.erb_spec.rb

Generally a good idea for security, and also fixes #2876 so we let Blacklight de-mangle URLs "normalized" by PHP.

Stop using `permit_all_parameters` configuration

---

Jenkinsfile
config/deploy/preview_folio.rb
config/deploy/preview_gryphon.rb

Dev/UAT environments deploy from HEAD:
searchworks-stage
searchworks-uat
gryphon-search
searchworks-folio-dev
Prod and data preview environments deploy tagged releases:
searchworks-prod
sw-preview-prod
sw-preview-stage
searchworks-morison

Wire up continuous deployment for searchworks

---

app/assets/stylesheets/modules/view-type-group.scss
app/assets/stylesheets/searchworks.scss
config/locales/blacklight.en.yml
spec/features/blacklight_customizations/view_options_spec.rb

I can't see any other context where those labels need to be upper-case 🤷‍♂️

Lower-case the view labels in the i18n file instead of doing it on-the-fly with css

---

app/models/concerns/document_links.rb

This was a regression from the blacklight 7 upgrade. Previously we limited just to fulltext:
https://github.com/sul-dlss/SearchWorks/blob/v3.3.13/lib/access_panels/online.rb#L20

Limit EDS online links to just the fulltext

---

app/models/concerns/dor_content_metadata.rb
app/models/solr_document.rb
app/views/catalog/_show_mods.html.erb
spec/models/concerns/dor_content_metadata_spec.rb
spec/views/catalog/_show_mods.html.erb_spec.rb

This will suppress the embed and header for MODS resources if we know there is no published content (`:dor_resource_count_isi` field is present and not a positive number). Because this is a new field requiring re-indexing, the logic allows the embed to display if the `:dor_resource_count_isi` field is not yet set on the record.
Partially addresses #2885

Suppress embed for MODS resources when :dor_resource_count_isi field exists and is 0

---

app/assets/javascripts/blacklight/facet_load.js
app/assets/stylesheets/blacklight/_facets.scss
app/assets/stylesheets/modules/image-collection-filmstrip.scss
app/assets/stylesheets/modules/sul-icons.scss

before
after
before
after
(scroll still works when needed)

Small style changes

---

app/components/access_panels/collection_component.html.erb

Fix collection access panel display

---

app/helpers/marc_helper.rb
spec/helpers/marc_helper_spec.rb

Closes https://github.com/sul-dlss/searchworks_traject_indexer/issues/647
I had originally thought this was an issue on the indexing side, but it appears that the intent was for SearchWorks to select the right search field based the tag in the `uniform_title_display_struct` but was looking in the wrong place.

Look for :uniform_title_tag in the correct location in the uniform_title_display_struct

---

app/assets/javascripts/jquery.preview-gallery.js
app/models/nearby_on_shelf.rb

De-dup item list for call number browse fixes issue where preview would not display:
Fix for preview arrow placement:
Before:
After:

De-dup call number browse list; fix preview arrow placement on full page view.

---

app/views/article_selections/_tool_dropdown.html.erb

Throw a `download` attribute on the RIS Download link

---

lib/holdings/location.rb

Sends a honeybadger notification if we try to fetch the name
for a location that doesn't have a code->name mapping.

Handle missing location names in stackmap links

---

app/models/concerns/folio_json_export.rb
app/models/solr_document.rb
app/views/catalog/_folio_json_view.html.erb
config/initializers/mime_types.rb
spec/models/concerns/folio_json_export_spec.rb

This just enhances work for https://github.com/sul-dlss/SearchWorks/issues/2955 to make it easier to debug using browser JSON formatting / expand / collapse
You can navigate to e.g. `/view/13839521.folio_json` and see something like this:
The main question I have about this PR is from the [BL docs](https://www.rubydoc.info/gems/blacklight/6.0.1/Blacklight/Document/Export) about exports:
> The convention for methods contained in extensions that transform to an exportable file of some kind is “export_as_*”. For instance, “export_as_marc21” would return a String object containing valid marc21, and “export_as_marcxml” would return a String object containing valid marcxml. The tokens used after “export_as” should normally be the format names as registered with Rails Mime::Type.
^ So according …

Create .folio_json export format

---

app/assets/stylesheets/bootstrap-overrides.scss

If people agree with my writeup in the ticket, this PR closes #1004
I believe the Bootstrap folks fixed the underlying issue that this workaround addressed. The reported bug only occurred in production though, so not sure the best way to test.

Remove outdated modal z-index workaround

---

app/models/concerns/eds_links.rb
app/models/concerns/hathi_links.rb
app/models/concerns/index_links.rb
lib/search_works/links.rb
spec/components/access_panels/online_component_spec.rb
spec/fixtures/solr_documents/24.yml
spec/fixtures/solr_documents/5749286.yml
spec/lib/links_spec.rb
spec/models/concerns/eds_links_spec.rb
spec/models/concerns/index_links_spec.rb
spec/models/concerns/marc_links_spec.rb
spec/models/json_results_document_presenter_spec.rb
spec/views/catalog/_accordion_section_online.html.erb_spec.rb
spec/views/catalog/_show_marc.html.erb_spec.rb
spec/views/catalog/record/_marc_contents_summary.html.erb_spec.rb

Closes #2969 
sul-bento-app displays links that are generated in SearchWorks and appear in the JSON search results in `fulltext_link_html` so no changes are needed in bento: 
https://searchworks.stanford.edu/?f[access_facet][]=Online&search_field=search&q=Air+and+Marine+Operations+vision+and+strategy&format=json

Move HTML link generation into Link class (replaces attribute from Solr)

---

app/assets/javascripts/jquery.rotatehelper.js
app/assets/javascripts/search_navbar_services_menu.js
app/assets/stylesheets/modules/subnavbar.scss

Fixes #1461
Currently the carets in the mobile menu don't rotate at all,
and when you toggle inner menu items, it causes the main Menu hamburger to incorrectly toggle (see live gif in issue)
This PR updates some incorrect jQuery selectors and stops event propagation from the inner menu items.
current (help caret not moving)
fix
current (main menu icon is in "closed" state even though it is open)
fix
📝 CHANGELOG update?
Fix icon rotation in mobile menu

Fix icon rotation on toggle in mobile menu

---

app/controllers/catalog_controller.rb

We don't want bots crawling too deep, or regular users asking for massive page sizes, but sometimes it's nice to get a whole bunch of records (as JSON, MARCXML, etc).

Make it easier to export a whole bunch of records

---

.rubocop.yml
.rubocop_todo.yml
app/controllers/browse_controller.rb
app/models/concerns/solr_holdings.rb
app/models/nearby_on_shelf.rb
app/views/browse/index.html.erb
app/views/browse/nearby.html.erb
spec/models/nearby_on_shelf_spec.rb

Update browse nearby to use before/after shelfkey offsets (replacing forward/backward pagination from a known point). This   ensures consistent + complete pagination through high-count shelfkeys (but may also need https://github.com/sul-dlss/searchworks_traject_indexer/pull/679 for best display)

Use before/after shelfkey offsets to drive browse nearby pagination

---

app/views/article_selections/_tool_dropdown.html.erb
app/views/bookmarks/_tool_dropdown.html.erb

Previously the `download` attribute had been set to `true` for the ris export link causing the downloaded file to be named `true`. We had not set the `download` attribute for endnote downloads, so for consistency I added the attribute there as well.
See download attribute reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

Set download attribute on ris and endnote export links to the filename of the download.

---

app/assets/stylesheets/blacklight/_controls.scss
app/assets/stylesheets/bootstrap-overrides.scss
app/assets/stylesheets/modules/buttons.scss
app/assets/stylesheets/modules/record-toolbar.scss
app/assets/stylesheets/modules/sort-and-per-page-toolbar.scss
app/assets/stylesheets/print/styles.scss
app/views/article_selections/_tool_dropdown.html.erb
app/views/articles/_search_header.html.erb
app/views/bookmarks/_tool_dropdown.html.erb
app/views/catalog/_sort_and_per_page.html.erb
spec/features/access_points/databases_spec.rb
spec/features/blacklight_customizations/results_toolbar_spec.rb
spec/features/blacklight_customizations/sort_options_spec.rb
spec/features/blacklight_customizations/view_options_spec.rb
spec/features/responsive/results_toolbar_spec.rb
spec/features/sort_and_per_page_dropdown_spec.rb
spec/features/tabbed_selections_spec.rb

Fixes #2151 
-- according to this[ umbrella ticket](https://github.com/sul-dlss/SearchWorks/issues/1885), was based on user feedback
~~I didn't know what "centering" meant, so just styled the buttons. @ggeisler I'd be interested in your feedback and input especially considering this ticket is so old!~~
**Edit 9.1.22:** updated with centering and modified mobile view (reviewed/approved by @ggeisler yesterday, thank you!)
Before:
After:
Before mobile:
After mobile:

Re-style buttons in Selection lists toolbar

---

app/presenters/sms_presenter.rb
spec/presenters/sms_presenter_spec.rb

We don't want carriers to digest messages, but if they do, we want to make sure there's trailing whitespace to separate our message from any wrapping they inject
SW-4130

Try some things to help ensure the URL is clickable

---

config/locales/searchworks.en.yml
config/settings.yml
config/settings/development.yml
config/settings/test.yml

This reverts the request link related configuration to a pre-Aeon state
until the Aeon libraries are ready for implementation. It keeps the
Aeon config active in the dev and test environment settings so that
tests will pass.
Also removes the OAC_REQUEST_LINKS config, which is made redundant by
Aeon work and no longer referenced.

Revert Aeon configuration temporarily

---

app/assets/stylesheets/modules/mastheads.scss

Wrap the collection descriptions somewhere around 100ch

---

lib/constants.rb

Green Reference staff have requested a new Symphony location `HH-FOYER`.
Closes #3028

Add new HH-FOYER location to mappings

---

app/models/marc_field.rb
spec/models/marc_field_spec.rb

Prior to #2647, we didn't do any html sanitization. Turns out, `safe_join` is too aggressive with html entities (see e.g. SW-4131), so we actually have to do some proper sanitization.

Sanitize MarcField display value output

---

.rubocop.yml

This keeps the build from randomly failing after a bundle update.  We will now be intentional about when we want to add new cops

Be explicit about which rubocops we care about

---

Gemfile
Gemfile.lock
config/environments/production.rb

Uglifier is no longer recommened for Rails 7. See https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt\#L29-L36

Upgrades the production assets to the rails 7 defaults

---

config/initializers/rack_attack.rb

We're currently blocking some legit users, e.g. using "select all" with large result sets
See SW-3894

Only guard catalog search (+ result) paths using rack-attack

---

config/initializers/rack_attack.rb

Ref #1766
This borrows DLME's rack-attack config to send headers to clients informing them about throttle settings and when they'll get unblocked. It applies a stricter throttle (12 requests per minute) to article searching but disables all throttling for Stanford local clients.

Throttle article searching more aggressively to protect EDS API

---

app/helpers/xml_api_helper.rb
app/models/concerns/druid.rb
app/models/concerns/index_links.rb
app/models/concerns/marc_links.rb
app/views/catalog/_index_default.mobile.builder
app/views/catalog/_index_online_section.html.erb
spec/components/access_panels/at_the_library_component_spec.rb
spec/components/access_panels/online_component_spec.rb
spec/components/location_request_link_component_spec.rb
spec/fixtures/solr_documents/29.yml
spec/fixtures/solr_documents/40.yml
spec/fixtures/solr_documents/5608954.yml
spec/fixtures/solr_documents/57.yml
spec/fixtures/solr_documents/5749286.yml
spec/fixtures/solr_documents/7626894.yml
spec/fixtures/solr_documents/8923346.yml
spec/mailers/search_works_record_mailer_spec.rb
spec/models/concerns/druid_spec.rb
spec/models/concerns/index_links_spec.rb
spec/models/hathi_trust_links_spec.rb
spec/models/json_results_document_presenter_spec.rb
spec/views/catalog/_accordion_section_online.html.erb_spec.rb
spec/views/catalog/_index_marc.html.erb_spec.rb

This removes our dependence on legacy link fields: `url_fulltext`, `url_restricted`, `url_suppl`, `url_sfx`, and `managed_purl_urls`, relying instead on the `marc_links_struct` field.
Closes #3131
Unblocks #3112 and https://github.com/sul-dlss/searchworks_traject_indexer/issues/856

Stop using url_* and managed_purl_urls fields

---

app/models/concerns/index_links.rb
app/models/concerns/marc_links.rb
app/models/links.rb
app/models/links/ezproxy.rb
spec/models/concerns/index_links_spec.rb
spec/models/concerns/marc_links_spec.rb
spec/models/links/ezproxy_spec.rb

Creates a Links::Ezproxy class to wrap logic related to deciding whether to add a proxy prefix and which prefix to add.
Closes #3112

Add EZproxy prefix only for links with specific 856$z notes

---

lib/holdings/item.rb

This enables item-level request links for e.g. hold/recall

Determine item circulation using FOLIO loan policies

---

app/components/access_panels/library_component.html.erb
app/components/access_panels/library_component.rb
config/settings.yml
lib/holdings/library.rb
spec/components/access_panels/library_component_spec.rb

This fixes a regression introduced in #3156.

Defensively guard against missing library information

---

app/services/folio/circulation_rules/rule.rb

Adds some newlines and formatting so that the parts of the rule are clearer. When inside a `<pre>`, it's hard to tell the parts apart and figure out what's a rule vs. a policy.
Before:
After:

Make the circ rule debug info in librarian view easier to read

---

app/controllers/catalog_controller.rb
spec/requests/stackmap_spec.rb

Bot have been calling this route with invalid parameters.  This check prevents us from trying to render when we don't have the necessary data. Fixes https://app.honeybadger.io/projects/50022/faults/96387675

Require the library parameter for stackmap

---

.rubocop_todo.yml
app/assets/javascripts/jquery.plug-google-content.js
app/assets/javascripts/truncate.js
app/assets/stylesheets/modules/results-documents.scss
app/models/concerns/collection_titles.rb
app/models/concerns/marc_metadata.rb
app/models/marc_fields/linked_collection.rb
app/models/solr_document.rb
app/views/catalog/_index_marc.html.erb
app/views/catalog/_index_mods.html.erb
app/views/catalog/_index_online_section.html.erb
app/views/catalog/record/_marc_upper_metadata_items.html.erb
app/views/marc_fields/_linked_collection.html.erb
app/views/selected_databases/_database.html.erb
config/locales/searchworks.en.yml
config/solr_configs/solrconfig.xml
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/models/concerns/collection_titles_spec.rb
spec/models/marc_fields/linked_collection_spec.rb
spec/views/catalog/_index_marc.html.erb_spec.rb
spec/views/catalog/_index_mods.html.erb_spec.rb
spec/views/catalog/record/_marc_upper_metadata_items.html.erb_spec.rb
spec/views/preview/_show_mods.html.erb_spec.rb

Closes #3150 
Show view with vernacular title:
Index view with more/less widget:
Still todo:

Display MARC 795 values and link to subject search

---

app/services/folio/circulation_rules/policy_service.rb

Group names are under the key 'group', not 'name'

---

app/assets/stylesheets/modules/results-documents.scss

Ensure Safari does not apply a list-style to collection title links

---

app/assets/javascripts/analytics.js

Here we're looking for an href attribute that has a protocol separator in it.  I'm fairly certain that there is no part of the application that has the data-behavor='requests-modal' attribute set.
Fixes #3260

Use a legal selector for external links

---

lib/holdings/location.rb

This code will break if it is called:
```
bin/rails c
Loading development environment (Rails 7.0.6)
irb(main):001:0> RequestLink
(irb):1:in `<main>': uninitialized constant RequestLink (NameError)
RequestLink
^^^^^^^^^^^
```

Remove unused method

---

config/settings.yml
lib/constants.rb

There are some new FOLIO temporary location codes that do not map to legacy codes. They're specified in [this spreadsheet](https://docs.google.com/spreadsheets/d/1TCWHj45Yb7_7kHst0Cg0Wrk9vGcRX86qYeAqhX1lYvA/edit#gid=0) and mapped in the indexer from [temp_locations.tsv](https://github.com/sul-dlss/searchworks_traject_indexer/pull/977).
Closes #3154

Add FOLIO codes to unavailable locations

---

app/components/location_request_link_component.rb
app/policies/request_link_policy.rb

This separates the "should we display" logic to a separate class from "how we display".  As these are both fairly complex, they each deserve their own class.

[Refactor] Extract RequestLinkPolicy from RequestLinkComponent

---

config/routes.rb
spec/requests/symphony_legacy_url_spec.rb

(I'm personally tired of deleting the `a`)

Redirect FOLIO hrids that start with an `a` to their legacy url

---

app/models/marc_fields/linked_collection.rb
app/views/marc_fields/_linked_collection.html.erb
config/locales/searchworks.en.yml
spec/fixtures/marc_records/marc_metadata_fixtures.rb
spec/models/marc_fields/linked_collection_spec.rb
spec/views/catalog/record/_marc_upper_metadata_items.html.erb_spec.rb

Fixes an issue where there is unneeded sanitization happening when getting the values from the SolrDocument's marc field, which results in displaying `&amp;` on the rendered page. Also, seems like a better approach? I'm not sure I'm understanding what the preferred patterns are in SearchWorks though.
Example record: https://searchworks.stanford.edu/view/34329
Before:
After:

Use collection_titles method on SolrDocument to render linked values in upper metadata section

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/components/access_panels/library_component.rb
spec/components/access_panels/library_component_spec.rb

This used the data-hidpi-src attribute, but all modern browsers use the srcset attribute, which is natively supported by Rails.

Remove the obsolete retina_tag gem

---

config/initializers/rack_attack.rb

The user agent header SHOULD be sent according to https://datatracker.ietf.org/doc/html/rfc9110\#section-10.1.5 So, we still accept this request, but treat it as suspicious with regard to article access.
Fixes #3315

Handle the case where there is no user-agent

---

app/policies/location_request_link_policy.rb

This is already checked in the caller (#show?)

Remove a duplicate check

---

app/components/location_request_link_component.rb
lib/holdings/library.rb
spec/components/location_request_link_component_spec.rb
spec/lib/holdings/library_spec.rb

Hoover Library and Hoover Archives are being merged into one organization FOLIO. If there's a finding aid, patrons should use it to request items for anything in `HOOVER`.

Use 'Request via Finding Aid' for Hoover Library items with finding aids

---

app/policies/location_request_link_policy.rb
lib/holdings/item.rb

Items with a blank barcode can't be matched up with their FOLIO item. Perhaps we should populate the item_display barcode field with the UUID if there's no barcode?

Be a little cagier about the presence of a FOLIO item

---

spec/components/item_request_link_component_spec.rb

There was no method with this name

Remove incorrect describe call from an rspec test

---

app/services/folio/locations_map.rb

Lane has no equivalent codes in Symphony, so their home location codes are passed through as-is from FOLIO.
E.g. https://searchworks-folio-dev.stanford.edu/view/L12

Fall back on the provided location code if a legacy code wasn't found

---

lib/holdings/item.rb
spec/lib/holdings/item_spec.rb

Lane has item-level resources for e-resources in a variety of locations.

Treat items with the type 'ONLINE' as internet resources

---

app/components/access_panels/library_location_component.html.erb
app/controllers/browse_controller.rb
app/policies/item_request_link_policy.rb
lib/holdings/item.rb
lib/holdings/status/deliver_from_offsite.rb
lib/holdings/status/unavailable.rb

Regression from #3332; nil values used to be impossible for (most) item fields.
Fixes #3350

Handle nil values in the Holding::Item better

---

lib/holdings/item.rb
spec/lib/holdings/item_spec.rb

Handle missing full shelfkey values by sorting them last; fixes #3357

---

app/components/item_request_link_component.rb

See https://github.com/sul-dlss/SearchWorks/blob/master/config/locales/searchworks.en.yml\#L266-L271
It used to be used when it was added, but we don't need it anymore:
https://github.com/sul-dlss/SearchWorks/commit/18e115241f9569e81c46ae9661ef6fd7e397cd38

Library does not play a part in link_text generation

---

app/components/item_request_link_component.rb
spec/components/item_request_link_component_spec.rb

I don't see how this can happen in practice. If the item is in one of these locations, it has a location-level request link.

Remove item-level on-site locations

---

app/models/folio/location.rb
app/policies/item_request_link_policy.rb
app/policies/location_request_link_policy.rb
config/settings.yml
lib/holdings/item.rb
lib/holdings/status.rb
spec/components/item_request_link_component_spec.rb
spec/components/location_request_link_component_spec.rb
spec/lib/holdings/status_spec.rb
spec/models/folio/location_spec.rb
spec/services/folio/circulation_rules/policy_service_spec.rb

Part of #3129 
We can use information from FOLIO's item statuses, location details and circulation rules to determine the (non-real-time) availability information previously determined by Symphony location codes.
- `cdl` => unsupported at FOLIO launch
- `in_process` (currently just Hoover archives without finding aids) => anything with the FOLIO item status of "In process" or in a location that implies in-process. It's unclear why the Symphony definition is quite so limited and marked as explicitly unavailable instead
- `unavailable` (derived from a huge list of current locations) => derived from folio item statuses or the implied status of the item's location
- `noncirc_page` (derived from a list of locations) => locations marked as offsite and a non-circulating item loan policy
- …

Use FOLIO item statuses, circ rules, and location details to calculate availability and request links

---

app/models/concerns/solr_holdings.rb
app/models/folio/item.rb
app/policies/location_request_link_policy.rb
lib/holdings/item.rb
spec/components/location_request_link_component_spec.rb

e.g. for Aeon + mediation groups, we should look at the its permanent location (falling back on the holdings effective location) to determine whether to use Aeon or mediation behavior. This is especially true for items e.g. in-process, out for repair, etc which shouldn't lose their Aeon-ness just because they are temporarily somewhere else.
Part of #3129

Use the permanent location to determine location-specific behavior

---

app/models/concerns/solr_holdings.rb
app/services/live_lookup.rb
config/settings.yml

Prepares us to have more than two LiveLookup services in case we need to use Solr as a backup service while Symphony is shut down. Should get merged around the same time as: https://github.com/sul-dlss/shared_configs/pull/2026

Use Settings.LIVE_LOOKUP_SERVICE to select LiveLookup service class

---

app/models/folio/item.rb

Fixes:
```
[c0bf13c4-fe82-48d5-af43-011785419e76] ActionView::Template::Error (undefined method `permanent_location' for #<Folio::Item:0x00007fed9c799988 @id="cad93aec-5da8-5fdc-b0c5-83389e8bf660", @barcode="36105036611262", @status="Available", @material_type=#<struct Folio::Item::MaterialType id="1a54b431-2e4f-452d-9cae-9cee66c9a892", name="book">, @permanent_loan_type=#<struct Folio::Item::LoanType id="2b94c631-fca9-4892-a730-03ee529ffe27", name="Can circulate">, @effective_location=#<Folio::Location:0x00007fed9c79a1d0 @id="1146c4fa-5798-40e1-9b8e-92ee4c9f2ee2", @code="SAL3-STACKS", @name="Off-campus storage", @institution=#<struct Folio::Location::Institution id="8d433cdd-4e8f-4dc1-aa24-8a4ddb7dc929", code="SU", name="Stanford University">, @campus=#<struct Folio::Location::Campus …
```

Make Folio::Item.permanent_location a readable attribute

---

config/settings.yml
lib/constants.rb

Part of [#1068](https://github.com/sul-dlss/searchworks_traject_indexer/issues/1068)

Remove FOLIO codes since they will handled by Holdings::Status.folio_availability_class

---

app/policies/item_request_link_policy.rb

None of the fall-back current location stuff should actually matter.. if FOLIO says its hold/recallable, we probably want the item-level button 🤷‍♂️

Only use FOLIO request policies to drive the item-level request link

---

app/controllers/browse_controller.rb
spec/controllers/browse_controller_spec.rb

Use preferred item for browse nearby if instance has no preferred barcode

---

app/components/access_panels/library_location_component.html.erb

It's hard to debug item display problems when we don't include a unique identifier for the item 🤷‍♂️

Add the barcode to the item tr tag for debugging

---

app/views/catalog/_sort_and_per_page.html.erb
spec/features/access_points/databases_spec.rb
spec/features/blacklight_customizations/sort_options_spec.rb
spec/features/blacklight_customizations/view_options_spec.rb

Because this has duplicate ids which is an accessability problem.  We don't expect to serve devices that can't handle small navigation.
Fixes #3509

Remove the xs only navigation

---

app/assets/javascripts/jquery.plug-google-content.js
app/components/access_panels/online_component.html.erb
app/components/access_panels/online_component.rb
app/components/access_panels/related_component.html.erb
app/components/access_panels/related_component.rb
app/views/catalog/_index_online_section.html.erb
app/views/catalog/thumbnails/_item_thumbnail.html.erb
spec/components/access_panels/online_component_spec.rb
spec/views/catalog/_accordion_section_online.html.erb_spec.rb
spec/views/catalog/thumbnails/_item_thumbnail.html.erb_spec.rb

It is not present in Bootstrap v4, so this helps us prepare for that transition

Avoid using the CSS class hide

---

app/components/access_panels/course_reserves_component.html.erb

Restore Course reserve title in access panel

---

app/assets/javascripts/jquery.plug-google-content.js
app/components/access_panels/online_component.html.erb
app/components/access_panels/online_component.rb
app/components/access_panels/related_component.html.erb
app/components/access_panels/related_component.rb
app/views/catalog/_index_online_section.html.erb
app/views/catalog/thumbnails/_item_thumbnail.html.erb
spec/components/access_panels/online_component_spec.rb
spec/views/catalog/_accordion_section_online.html.erb_spec.rb
spec/views/catalog/thumbnails/_item_thumbnail.html.erb_spec.rb

This reverts commit e5a10ba85b9471f4fd55461eb87b8f92dc938c7e.
Until we find a solution for the broken gallery view:

Revert "Avoid using the CSS class hide"

---

app/assets/javascripts/jquery.plug-google-content.js
app/assets/stylesheets/modules/gallery-view.scss
spec/features/blacklight_customizations/record_metadata_spec.rb
spec/features/gallery_view_spec.rb

Related to https://github.com/sul-dlss/SearchWorks/commit/e5a10ba85b9471f4fd55461eb87b8f92dc938c7e

Hide fake cover when Google Books cover is present

---

app/controllers/collection_members_controller.rb
app/helpers/collection_helper.rb
app/models/concerns/collection_member.rb
app/models/concerns/digital_collection.rb
app/models/solr_document.rb
spec/helpers/collection_helper_spec.rb
spec/models/concerns/collection_member_spec.rb
spec/models/concerns/digital_collection_spec.rb
spec/views/collection_members/_file_collection_members.html.erb_spec.rb

- Strip leading 'a' from catkeys when finding parent collections
- Make digital collection preview search use a-prefixed catkeys
- Permit some params for CollectionMembersController to silence warnings

Fix collection membership display

---

app/assets/stylesheets/modules/access-panel-library-locations.scss
app/assets/stylesheets/modules/access-panel.scss
app/components/access_panels/library_component.html.erb
spec/components/access_panels/library_component_spec.rb

Rather than adding special styles to remove them.  I think this is easier to understand as there are fewer unnecessary conditionals in the code
Fixes #3567

Additively put a style on links in the LibraryComponent

---

app/models/concerns/schema_dot_org.rb
spec/models/concerns/schema_dot_org_spec.rb

Safari tries to parse these, and expects Author to be a type of Object. Then the parsing fails and it logs a Honeybadger message about it.
See https://app.honeybadger.io/projects/50022/faults/100897149

Remove null schema.org json+ld properties

---

lib/holdings/item.rb
spec/components/access_panels/at_the_library_component_spec.rb
spec/lib/holdings/item_spec.rb

Fixes https://github.com/sul-dlss/sul-requests/issues/1902

Remove PHYSICS (not in FOLIO) and SUL (perfectly valid FOLIO library)  from the zombie list

---

app/views/shared/_search_subnavbar.html.erb
spec/features/connection_form_spec.rb

The "Connection problem?" form is only used on the article search page, so we don't need to draw it on other pages.

Avoid drawing the connection form on pages that don't need it

---

app/views/shared/_search_bar.html.erb
app/views/shared/_search_subnavbar.html.erb
config/locales/searchworks.en.yml
spec/features/blacklight_customizations/accessibility_spec.rb

Fixes #3630
This also makes the search sub-nav into a `nav` and gives it a label; otherwise its contents are outside of any aria landmark.

Remove out-of-order h2 and use as nav label

---

app/assets/stylesheets/modules/access-panel-library-locations.scss

Fixes https://github.com/sul-dlss/SearchWorks/issues/3609
Now the h3 inherits a line-height of 1.2em instead of 1
before
fix
(this is a fake example but wanted to check the dotted underline)
before
fix

Don't cut off descenders with line-height

---

config/settings.yml

Fixes https://jirasul.stanford.edu/jira/browse/SW-4238

Make configured Lane Library name the same as the FOLIO name

---

app/components/access_panels/location_item_component.html.erb
lib/holdings/item.rb

The original purpose of this condition was to prevent live lookup for medical library material ([code ref](https://github.com/sul-dlss/SearchWorks/blame/a1fe2cc37c990f769ccceb8def0fae697d8f8f47/lib/holdings/item.rb#L134)). This is no longer relevant because their material is now in FOLIO with everything else. The condition was preventing bound-with children from displaying live availability.
Before:
After:
Fixes: https://jirasul.stanford.edu/jira/browse/SW-4240

Remove condition preventing bound-with children from displaying live availability

---

config/ezproxy/sul_proxy_file.txt

In #3666 we were asked to add `www.mona.uwi.edu` to the sul proxy file. It was already present in the file, but we were missing a line break between two entries.

Add line break between proxied url entries; closes #3666

---

app/assets/stylesheets/modules/zero-results.scss
app/views/shared/_search_assistance_block.html.erb
app/views/shared/_zero_results.html.erb

Address BS4 style regression on the zero results page; fixes #3670

---

app/helpers/record_helper.rb
app/views/catalog/mastheads/_collection.html.erb
spec/helpers/record_helper_spec.rb

Closes #3671 
This may not be the best or only place to fix this display issue. In both H2 and Argo we've made sure that when `\r\n` is included they are represented properly and do not use the `&#13` html encoding by reverting it back to `\r`. This seems to still be converted to `&#13` when reading the solr document for display in searchworks. 
Happy for any suggestions on how else to approach this.

Encode html &#13 as \r for display

---

spec/features/blacklight_customizations/bookmarks_path_spec.rb
spec/features/blacklight_customizations/facets_spec.rb
spec/features/bookmarking_items_spec.rb

Fixes some tests that failed locally but were excluded from CI.
[Fix wrapping for sort-and-per-page toolbar at smaller viewports · sul-dlss/SearchWorks@52a0eff (github.com)](https://github.com/sul-dlss/SearchWorks/commit/52a0eff2214017adfe77ddaa9bdd88eb944a6346) removed the `.search-widgets` class. `.sort-and-per-page` seems to be the logical choice as the next container that wraps the same elements.
[Fix multiple citations · sul-dlss/SearchWorks@9c5353c (github.com)](https://github.com/sul-dlss/SearchWorks/commit/9c5353cc7e0f22d7a14653c6e5f363573beaa71e) changes the 'By citation format' from a link to a button, the test expects a link.
I didn't confirm the exact commit, but it seems that the facet also switched from a link to a button.

Fix tests to reflect change in markup

---

config/application.rb

Remove unnecessary exception handling

---

config/environments/production.rb

Do not force SSL until ops completes https://github.com/sul-dlss/operations-tasks/issues/3587
Tested on sw-stage with no apparent bad effects.
Issue to revert this change once the ops task is complete: https://github.com/sul-dlss/SearchWorks/issues/3759

Comment out config.force_ssl = true

---

Jenkinsfile-Folio-Update
Jenkinsfile-Lane-Update

This fixes pull requests when jenkins attempts to update folio data & the lane proxy list. These have been failing since the base branch was switched from master to main.

Set base branch to main for jenkins pull requests

---

app/javascript/application.js

Patch Blacklight.modal.receiveAjax to execute recaptcha

---

app/views/shared/feedback_forms/_form_fields.html.erb

On /articles there is a connection form and a feedback form. Previously these both used the same html id.
Fixes #3768

Create a unique id for each feedback form

---

app/assets/stylesheets/modules/accordion-sections.scss
app/views/catalog/_accordion_section_course_reserves.html.erb
app/views/catalog/_accordion_section_library.html.erb

fix css to truncate locations and display locations inline

---

config/environments/production.rb

Now that [ops task #3587](https://github.com/sul-dlss/operations-tasks/issues/3587) is complete to check app health via https we can enable force_ssl.
Closes #3759

Re-enable force_ssl

---

app/components/access_panels/location_item_component.rb
lib/holdings/item.rb

request link when item not lendable
Not sure about this. My gut reaction is that `return false if item.request_link.render?` should be `return false if !item.request_link.render?` due to the conditions of render but I am not familiar enough with edge cases to be sure. Please advise if this is the right route, my gut was or if there is a better route I did not think of.

update render_real_time_availability_request_link? to not render

---

app/views/shared/_email_form.html.erb

Fixes #3808. 
Related to #3762. The new DOMParser parsing/modal content handling appears to leave the noscript elements unprocessed by the browser. This breaks recaptcha.
Seems most straightforward to disable noscript on recaptcha for the email modal.
I thought about amending the new code from #3762 in application.js with something like the following:
```js
// If contents contains noscript elements, they are unprocessed at this point.
// Hack to reprocess those elements.  
frag.querySelectorAll('noscript').forEach(noscript => noscript.innerHTML = noscript.innerHTML);
```
This works for all browsers I've tested on, but I'm unclear if this kind of hack would work everywhere.

Set recaptcha noscript to false for the email modal

---

app/assets/stylesheets/modules/results-documents.scss
app/components/thumbnail_with_iiif_component.html.erb
app/components/thumbnail_with_iiif_component.rb
app/javascript/application.js
app/javascript/jquery.plug-google-content.js
app/javascript/search-context.js
app/views/catalog/_index_gallery.html.erb
app/views/catalog/_thumbnail_default.html.erb
app/views/catalog/thumbnails/_collection_thumbnail.html.erb
app/views/catalog/thumbnails/_item_thumbnail.html.erb
spec/features/blacklight_customizations/results_document_spec.rb

This will assist in our move to blacklight 8.  This also removes a interactive element that behaves like a link but wasn't accessible.
Fixes #3798

Use view components for the thumbnails

---

app/components/record_toolbar_component.html.erb
app/components/record_toolbar_component.rb
app/views/articles/show.html.erb
app/views/catalog/_show_main_content.html.erb

This helps us align with the patterns used by blacklight, so that upgrades are less challenging.

Extract a record toolbar component

---

app/assets/stylesheets/modules/results-documents.scss

Fixes a regression where the iiif logo was displayed next to the thumbnail rather than below it

Ensure the iiif link is under the thumbnail

---

app/assets/stylesheets/modules/gallery-view.scss

Because flex-end has better support. This fixes an autoprefixer warning
Fixes #3838

Use align-items: flex-end rather than end

---

config/settings.yml
lib/hours_request.rb
spec/features/brief_view_spec.rb
spec/features/mhld_spec.rb
spec/fixtures/solr_documents/10.yml
spec/lib/holdings_spec.rb

Clean up unused library settings

---

app/helpers/collection_helper.rb
app/models/concerns/collection_member.rb
app/models/concerns/digital_collection.rb
app/models/concerns/solr_set.rb

closes #3854 
The code in app/models/concerns/solr_set.rb is what fixes this issue. The rest is consolidating the stripping out the a from the catkey.

strip leading a from collection search

---

app/views/catalog/_show_main_content.html.erb

There are currently ~11.5k of these http://sul-solr-prod-a.stanford.edu/solr/#/searchworks-prod/query?q=-format_main_ssim:*&q.op=OR&indent=true
Shelly says this occurs when
> it is not source=MARC and is currently uncataloged.
This is probably an upstream bug: https://github.com/projectblacklight/blacklight-marc/issues/114
fixes #3866

Workaround for a record with a missing format

---

app/assets/stylesheets/bootstrap-variables.scss

It looks like bootstrap changed their variable name from 3 -> 4.

Restore the pre-bootstrap-upgrade body-color

---

app/components/access_panels/online_component.html.erb

Don't display the online header when the panel is empty

---

app/assets/stylesheets/base.scss

This fixes a regression from bootstrap 3 (and fixes #3876; the gap appearing at all was a result of this)

Restore a .hidden class (used by the preview toggler on brief view)

---

app/controllers/course_reserves_controller.rb
app/helpers/course_reserve_access_point_helper.rb
app/models/concerns/course_reserves.rb
spec/models/concerns/course_reserves_spec.rb
spec/views/course_reserves/index.html.erb_spec.rb

This will allow us to switch to the courses_json_struct field

Decouple CourseInfo from the serialization format

---

app/views/shared/feedback_forms/_form_fields.html.erb

Fixes the feedback form reCAPTCHA issue in #3873.
In [SearchWorks v3.21.14](https://github.com/sul-dlss/SearchWorks/releases/tag/v3.21.14) and after, noscript tags in the form containing this reCAPTCHA sometimes do not get processed by the browser. When this happens, it breaks the reCAPTCHA auth.

Disable noscript on feedback form recaptcha

---

app/assets/stylesheets/modules/alert.scss

This was added in a70ecebc90b16302037c5b6fc63ba32cfaa8f397 but is no longer used

Remove unused class

---

app/controllers/catalog_controller.rb
config/solr_configs/schema.xml
config/solr_configs/solrconfig.xml
spec/fixtures/solr_documents/1.yml
spec/fixtures/solr_documents/18.yml

Relates to #3467 
See https://github.com/sul-dlss/searchworks_traject_indexer/blob/cdad30e01b4e44880af5c68923464adad8a74e2e/lib/traject/config/folio_config.rb#L286
There seem to be no documents with `title_uniform_display` in our current production index, and all tests pass without it.
The indexer note says to remove the field in 2010!

Remove references to unused title_uniform_display solr field

---

app/views/catalog/_summary_data.html.erb
spec/components/search_result/item/mods/metadata_component_spec.rb
spec/fixtures/solr_documents/mf774fs2413.yml

The index is populated with summary_display now: https://searchworks.stanford.edu/view/mw886tk2640.json It was added in https://github.com/sul-dlss/searchworks_traject_indexer/pull/224/files

Removing deprecated summary view code

---

app/models/user.rb

Patch to add context to honeybadger, to help address https://github.com/sul-dlss/SearchWorks/issues/3867 .
We want to be able to track sunet ids that correspond to the error so we can generate examples to pass on to SAML etc.

adding context to honeybadger notification

---

app/javascript/analytics.js

This should prevent the warnings about misusing the samesite cookie. See https://www.tinstar.co.uk/studio-blog/some-cookies-are-misusing-the-recommended-samesite-attribute-how-to-fix/

Provide missing cookie_flags to google analytics

---

config/deploy.rb

Jenkins tries to set the BRANCH variable, so we need to make the deploy configuration to respect it.

Allow Jenkins to deploy specific branch

---

app/models/marc_fields/bound_with_note.rb
app/models/marc_fields/bound_with_note_for_access_panel.rb
spec/models/marc_fields/bound_with_note_spec.rb

Fixes VUF-9613
Newly created bound-withs in FOLIO use FOLIO's hrids, not Symphoy catkeys (e.g. https://searchworks.stanford.edu/view/2126474). Until we can use FOLIO's native bound-with info, we should support some FOLIO hrid formats

Support FOLIO-style hrids in the 590

---

app/components/access_panels/library_location_component.html.erb
app/views/catalog/_index_location.html.erb
spec/components/access_panels/at_the_library_component_spec.rb
spec/views/catalog/_index_location.html.erb_spec.rb

Fixes #3775. Future work probably includes refactoring the indexed data (https://github.com/sul-dlss/searchworks_traject_indexer/issues/857) once we better understand what to display.

Only show the MHLD latest information once

---

app/assets/stylesheets/bootstrap-variables.scss
app/assets/stylesheets/modules/librarian-view.scss
app/components/librarian/item_details/table_component.html.erb
app/components/librarian/item_details/table_component.rb
app/models/concerns/solr_holdings.rb
app/models/folio/item.rb
app/models/folio/location.rb
app/views/catalog/_folio_json_view.html.erb
app/views/catalog/_marc_view.html.erb
app/views/catalog/librarian_view.html.erb
spec/components/librarian/item_details/table_component_spec.rb
spec/features/blacklight_customizations/librarian_view_spec.rb
spec/features/brief_view_spec.rb
spec/fixtures/solr_documents/10.yml
spec/lib/holdings/item_spec.rb
spec/models/folio/item_spec.rb
spec/views/catalog/librarian_view.html.erb_spec.rb

Fixes #3761 
On https://searchworks-stage.stanford.edu/view/2800276
Before:
After:
After clicking items:
After for https://searchworks-stage.stanford.edu/view/2279186  (no items)
After for https://searchworks-stage.stanford.edu/view/14859222 (items in a different location)
After for https://searchworks-stage.stanford.edu/view/in00000008968 (on order item)

Update librarian view to have items

---

app/components/access_panels/library_location_component.html.erb
app/models/concerns/marc_bound_with_note.rb
app/views/catalog/_index_location.html.erb

Because this isn't the same as a bound_with holding

Rename method to bound_with_note?

---

app/views/catalog/_index_location.html.erb
spec/features/request_link_spec.rb
spec/views/catalog/_index_location.html.erb_spec.rb

Previously we had code for this that was never activated.
Before:
After:

Display bound-with information on search results page

---

app/assets/stylesheets/modules/managed_purl_panel.scss

... and bring a little more style parity with the single item viewer.
Before:
After:
e.g. https://searchworks.stanford.edu/view/2472159

Fix the alignment of the embed viewer

---

app/assets/stylesheets/modules/buttons.scss
app/assets/stylesheets/modules/sul-toolbar.scss
app/components/view_type_dropdown_component.html.erb
app/views/article_selections/_tool_dropdown.html.erb
app/views/bookmarks/_tool_dropdown.html.erb
app/views/catalog/_sort_widget.html.erb

Or the select all widget. This makes the styles consistent across the search results and display page. Ref https://github.com/sul-dlss/SearchWorks/pull/3823\#issuecomment-1946361223

Don't underline the bookmark checkbox widget

---

lib/holdings/item.rb
spec/components/item_request_link_component_spec.rb

Part of #3892; folio_status and the current location code are both populated consistently:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/folio_record.rb#L183-L213

Remove current_location code check for on-orderness

---

lib/holdings/item.rb
spec/lib/holdings/item_spec.rb

This home location was replaced by a variety of `*-ELECTRONIC` locations, but the item's `type` is always ONLINE for all of those.

Remove home_location logic for online items

---

lib/holdings.rb
lib/holdings/item.rb
lib/holdings/library.rb
lib/holdings/location.rb
lib/holdings/mhld.rb
lib/holdings/status.rb
spec/lib/holdings/item_spec.rb
spec/lib/holdings/library_spec.rb
spec/lib/holdings/location_spec.rb
spec/lib/holdings/mhld_spec.rb
spec/lib/holdings/status_spec.rb
spec/lib/holdings_spec.rb

We used to use these for availability in #1068, but we no longer have this approach

Remove unused as_json methods

---

app/assets/stylesheets/modules/stackmap.scss
app/javascript/jquery.stackmap.js
app/views/catalog/_stackmap_link.html.erb
app/views/catalog/stackmap.html.erb
config/locales/blacklight.en.yml
spec/views/catalog/stackmap.html.erb_spec.rb

Using an anchor isn't appropriate since they don't have an href.  Also increased the spacing to comply with WCAG AA recommended target size

Change stackmap controls into buttons

---

app/services/fixture_harvester.rb
spec/features/alternate_catalog_spec.rb
spec/fixtures/solr_documents/in00000053236.yml

This is useful because eresources have dummy values in `item_display_struct`, this isn't used except to drive the browse nearby feature, which requires shelfkey.

Add a fixture for an eResource with a shelfkey

---

app/components/access_panels/location_item_component.html.erb
app/components/access_panels/location_item_component.rb
app/javascript/controllers/live_lookup_controller.js

Based on Sarah's comments in [#1026](https://github.com/sul-dlss/searchworks_traject_indexer/issues/1026)
Doesn't allow live updating of status if there is an "In_process" availability class, otherwise it allows for updating of status.
Works on records like

don't update live look up status if there is an avaliability class

---

app/javascript/embedded-call-number-browse.js

fix typo in embedded-call-number-browse.js

---

app/javascript/embedded-call-number-browse.js

This script was caching values that didn't always match what existed on the page, especially when the page was restored from a cache.  I've removed the state in the script and now it just relies on the DOM state, so it's impossible to get out of synch
Fixes #4026

Don't recreate continue links on page restored from cache

---

app/components/search_result/location_component.html.erb
app/views/catalog/_accordion_section_library.html.erb

Due to the data-controller="live-lookup" being in each table for each location, it would fire the live_lookup js for each library location. Since rtac looks up an instance record we only need to fire the live lookup once record. This PR moves the data-controller="live-lookup" out of the loop into a wrapper.
closes #4050

update data-controller live-lookup to fire once per instance record

---

app/controllers/browse_controller.rb
app/models/concerns/solr_holdings.rb
app/models/nearby_on_shelf.rb
app/views/browse/index.html.erb
app/views/browse/nearby.html.erb
lib/holdings/spine.rb
spec/models/nearby_on_shelf_spec.rb

The temporary work-around can be removed after https://github.com/sul-dlss/searchworks_traject_indexer/pull/1363 is merged + reindexed.

Extract `Holdings::Spine` and use it to drive browse nearby

---

app/components/search_result/location_component.rb
spec/components/search_result/location_component_spec.rb

This was ocurring because there were MHLDs with only 'library_has'
Fixes #4042

Don't draw empty locations on the search results page

---

app/components/view_type_dropdown_component.rb
app/controllers/browse_controller.rb
app/views/catalog/_view_type_group.html.erb

This is deprecated in Blacklight

Stop using response from SearchService#fetch

---

app/assets/stylesheets/bootstrap-variables.scss
app/assets/stylesheets/sul-variables.scss

We had one color defined with two separate names. We settled on Poppy as that is what is in the brand guide: https://identity.stanford.edu/design-elements/color/accent-colors/

Consolidate to one color name

---

app/components/access_panels/online_component.html.erb
app/components/access_panels/online_link_list_component.html.erb
app/components/access_panels/online_link_list_component.rb

This prevents the controller from raising an error because the buttons it uses aren't drawn
Fixes #4071

Don't instantiate the long-list controller if the list is short

---

app/assets/stylesheets/modules/availability.scss
app/assets/stylesheets/modules/search-bar.scss
app/assets/stylesheets/sul-variables.scss

All color variables except this one were named after the color rather than the purpose. This brings consistency to the palette.  Furthermore, this color is used for more than just a public note, so it's current name is misleading.  I found this name via https://colors.artyclick.com/color-names-dictionary/color-names/citrine-white-color

Colors should have a name not a purpose

---

app/components/access_panels/online_component.html.erb
app/models/solr_document.rb
app/views/catalog/_index_online_section.html.erb
lib/holdings/item.rb
spec/components/access_panels/at_the_library_component_spec.rb
spec/models/solr_document_spec.rb

closes #3944 
If the item is an eresource only item (there are no physical holdings), "At the library" will not render. This is done by updating suppressed? to work for all internet resources not just the SUL ones.
If the  view is an eresource only item there needs to be a library display in the online section if the library is not SUL. library_display looks to see if there are libraries associated with the document, if there are it checks if the record has physical copies or is a SUL location. If it isn't it will return the location name to display in the online section. See https://github.com/sul-dlss/searchWorks/issues/3944#issuecomment-1955173750 for screenshots.

Update "at the library" and "online" view for eresources 

---

app/views/catalog/_index_header_gallery.html.erb

Keep displaying 'Stanford Libraries' on the gallery view for e-resources

---

app/views/catalog/record/_marc_metadata_sections.html.erb
app/views/catalog/record/_mods_metadata_sections.html.erb
app/views/catalog/record/_record_metadata_default.html.erb
lib/holdings.rb
spec/lib/holdings_spec.rb

With #4073, we shouldn't use items to drive browse nearby.

Use browseable_spines instead of browsable_items

---

app/assets/stylesheets/modules/home-page.scss
app/assets/stylesheets/modules/skip-to-nav.scss

All modern browsers support box-shadow without prefixes

Remove browser specific CSS for box-shadow

---

app/javascript/embedded-call-number-browse.js

The preview is what shows when you click the 'preview' button.

Rename method to showGallery as showPreview is confusing

---

app/assets/stylesheets/modules/access-panel-library-locations.scss

This fixes a regression where it was just cut off with no elipsis.
Fixes #4095

Truncate the library name if it's very long

---

app/assets/stylesheets/modules/record-view.scss
app/assets/stylesheets/searchworks-mixins.scss

It's only used in one place, so this is less indirection

Inline the title font mixin

---

spec/components/access_panels/at_the_library_component_spec.rb

This isn't an appropriate place to test this method. This was added in 6837a2206ce0d9492334659c68668a9034bae39b

Remove test about SolrDocument from a component test

---

app/policies/location_request_link_policy.rb
config/settings.yml
spec/components/location_request_link_component_spec.rb

When all the items in a location have an unrequestable item status, we can't place the request in FOLIO.

Don't render request links for item statuses that FOLIO doesn't allow requests

---

app/views/shared/feedback_forms/_form_fields.html.erb

Accessability checkers would like text fields to have labels.

Use hidden fields rather than text fields

---

app/views/catalog/_index_brief.html.erb

This was added in https://github.com/sul-dlss/SearchWorks/commit/2bd9c1fece4b498a358c742b4341b34a814205e1\#diff-9af593bf6c40bab14a30c549ca631cbbcb51fdb139f6c0ea164409718ac1730e but it's unclear why. We don't do this in any other usage of link_to_document with counter.
fixes #4103

Remove weird counter addition.

---

app/views/catalog/record/_callnumber_browse.html.erb

aria-expanded is supposed to go on the focusable interactive control that displays the collapsable section, not the collapsable section itself.
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded Fixes #4087

Remove aria-expanded from callnumber browse

---

app/services/folio_client.rb

We're storing way too much data about courses, instructors, etc. Slice it down to what we could plausibly use.

Only store a subset of the course data

---

app/views/layouts/searchworks.html.erb

onerror is now enableUncaught

---

app/javascript/analytics.js

This is how it worked before we added rollup.  We noticed that events are being drastically undercounted, so this may fix the problem.

Define gtag as a global function

---

app/views/shared/feedback_forms/_form_fields.html.erb

This improves the user experience as this lets the browser fill in some fields for the user. See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete\#values

Add autocomplete hints to the feedback form

---

config/settings.yml

I think this closes #3369. This is the only URL not working after https://github.com/sul-dlss/SearchWorks/pull/3683.

update slac url

---

app/views/catalog/_home_page.html.erb
app/views/catalog/mastheads/_iiif_resources.html.erb
config/settings.yml
spec/components/record/item/mods/metadata_component_spec.rb
spec/views/catalog/_show_mods.html.erb_spec.rb

After some discussion with Sarah we decided to update the IIIF links to https://iiif.io

Update IIIF links to https://iiif.io/

---

app/components/access_panels/library_location_component.html.erb
app/components/search_result/location_component.html.erb

Without unique ids, the show more/less controls on the search results pages don't work. This seems like as a regression introduced in https://github.com/sul-dlss/SearchWorks/pull/4059/files (where previously we didn't give these elements id attributes at all?)

Make sure item tables have a unique-to-the-page id

---

app/policies/item_request_link_policy.rb
spec/components/item_request_link_component_spec.rb

This addresses a situation that can arise from dubious data that
was reported by a tester in searchworks-stage for instance 14642011.
We normally allow a request to be made if we know an item is on
order but it hasn't been added to FOLIO yet, but SPEC is the only
library where this policy should not apply.

Prevent rendering of request buttons for SPEC titles with no items

---

app/views/marc_fields/_subjects.html.erb
spec/views/catalog/record/_marc_subjects.html.erb_spec.rb

The subject links on record pages such as https://searchworks.stanford.edu/view/in00000067099 are getting flagged by SiteImprove as links with the same text (in this case "Leiden") that go to different pages (despite their different title attribute values). @alundgard and I took a look at this and it seemed like we got the best behavior out the screen reader when we added an aria-label attribute with the same value as the title attribute. The screen reader reads the full link text "Printing  Netherlands  Leiden" from the aria-label instead of "Leiden, Printing Netherlands Leiden" from both the link text and the title attribute.

Add aria-label attribute to subject links

---

app/controllers/catalog_controller.rb
config/solr_configs/schema.xml
config/solr_configs/solrconfig.xml

This new field will help address a regression from https://github.com/sul-dlss/searchworks_traject_indexer/pull/382, which started penalizing more complete records that end up with multiple `author_title_search` values (e.g. a 100 + 240 and a 100 + 245) over other records.
This new field should let us boost uniform title matches over other sorts of titles while not excluding relevant results.
sul-solr configs: https://github.com/sul-dlss/sul-solr-configs/pull/325
Indexing PR: https://github.com/sul-dlss/searchworks_traject_indexer/pull/1457

Add best_author_title_search field for the 'the is the one' uniform (or otherwise) title for the record

---

app/views/browse/index.html.erb

closes #4223 
For pages like: 
https://searchworks.stanford.edu/view/12946310
https://searchworks.stanford.edu/view/13065921
Clicking on the view full page in the browse section errors out due to there being no call number or items for the document. However that link automatically puts the call number in the URL. This fixes the code by pulling the call number from the URL if it is already there.

fix for eresources with no call number

---

app/models/marc_fields/included_works.rb

before_t, *after_t = relevant_subfields.slice_before { |subfield| subfield.code == 't' }.to_a
within_t, *extra_fields = after_t.flatten.slice_after { |subfield| subfield.value =~ /[\.|;]\s*$/ }.to_a
Expect the result to be a list with two items in them. When slice_after doesn't find anything it returns an empty array [], not what it expects: [[], []]. This causes a problem when looping on the Included works field if there are items that aren't after the t field like the record 8113045. This has the subfields [#<MARC::Subfield:0x00000001725ae128 @code="t", @value="Works.">, #<MARC::Subfield:0x00000001725ae100 @code="f", @value="1999.">] which means within_t returns nil.

fix included works parsing of marc, closes #3487

---

config/solr_configs/schema.xml
spec/features/marc_results_metadata_spec.rb
spec/features/mhld_spec.rb
spec/features/results_page_spec.rb

BM25 is the "new" Solr default and causes some minor relevancy changes. The major difference seems to be a little boost to exact matching:
E.g. a query for "The John" no longer ranks the stemmed match "The Johns" higher than exact matches for "The John" 
And putting a little more weight on more unique terms:
E.g. a query for "mcrae jazz" returns titles with Mcrae above ones with Jazz:

Use the BM25 similarity class

---

lib/holdings/location.rb

Apparently some of our stub records have locations with a `nil` code (and our inspect method probably never worked)

Fix Holdings::Location#inspect and guard against nil location codes

---

config/deploy/preview_folio.rb
config/deploy/preview_gryphon.rb
config/deploy/prod.rb

Add courses data to additional environments

---

config/initializers/rack_attack.rb

The current limits might have caught a user paginating through the result set.

Relax rack-attack limits now that we're using metrics across all nodes.

---

config/application.rb

@jonrober says:
> On sw-webapp*, it seems like the application is doing its own log rotation of /var/log/Searchworks/search.log.  logrotate is often rotating an almost empty file, with something else rotating the log first at one minute til midnight.  I’m guessing that it’s the application doing that early rotation.  The result is that a lot of logs are filling extra disk space since the thing rotating them first doesn’t do gzipping and doesn’t do expiration of old logfiles after X days like logrotate.

Stop rotating search logger

---

app/views/shared/feedback_forms/_reporting_from.html.erb

This section is not an alert in the aria sense.  We don't want to disrupt the user with this information.
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role

Remove role=alert from non-live region

---

app/javascript/analytics.js

This seems like a regression from #3036. The previous implementation used the H3 value, not the facet panel text:
https://github.com/sul-dlss/SearchWorks/blame/cb3f26265f3e5c4f2b6d19fe82687c82466ae5ea/app/assets/javascripts/analytics.js#L134-L144

Fix facet event label.

---

app/models/citations/oclc_citation.rb
app/services/oclc_discovery_client.rb
spec/services/oclc_discovery_client_spec.rb

OCLC now supports requesting more than one citation style at once so we no longer need to send separate requests for each style we want to display.

Use new OCLC Citation API feature to fetch multiple citation styles per request

---

app/controllers/browse_controller.rb
app/views/browse/index.html.erb
spec/views/browse/index.html.erb_spec.rb

e-resources have `browse_nearby_struct` (and are kinda the reason we added the field) but don't have any actual items. 
Fixes #4487

Drive browse pages using the browse_nearby_struct, not item_display_struct

---

app/models/citations/oclc_citation.rb
spec/models/citations/oclc_citation_spec.rb

Accounts for case where OCLC sends a response for a citation that does not include the citation.
Example case: https://searchworks.stanford.edu/view/13644707
Before:
After:

Reject oclc citation entries that are missing the citationText and/or style keys

---

app/assets/config/manifest.js
app/assets/stylesheets/component-library-overrides.css
app/assets/stylesheets/sul-variables.scss
app/views/layouts/searchworks.html.erb
app/views/shared/_su_footer.html.erb
app/views/shared/_top_navbar.html.erb

The requested style changes until we fully transition over to the component library during the work cycle.
Reviewed by @dbranchini

Change header/footer logo and styles

---

app/assets/stylesheets/modules/research-starter.scss

Fix image layout when article topic overview text is short

---

app/components/access_panels/online_link_list_component.html.erb
app/models/links/link.rb

Restoring the access condition tooltip:
and fix the list truncation (e.g. for https://searchworks.stanford.edu/view/in00000162623)

Fix regressions in online links

---

app/views/catalog/_accordion_section_library.html.erb
spec/views/catalog/_accordion_section_library.html.erb_spec.rb

aria-expanded is supposed to go on the focusable interactive control that displays the collapsable section, not the collapsable section itself.
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded

Remove aria-expanded from location accordion

---

app/components/access_panels/location_item_component.rb
lib/holdings/item.rb

From the component. This supports the split of the LocationItemComponent in #4070, so that there is no duplication

Move model methods to the model

---

app/assets/stylesheets/modules/constraints.scss

Stop safari from wrapping the 'catalog start' button.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/fonts.scss
app/assets/stylesheets/modules/online-resource-links.scss

A second attempt at adding Tibetan character support.
The first attempt added an overrides specific font family for the Tibetan unicode-range only. Safari had quirks with unicode-range, not falling back down the chain as expected which led to an odd style issue:
Our current "Source Sans Pro" stack doesn't have the Tibetan range. Adding the range to "Source Sans Pro" worked on all browsers except for Chrome/Edge, which ignored the addition.
Adding the Tibetan range to our current fallback font "Arial Unicode MS" is working as expected on Chrome, Edge, Firefox, and Safari.

Use Noto Serif Tibetan for Tibetan Unicode range

---

.github/workflows/ruby.yml

Needs https://github.com/bblimke/webmock/pull/1091/files to work

upgrade ruby ci to 3.4

---

app/services/folio/courses.rb

I think we also need the course ID here. All the current reported course numbers have valid start/end dates. We need to confirm we are comparing the exact same courses and not a course with the same code/name that's not associated with a term.

Include the course ID in HB notice

---

config/schedule.rb

Offsets the hourly job by 15 minutes to see if it changes the `nil` term data we are seeing from #4631 on the off chance it's load and/or being impacted by some other scheduled job.

Add offset to Folio courses scheduled job time

---

app/views/articles/_email_form.html.erb

closes #4632 
This was happening because without the blacklight modal trigger, the modal was redirecting to /articles/email after clicking on the send button. Someone probably refreshed the page to trigger the error. 
Change moves this in line with how email works in the catalog.
https://searchworks.stanford.edu/articles/nlebk__3435673
https://github.com/user-attachments/assets/852b8a9b-bd89-4b96-9eb2-498988c114d1

enable blacklight on articles email form modal

---

app/mailers/application_mailer.rb
config/application.rb

This older way doesn't work in Rails 8.  See https://guides.rubyonrails.org/v7.2/action_mailer_basics.html#generate-the-mailer

Use the prescribed way to configure action_mailer defaults

---

app/policies/item_request_link_policy.rb

item_allows_hold_recall? is doing the exact same check and is a public function so we should use that instead of re-creating it.

remove redundant lines and replace with existing function

---

app/models/concerns/marc_metadata.rb
app/models/marc_fields/hierarchical_place_name.rb
app/views/catalog/record/_marc_bibliographic.html.erb
spec/models/marc_fields/place_name_spec.rb

Don't use the -- subfield delimiter for the 752 relator term; it should be separated by a comma from the geography.

---

spec/features/access_panels/exhibit_spec.rb

Feature tests are slow, so we can have a faster test suite if each has multiple assertions

Consolidate feature tests

---

app/components/stanford_only_popover_component.rb

Remove unnecessary class btn-link from StanfordOnlyPopupComonent

---

app/assets/stylesheets/modules/availability-icons.scss
app/assets/stylesheets/modules/results-online-section.scss
app/components/stanford_only_icon_component.rb
app/components/stanford_only_popover_component.rb

This works in the existing places and will also work with larger fonts (for chat)

Update stanford only icon for better alignment

---

app/assets/stylesheets/modules/recaptcha.css
app/assets/stylesheets/searchworks.scss
app/assets/stylesheets/variables.css
app/components/recaptcha_with_login_link_component.html.erb
app/components/recaptcha_with_login_link_component.rb
app/views/shared/_email_form.html.erb
app/views/shared/feedback_forms/_form_fields.html.erb
spec/components/recaptcha_with_login_link_component_spec.rb
spec/features/blacklight_customizations/emailing_records_spec.rb

Closes #3868
500 vs 600 font weight on hover still in discussion with @dbranchini (600 visually shifts the text).

Add a recaptcha login link component

---

app/javascript/feedback_form.js
app/views/shared/feedback_forms/_form_fields.html.erb
spec/features/connection_form_spec.rb
spec/features/feedback_form_spec.rb

This eliminates unnecessary code. My initial thought was that this supported a non-javascript use case, but the code before also required javascript as it did:
```html
<a class="cancel-link" data-toggle="collapse" data-target="#feedback-form" href="javascript:history.back()">Cancel</a>
```

Generate a button rather than transform link into button

---

app/components/record/marc_content_advice_component.rb
spec/components/record/marc_content_advice_component_spec.rb

Also render unmatched vernacular in the content advice component

---

app/components/articles/index_brief_component.html.erb
app/components/articles/index_brief_component.rb
app/views/catalog/_document_brief.html.erb

This is to make things easier for a bug fix I found for https://github.com/sul-dlss/SearchWorks/issues/2090. This displays correctly on the default view but if you switch to the brief view we are displaying the old content. This partial is where the change needs to get made to fix this issue. I have split the fix into two PRs to make things easier to review.

convert index_brief.html.erb to ViewComponent

---

app/assets/stylesheets/blacklight.scss

Fix facet modal layout.

---

app/components/articles/document_list_component.rb
app/components/search_result/document_component.rb

Fix the bookmark checkboxes alignment.

---

app/assets/stylesheets/modules/browse-toolbar.scss

This CSS can't be what was originally intended. It ends up targeting the callnumber in the availability panel of the preview only when it is in browse nearby:
After:

Remove mistargeted css.

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/blacklight.scss

This interferes with other styles and it's unclear what if any effect it was meant to have

Remove max-width from li

---

app/assets/stylesheets/blacklight.scss

After:
Before:
And current production for comparison:

Tighten up facet vertical padding.

---

app/assets/stylesheets/modules/browse-toolbar.scss
app/views/catalog/record/_callnumber_browse.html.erb
spec/views/catalog/record/_callnumber_browse.html.erb_spec.rb

I figured out what #4830 was supposed to target. 
After (and how it used to be):
Before:

Update callnumber button styling.

---

app/assets/stylesheets/modules/alert.scss
app/assets/stylesheets/searchworks.scss
app/javascript/feedback_form.js

We should just use alert-danger

Get rid of unnecessary alert-error class

---

app/models/concerns/solr_holdings.rb
app/models/folio/item.rb

SPEC reports that the existing list is hard to navigate and would have a better time if it was ordered 🤷‍♂️

Sort folio items by their effective shelving order.

---

app/javascript/select-all.js

I believe that 78af604192ac1c93161d5d42f4664b1cd68f0c83 introduced a bug, where the deferred code was immediately resolved in all instances, which means it wasn't working as desgined in 9d1a31e52a04d58780d4d73d5d9723bf53f09fdc. However, since we haven't been using the deferred code, the original bug has not resurfaced, which means we can get rid of the deferred code, so that it's all a bit simpler.

Simplify select all code

---

app/assets/stylesheets/component-library-overrides.css
app/assets/stylesheets/variables.css
app/components/search_result/login_banner_component.html.erb

style log in link

---

app/assets/stylesheets/modules/availability-icons.scss
app/components/articles/document_component.html.erb
app/components/articles/eds_restricted_component.html.erb
app/views/articles/_show_main_content.html.erb
config/locales/searchworks.en.yml

closes #1452. Would use `hide_whitespace` because app/views/articles/_show_main_content.html.erb is a small change but looks large due to tabbing fixes.

update eds restricted item view to show message and popover

---

app/javascript/feedback_form.js

A recaptcha token is only valid one time
Fixes #4842

Reset the recaptcha after sending the form

---

app/assets/stylesheets/modules/access-panel.scss

`$h4-font-size` is a bootstrap variable that already sets h4 font size. See https://github.com/twbs/bootstrap/blob/f849680d16a9695c9a6c9c062d6cff55ddcf071e/scss/_reboot.scss#L110

Remove unnecessary css rule

---

app/assets/stylesheets/modules/results-documents.scss
app/components/search_result/login_banner_component.rb

The figma has a border of stanford red, we currently have a gray border. This fixes that.
**Figma**
**Current**
**This PR**

change border color on articles login alert

---

app/views/bookplates/_bookplate.html.erb

fix bookplate on medium sizes

---

app/assets/stylesheets/modules/results-documents.scss
app/components/articles/response/facet_group_component.html.erb
app/components/searchworks/response/facet_group_component.html.erb

Restore the hamburger menu icon and clean up vertical alignments for facets

---

app/controllers/article_selections_controller.rb

closes #4862 
search_service = Blacklight::SearchService in app/controllers/article_selections_controller.rb
Somehow it ends up getting into the Eds::SearchService but it doesn't have the eds_params set so it won't work.

have article bookmarks use eds search service

---

app/controllers/bound_with_children_controller.rb
app/views/bound_with_children/index.html.erb

With the stub search builder, we're bypassing some of the things blacklight will do for us (including properly quoting and escaping the item id value, setting the `qt`, etc). If we ever decide to paginate the long bound-with lists, we'll be able to use the default machinery too.

Use the default search builder to construct the bound-with query.

---

app/presenters/article_fulltext_link_presenter.rb
app/views/articles/index.json.jbuilder
app/views/catalog/index.json.jbuilder
spec/presenters/article_fulltext_link_presenter_spec.rb

Show the StanfordOnlySpanComonent on Article results

---

app/controllers/concerns/location_facet.rb

Remove special handling for Education (at SAL1&2)

---

app/assets/stylesheets/bootstrap-variables.scss
app/assets/stylesheets/modules/record-toolbar.scss
app/assets/stylesheets/modules/subnavbar.scss
app/components/record_toolbar_component.html.erb
app/views/shared/_search_subnavbar.html.erb

It is deprecated in Bootstrap https://getbootstrap.com/docs/5.3/migration/\#color-modes-1

Stop using .navbar-dark

---

app/controllers/articles_controller.rb
app/controllers/catalog_controller.rb
app/views/articles/_search_results.html.erb
app/views/catalog/_search_results.html.erb

This helps us with migration to Blacklight 9, which doesn't have a constraints partial.

Use the Blacklight constraints component

---

app/javascript/embedded-call-number-browse.js

closes #4942 
We probably still want to convert this to a stimulus controller but this is a quick patch that will fix the issue for now.

don't allow call number browser ribbon to initialize twice

---

app/assets/stylesheets/base.scss

Closes #4941.
Bootstrap 5 changed the default:
```css
@media (prefers-reduced-motion: no-preference) {
:root {
scroll-behavior: smooth;
}
}
```

Restore scroll-behavior

---

config/settings.yml
config/settings/test.yml

Currently explicitly disabled in -prod:
https://github.com/sul-dlss/shared_configs/pull/2343

Enable citeproc citations by default

---

app/components/stanford_only_popover_component.rb

add focus ring to stanford only button

---

app/components/search_result/mini_bento/layout_component.html.erb

closes #5003 
Mobile in Firefox
In safari

fix mini bento close button on safari

---

app/assets/stylesheets/modules/home-page.scss
app/views/shared/_home_page_bento.html.erb

Fix homepage layout

---

app/javascript/embedded-call-number-browse.js
app/views/catalog/_document_gallery.html.erb

Since, we're adding HTML to the page which was generated by the backend, we may as well be consistent and not have the front end also generate some of the HTML.

Add the full page links in the backend

---

.github/workflows/ruby.yml
Jenkinsfile
Jenkinsfile-Folio-Update
Jenkinsfile-Lane-Update
config/deploy.rb

Fixes #5057
Fixes #5058
We need to remember to cut our release tags on the `release` branch rather than `main`.

Deploy release branch instead of main

---

app/assets/stylesheets/modules/sort-and-per-page-toolbar.scss

Closes #5066 (after backport to `release`)
This is what it was in a recent "working" release:
Now:
This also impacts the same controls that are present at the top of the catalog results page.

Restore button hover color for sul-toolbar

---

app/javascript/analytics.js

Part of #5085.
External link clicks are tracked by default in GA4.

Remove custom IIIF link click tracking

---

app/javascript/analytics.js

Part of #5085 
I think in GA4 this could be better explored via page views, rather than a specific event.
https://analytics.google.com/analytics/web/#/analysis/p342534663/edit/PhaoN7HxSlapy2LeEzwgQQ

Remove the zero results page loaded analytics event

---

app/javascript/analytics.js

Part of #5085 
Now that we're using turbo frames we need more specific event handling so listeners don't get lost during navigation or initialized multiple times.

Fix initialization of analytics listeners

---

app/javascript/analytics.js

Part of #5085.
It was decided browse nearby scroll events aren't very useful.
The availability accordion we will revisit after the new design implementation. A placeholder issue has been created so we do not forget: https://github.com/sul-dlss/SearchWorks/issues/5127

Remove unneeded analytic events

---

app/assets/stylesheets/searchworks4/homepage.css
app/views/catalog/_home_page.html.erb

part of #5152 
Splitting facet design into separate PR/component library.
Darcy asked to remove `What are you searching for?` section.
Before:
Before:
After:
Before:
After:

small homepage updates

---

app/javascript/controllers/copy_link_controller.js

I missed this on review. The designs have a bit of padding here.
Before:
After:

Add padding to the toast icon

---

app/assets/stylesheets/searchworks4/mini-bento.css
app/components/search_result/mini_bento/layout_component.html.erb
config/locales/searchworks.en.yml
spec/features/alternate_catalog_spec.rb

Closes #5231
Only outstanding question I have is if @dbranchini wants the `View results from all tools` link underlined by default.
Mobile:
View all wrapped:
View all unwrapped:

Update mini-bento styles

---

app/assets/stylesheets/searchworks4/search-results.css
app/views/catalog/_search_results.html.erb
app/views/databases/_search_results.html.erb

This cleans up the vertical alignment between the text + icons. Embedded SVGs considered harmful?
Before:
After:

Switch prev/next chevrons to use the icon font.

---

app/controllers/availability_controller.rb
app/services/live_lookup/solr.rb

FOLIO uses the instance uuid, not the hrid, for lookups.

---

app/controllers/articles_controller.rb
app/models/eds/repository.rb
app/models/eds/session.rb
app/services/eds/search_service.rb
spec/controllers/articles_controller_spec.rb

If an EDS session token is expired, the `Eds::Session` will retry the request after requesting a new session token. When the token changes, we should replace the token we stored in the user session with the one we got after attempting the request.

Store the as-used session token in the user session (e.g. if we rotated it during one of our requests)

---

app/assets/stylesheets/searchworks4/search-results.css
app/views/catalog/_sort_widget.html.erb
app/views/shared/_per_page_widget.html.erb

Closes #5255 
Removes the whitespace that was being underlined in the active before:

Fix sort and per page dropdown alignment

---

app/assets/stylesheets/searchworks4/mini-bento.css
app/assets/stylesheets/searchworks4/zero-results.css
app/components/search_result/mini_bento/layout_component.html.erb
app/views/shared/_zero_results.html.erb

Closes #5339
The three column layout could overflow filter names before. @dbranchini suggested trying a variation of one of her [earlier designs](https://www.figma.com/design/fsVWCX66bpvFZGKEHNRBS5/SearchWorks-4.0--WC1-?node-id=819-57015&t=9zBUdA6VHxyixsgy-4) that wrapped mini-bento earlier. That is this:
Three columns:

Style no results page

---

app/assets/stylesheets/searchworks4/facets.css

If you resize the screen from large to small the mini bento will show up below the button. This fixes it.

fix mini-bento resize from large to small

---

app/components/record/marc_contents_summary_component.html.erb
app/components/record/marc_document_component.html.erb
app/components/searchworks4/metadata_field_layout_component.html.erb
app/components/searchworks4/metadata_field_layout_component.rb
app/views/catalog/_dates_from_solr.html.erb
app/views/marc_fields/_included_works.html.erb
app/views/marc_fields/_instrumentation.html.erb
app/views/marc_fields/_link_to_search.html.erb
app/views/marc_fields/_linked_author.html.erb
app/views/marc_fields/_linked_collection.html.erb
app/views/marc_fields/_linked_related_works.html.erb
app/views/marc_fields/_linked_serials.html.erb
app/views/marc_fields/_linked_series.html.erb
app/views/marc_fields/_local_subjects.html.erb
app/views/marc_fields/_marc_field.html.erb
app/views/marc_fields/_production_notice.html.erb
app/views/marc_fields/_subjects.html.erb
spec/components/record/marc_document_component_spec.rb

This allows us to create a little more space around different fields:
Before/After:

Render MARC dt/dd pairs using a layout component.

---

app/assets/stylesheets/searchworks4/record.css
app/components/record_toolbar_component.html.erb

fix toolbar heights/icon alignment

---

app/assets/stylesheets/searchworks4/links.css

Get link hover decoration back on non-underlined links

---

app/assets/stylesheets/searchworks4/record.css
app/components/searchworks4/metadata_field_layout_component.html.erb
app/views/catalog/mastheads/_collection.html.erb

Allow field labels to wrap now that we're wrapping the dt/dds

---

app/components/record/marc_document_component.html.erb

closes #5543 
I don't know how to do this without html safe. I could use help

fix escaping on marc fields

---

app/assets/stylesheets/searchworks4.scss
app/assets/stylesheets/searchworks4/bookplates.css
app/assets/stylesheets/searchworks4/gallery-view.css
app/components/bookplate_fund_component.html.erb
app/components/bookplate_fund_component.rb
app/views/catalog/_search_results.html.erb
lib/page_location.rb
spec/features/bookplates_spec.rb
spec/lib/page_location_spec.rb

Ref #5548 
Makes the requested masthead change (moved above the contraints in a Slack conversation) and pulls in the gallery styling. Widening the gallery view at XXL size and bringing back the view mode selection will be in subsequent PRs.

Move and restyle donor masthead

---

app/assets/stylesheets/searchworks4/search.css

Due to https://github.com/projectblacklight/blacklight/commit/43c7780dd5809ada0321ea6cdb2265d9c940ecf8
Before:
After

Remove border on search field

---

app/assets/stylesheets/searchworks4/masthead.css

We don't need it now that we don't have blacklight

Remove unnecessary override of Blacklight style

---

config/locales/blacklight.en.yml

Remove trailing colon from articles+ field labels

---

app/components/homepage_search_component.html.erb
app/components/masthead/layout_component.html.erb
app/components/masthead_search_component.rb
app/javascript/controllers/home_page_search_controller.js
app/views/articles/_home_page.html.erb
app/views/catalog/_home_page.html.erb
app/views/catalog/mastheads/_digital_collections.html.erb
app/views/catalog/mastheads/_government_documents.html.erb
app/views/catalog/mastheads/_sdr.html.erb
app/views/databases/_header.html.erb
app/views/shared/searchworks4/_search_navbar.html.erb

Persist the q parameter when toggling between different search modes (but don't persist it after searching)

---

app/components/search_result/document_gallery_component.html.erb

Current designs do not use this. We can add it back in later if Darcy includes it.
Before:
After:

Remove online label from document gallery component

---

app/assets/stylesheets/searchworks4/sul-icons.css

Fix dataset icon alignment on the record view page

---

app/components/access_panels/google_books_preview_component.html.erb
app/components/access_panels/google_books_preview_component.rb
app/javascript/controllers/google_cover_image_controller.js

Fixes #5684 
It looks like we dropped handling for full text links when we converted this to stimulus (compare
https://github.com/sul-dlss/SearchWorks/commit/cb7bf1c95ef7a5d68b07c218db8d796fcb0ebaa3#diff-0471cbe78c253480fe7ae77cb64ae426a35f42f4ea0e29e7235b9f1f0687d69fL127
+https://github.com/sul-dlss/SearchWorks/commit/cb7bf1c95ef7a5d68b07c218db8d796fcb0ebaa3#diff-878a83bbaa344f0733cd01319f912c65b36ecd41ae870c150c7238e0a6eebed9R107)
This PR restores that case, and moves all the link rendering into the javascript instead of messing around with class selectors 🤷

Handle rendering the google books link in javascript

---

app/models/marc_fields/linked_serials.rb
app/views/marc_fields/_linked_serials.html.erb
spec/models/marc_fields/linked_serials_spec.rb
spec/views/marc_fields/_linked_serials.html.erb_spec.rb

E.g. https://searchworks.stanford.edu/view/in00000290510 happens to wrap a little funny in SW4.
Per Darcy: 
> Seems like there's a space after the ( and before the ). If we remove the space, it wraps a bit better... just not sure if there's a good reason why the space is there.

Render linked serial links without injecting extra space.

---

app/assets/stylesheets/searchworks4/record.css
app/models/concerns/stacks_images.rb
app/views/catalog/_managed_purl_embed.html.erb
spec/components/record/marc_document_component_spec.rb
spec/features/purl_embed_spec.rb

closes #5644 
The gap at the top of the viewer will go away when we re-release sul-embed. I tried to get the dependency updates in but a rebase overwrote them and closed the pr and I can't figure out how to get them to run again with dependabot so I figure we wait until next week.

restyle digital collections purl part view

---

spec/features/merged_file_collection_spec.rb

There is no plan to reimplement the collection preview in the search results. (per Darcy)

Remove pending file collection search view spec

---

app/assets/stylesheets/searchworks4/blacklight.css
app/assets/stylesheets/searchworks4/search.css

These are not styles provided by blacklight, so it's a bit confusing to have them in the blacklight stylesheet

Move #search-navbar styles to search.css

---

app/components/access_panels/availability_component.html.erb

fix alignment on expand button

---

app/components/searchworks4/online_accordion_component.html.erb

Right now if you open the modal from a specific location the online modal looks like it is open
This fixes that issue.
The change looks big but it literally is just a space in front of collapsed

bug fix for online modal collapse

---

app/components/searchworks4/availability_accordion_component.html.erb
app/components/searchworks4/physical_availability_component.rb
app/components/searchworks4/search_result/collection_info_component.html.erb
app/views/collection_members/_file_collection_members.html.erb
app/views/collection_members/_image_collection_filmstrip.html.erb

(I'm surprised `pluralize` works with numbers and strings, but I guess they've thought of everything)

Display numbers with delimiters.

---

app/assets/stylesheets/searchworks4/search-results.css
app/components/searchworks4/physical_availability_component.html.erb
app/components/searchworks4/physical_availability_component.rb
app/javascript/controllers/availability_controller.js

(I'm assuming we'd also like the details to shrink smaller than the summary, but managing which borders are rounded starts to get a little hairy..)

Allow the summary header to shrink smaller than the details

---

app/components/citations/multiple_citations_component.html.erb
app/components/citations/multiple_citations_component.rb
app/components/searchworks4/citations/citation_component.html.erb
app/components/searchworks4/citations/citation_component.rb
spec/components/citations/multiple_citations_component_spec.rb

Additional bits for #5625
I don't love either of these. I think ideally the tool isn't even presented in these cases but this is better than displaying "Null" in places in the meantime. I'm also assuming there's no reason to provide "Copy" or "Export" in these situations.
Multiple citation tool with a single item with a null citation (which renders the single citation component). "No citation available for this record" is the default null citation text:
Multiple citation tool with a multiple items all having null citations:

Add better handling of null citation display

---

app/components/searchworks4/advanced_search_form_component.rb
app/controllers/catalog_controller.rb
spec/features/advanced_search_spec.rb

Use a separate label for date in advanced search; fixes #5729

---

app/components/articles/article_component.html.erb
app/javascript/article.js
spec/features/article_display_spec.rb

Style the articles+ full text button a little bit, and default to closed

---

app/components/main_container_component.html.erb
app/javascript/controllers/saved_list_controller.js

... so they carry over across turbo visits.

Mark toasts as data-turbo-permanent.

---

app/assets/stylesheets/searchworks4/chat.css
app/assets/stylesheets/searchworks4/typography.css
app/components/page_links_component.html.erb
app/components/toolbar_search_context_info_component.html.erb
app/javascript/controllers/course_reserves_controller.js
spec/features/accessibility_spec.rb
spec/support/accessibility_helpers.rb

Closes #5359
It was decided disable state text color should be `stanford-50-black` and excluded from our automated a11y checks.
Performing two a11y checks like this didn't add any significant additional time (< 250ms on my machine).
We had a duplicate advanced search test, I removed the pending one.

Update disabled state color

---

app/assets/stylesheets/searchworks4/record.css
app/components/access_panels/location_item_component.html.erb
app/components/access_panels/location_item_component.rb
app/components/record/bound_with_children_component.html.erb
app/components/record/bound_with_children_table_component.html.erb
app/components/searchworks4/availability_modal_location_component.html.erb
app/controllers/bound_with_children_controller.rb
app/javascript/controllers/show_more_button_controller.js
app/javascript/controllers/toast_message_listener_controller.js
app/views/bound_with_children/index.html.erb
app/views/bound_with_children/modal.html.erb
spec/components/record/bound_with_children_component_spec.rb
spec/features/bound_with_children_spec.rb

closes #5676 
Figma:
Pr:
Figma:
PR:
Figma:
PR:
Not in Figma:

update bound with children view for searchworks4

---

app/components/searchworks4/document_section_layout.html.erb
app/components/searchworks4/metadata_field_layout_component.html.erb

`DocumentSectionLayout` wraps a number of fields. I think we want `list-toggle` on the container for the specific field?

Move list-toggle down to the right level.

---

app/assets/stylesheets/searchworks4/bookmarks.css

Different browsers seem to want `cursor: pointer` on different elements?

Really get the bookmark label to have a cursor icon.

---

app/assets/stylesheets/searchworks4/gallery-view.css
app/assets/stylesheets/searchworks4/record.css

Full page browse nearby was not getting the border radius correctly before.
After:

Round the borders of all gallery documents

---

app/components/articles/eds_metadata_field_component.html.erb

... ideally, it'd happen sooner, but that's historically been hard or confusing (maybe there's some hope now with `EdsDocument`?)

Uniq the EDS metadata before display

---

app/components/main_container_component.html.erb

remove padding on flash messages if there are no flash messages

---

config/settings.yml

https://github.com/sul-dlss/global_alerts/pull/80 needs to be released and deployed everywhere before we can use the new attributes

Add the SW banner as a local alert until the global alert gems can catch up

---

app/javascript/controllers/browse_nearby_controller.js

On certain size screens breakout is being applied to the browse-nearby which is bad because it is going off the screen. There is never going to be an aside on smaller screens since we make the aside a drawer on smaller screens
Before:
After:

fix overflow for browse nearby

---

app/components/searchworks4/online_availability_component.html.erb

fix alignment for in single online link

---

app/views/shared/searchworks4/_search_navbar.html.erb

fix advanced search link not working

---

app/javascript/controllers/copy_text_controller.js

Right now when you click on the copy link in the cite modal the citation is copied in plain text. This change makes it rich text change.

allow italics/bold to be copied from cite

---

app/javascript/controllers/copy_text_controller.js

I was having trouble copy + pasting into some apps without a `text/plain` fallback?

Provide a plain-text clipboard fallback

---

app/components/record/item/marc/callnumber_browse_component.html.erb

We can somewhat infer this in GA, but I think we had specific tracking of this prior to the redesign.

Gather analytics for full page button in related items

---

spec/features/accessibility_spec.rb

It's way too annoying right now with how often it fails. Let's skip until we find a better way?

Skip accessibility test for more facets modal

---

app/controllers/articles_controller.rb
app/models/concerns/eds_links.rb
app/models/eds_document.rb
app/presenters/article_fulltext_link_presenter.rb
spec/models/concerns/eds_links_spec.rb

E.g. searching for "Nonholonomic Trajectory Planning of Postcapture Space" on -stage.

Also use EDS smart links for article fulltext

---

app/assets/stylesheets/searchworks4/record.css

fix tabbing on toc

---

app/views/shared/searchworks4/_top_navbar.html.erb

Maybe I'm just bad at clicking with my mouse, but I'm so tired of accidentally clicking somewhere in the red bar and going to the university homepage.

Make the Stanford header link inline.

---

app/components/record/marc_document_component.html.erb
app/models/solr_document.rb
spec/components/record/marc_document_component_spec.rb

Only databases index into the `db_az_subject` field, so the `is_a_database?` is redundant:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/folio_config.rb#L1460-L1473
Only `MetadataFieldLayoutComponent` with values render, so the additional condition isn't necessary

Convert db_az_subject to a document attribute.

---

app/components/searchworks4/record_summary_component.rb
app/models/eds_document.rb

Since we are getting data from three different "nodes" for eds_author (RecordInfo BibRecord BibRelationships) we can have repeats of the same data. This makes sure we aren't repeating author data to the user.
Before:
After:

uniq eds_authors

---

.github/workflows/ruby.yml
Gemfile
Gemfile.lock

This helps us find malformed html in our ERB files
See https://github.com/marcoroth/herb\?tab\=readme-ov-file
This is what allowed me to catch https://github.com/sul-dlss/SearchWorks/pull/5925 (among others), whereas #5879 does not catch that.

Do static analysis of erb files using herb

---

app/models/solr_document.rb
spec/models/solr_document_spec.rb

I don't think `id `can contain a `/` 🤷‍♂️

Remove SolrDocument#id override.

---

app/components/access_panels/collection_component.html.erb
app/helpers/collection_helper.rb
app/views/collection_members/_placeholder.html.erb
spec/helpers/collection_helper_spec.rb

This doesn't seem like a very useful helper method (and we used `link_to` just as much as `link_to_collection_members` 🤷‍♂️ )

Remove link_to_collection_members

---

app/components/searchworks4/physical_availability_component.html.erb

.. so it looks like:
instead of:

Have show/hide details left-aligned when it wraps

---

app/assets/stylesheets/searchworks4/search.css
app/views/shared/searchworks4/_search_navbar.html.erb

Search navbar portion of #5854
Search is slightly wider than in the designs because I don't think we'd like the select text to wrap.

Add the responsive search navbar designs

---

app/components/articles/document_component.html.erb
app/components/record/document_layout_component.html.erb
app/components/record/marc_document_component.html.erb
app/components/record/mods_document_component.html.erb
app/components/searchworks4/document_section_layout.rb

Fixes #6014 
Some ugliness to avoid rendering an empty embed container which makes it hard to have consistent spacing.

Adjust record view styles on smaller screens

---

app/controllers/catalog_controller.rb
config/solr_configs/schema.xml
config/solr_configs/solrconfig.xml
spec/features/callnum_search_spec.rb
spec/fixtures/solr_documents/1.yml

SearchWorks side of https://github.com/sul-dlss/searchworks_traject_indexer/issues/1620
The fields are already in solr and indexed via: https://github.com/sul-dlss/searchworks_traject_indexer/pull/1626. The impactful change here is the call number search config modification.

Search additional fields for call number search

---

app/helpers/record_helper.rb

Subject (not genre) portion of #5016
Given a mods record (e.g., `vd347dk2145`) with subject `Transportation > Bikes`
Before: subject search for "Transportation Bikes"
After: subject search for "Transportation" "Bikes"
Example flat structure from stanford-mods
```
record.subject_all_search
=>
["Design features",
"Black and White",
"デザインの特徴",
"モノクロ",
"Districts",
"Commercial district",
"Ethnic street",
"地区",
"商業地区",
"エスニック通り",
"Transportation",
"Bikes",
"交通手段",
"自転車",
"Transportation",
"Rickshaws",
"交通手段",
"人力車",
"Manchuria",
"Anto-ken"]
```

Quote each individual subject term in search link on mods records

---

app/components/access_panels/library_header_component.html.erb

E.g. this isn't great:
https://searchworks.stanford.edu/view/686777/availability

Don't save space for hours if we're not fetching them.

---

config/solr_configs/schema.xml

This splits the analyzers into index and query. It performs the same normalization for both, but treats the user query as a single term rather than exploding it into all the path components.

Stop using PathHierarchyTokenizer for call numbers at query time

---

config/solr_configs/schema.xml
spec/features/callnum_search_spec.rb
spec/fixtures/solr_documents/1.yml

This addresses the reported `82070 BOX 1` issue, where a call number search for `82070` didn't return the expected record.
I think consolidating the first two terms only when the first term is a common/often repeated alpha string that might dilute the search pool (e.g., `calif`, `zdvd`) would be an improvement.

Permit more single leading term matches for alphanum call numbers

---

app/assets/stylesheets/searchworks4/modal.css

Fixes #5993 
I didn't hide the full footer because the cite tool can also be viewed as a page, and it seems useful to keep the "Send" button in that case.

Hide the modal close button outside of the modal

---

app/views/bound_with_children/modal.html.erb
app/views/catalog/_grouped_citations.html.erb
app/views/catalog/_single_citation_with_modal.html.erb
app/views/catalog/availability_modal.html.erb
app/views/catalog/stackmap.html.erb

Part of #5953
We likely will not need https://github.com/sul-dlss/SearchWorks/pull/6009 if this goes in

Remove footer from modals that only have a close button

---

app/components/search_result/mini_bento/layout_component.html.erb

Fixes `Search results - mini-bento - side of focus ring gets cut off by count (number of matches)` portion of #5627

Use margin rather than padding for mini-bento result links

---

app/components/citations/multiple_citations_component.html.erb
app/components/searchworks4/citations/citation_component.html.erb
app/views/catalog/availability_modal.html.erb
app/views/catalog/email.html.erb
app/views/shared/_modal.html.erb
spec/features/bound_with_availability_spec.rb

Scrollable modal portion of https://github.com/sul-dlss/SearchWorks/issues/5953
This switches the order of the cite tools. @dbranchini suggested this as a way to stay within Bootstrap's default `modal-dialog-scrollable` behavior (The entire `modal-content` being scrollable). If we don't like how this looks, we definitely can implement the original design, it'll just take a bit more planning to work out the specific behaviors at smaller heights.

Switch to scrollable modals

---

app/javascript/controllers/copy_text_controller.js

Show the copied status in-place for the copy citation button for the citation modals.
Darcy voted for this when it looked like showing the toast above the dialog was hard. If somebody knows how to make that easy, we could do that 😄

Remove copy citation toast

---

app/components/searchworks4/record_summary_component.html.erb
app/components/searchworks4/record_summary_component.rb
spec/components/searchworks4/record_summary_component_spec.rb

I think this was a regression introduced in [#5947](https://github.com/sul-dlss/SearchWorks/pull/5947) (Blacklight only uses the thumbnail component configuration in the document component, the thumbnail presenter doesn't do anything with it at all)

Restore thumbnails to the record summary component.

---

app/assets/stylesheets/searchworks4/record.css
app/components/searchworks4/citations/citation_component.html.erb

Allow citation urls to break; fixes #6074

---

spec/features/blacklight_customizations/search_types_spec.rb

`click_link` is hitting the link in the footer

Use the Articles+ option in search types spec

---

app/models/json_results_document_presenter.rb
spec/models/json_results_document_presenter_spec.rb

Closes https://github.com/sul-dlss/sul-bento-app/issues/968 (or should - once the links are passed on through the JSON API request that bento uses)

passing along EzProxy as part of the links through the JSON API

---

app/components/access_panels/additional_info_component.html.erb
app/components/record/marc_document_component.html.erb
spec/components/access_panels/at_the_library_component_spec.rb
spec/components/record/marc_document_component_spec.rb

Move the finding aid link into the document header.

---

app/components/access_panels/at_the_library_component.html.erb
app/components/main_container_component.html.erb
app/components/searchworks4/physical_availability_component.html.erb
app/controllers/application_controller.rb
app/helpers/catalog_helper.rb
app/javascript/controllers/index.js
app/javascript/controllers/inline_turnstile_controller.js
app/views/catalog/_search_results.html.erb
app/views/catalog/availability_modal.html.erb
app/views/layouts/searchworks4.html.erb

without being disruptive and requiring a full page reload, prompt for turnstile before loading the availability turbo-frames.

Add some turnstile around availability lookups.
