Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/controllers/course_reserves_controller.rb, app/controllers/preview_controller.rb, app/controllers/selected_databases_controller.rb, app/views/browse/_index_header_default.html.erb, app/views/catalog/_index_brief.html.erb, app/views/catalog/_index_header_default.html.erb, app/views/catalog/_index_header_gallery.html.erb, app/views/catalog/record/_record_toolbar.html.erb, app/views/preview/_show_header_default.html.erb, spec/controllers/selected_databases_controller_spec.rb, spec/features/blacklight_customizations/emailing_records_spec.rb, spec/features/blacklight_customizations/facets_spec.rb
Built on top of @cbeer's work for 5.8.0.
=> Upgrade to Blacklight 5.8.2

app/views/catalog/_chat_librarian_sidebar.html.erb
=> Change text re: reference hours on zero results page.

Capfile, config/deploy.rb, config/schedule.rb
Also making schedule.rb a shared file so that different servers
can have different cron schedules w/o using rails_config.
=> Add Whenever/Capistrano integration so our cron jobs are written.

lib/constants.rb, spec/lib/holdings/callnumber_spec.rb
=> Allow ALPHANUM callnumbers to be browsable.

app/assets/javascripts/jquery.plug-google-content.js, spec/features/blacklight_customizations/record_metadata_spec.rb, spec/features/blacklight_customizations/results_document_spec.rb
* Refactored couple of long `$.each` loops
* Fixed failing tests
=> Updates to cover fix and failing tests

lib/constants.rb
=> Add temporary LIBRARY_INSTRUCTIONS for ART.

Gemfile, Gemfile.lock, app/controllers/login_controller.rb, app/models/user.rb, app/views/shared/_top_navbar.html.erb, config/initializers/devise.rb, config/routes.rb, spec/controllers/login_controller_spec.rb, spec/models/user_spec.rb, spec/views/shared/_top_navbar.html.erb_spec.rb
=> Implement devise-remote-users to integrate webauth and devise.

app/assets/javascripts/jquery.libraryh3lp.js, app/assets/javascripts/jquery.plug-google-content.js, app/helpers/xml_api_helper.rb, app/views/layouts/searchworks.html.erb
I think this is all of them.  Tested this out on a server w/ https and did not see any mixed-content errors.
=> Migrate referenced assets to use https.

app/assets/javascripts/jquery.live-lookup.js, app/helpers/request_link_helper.rb, app/views/catalog/_index_location.html.erb, app/views/catalog/access_panels/_location.html.erb, spec/helpers/request_link_helper_spec.rb
=> Add rel='nofollow' to request links.

app/assets/stylesheets/modules/results-documents.css.scss, app/assets/stylesheets/modules/sul-icons.css.scss, app/assets/stylesheets/sul-variables.css.scss, app/controllers/catalog_controller.rb, app/helpers/catalog_helper.rb, app/views/bookmarks/index.html.erb, app/views/catalog/_index.html.erb, app/views/selected_databases/index.html.erb, config/solr_configs/schema.xml, spec/features/rss_feed_spec.rb, spec/fixtures/solr_documents/44.yml, spec/fixtures/solr_documents/46.yml, spec/helpers/catalog_helper_spec.rb
=> Add feed icon to atom feed for results sorted by date_cataloged

lib/holdings/callnumber.rb, spec/lib/holdings/callnumber_spec.rb
=> Allow call number browse for internet resources

app/assets/stylesheets/modules/bookplates.css.scss, app/views/catalog/record/_marc_metadata_sections.html.erb
=> Small bookplates style tweak

app/views/catalog/mastheads/_bookplate_fund.html.erb
Closes #1107 (in conjunction with #1108).
=> Update the text on the bookplate masthead.

app/views/shared/_su_footer.html.erb, app/views/shared/_top_navbar.html.erb
=> Add alt attributes for SUL icons in header and footer.

app/views/catalog/record/_marc_bibliographic.html.erb
=> Parse ISBN from MARC instead of getting from the index.

app/assets/stylesheets/modules/breadcrumb.css.scss
=> Allow breadcrumb values to be selectable by the user.

app/views/catalog/_index_location.html.erb, app/views/catalog/access_panels/_location.html.erb, lib/holdings/mhld.rb, spec/lib/holdings/mhld_spec.rb
=> Escape HTML Entities in MHLD Data

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/helpers/catalog_helper.rb, app/models/citation.rb, app/models/concerns/citable.rb, app/models/solr_document.rb, app/views/catalog/_citation.html.erb, app/views/catalog/_grouped_citations.html.erb, app/views/catalog/_single_citation.html.erb, app/views/catalog/record/_record_toolbar.html.erb, config/settings.yml, spec/features/blacklight_customizations/record_toolbar_spec.rb, spec/features/bookmarking_items_spec.rb, spec/features/responsive/record_toolbar_responsive_spec.rb, spec/features/responsive/results_toolbar_spec.rb, spec/features/responsive/results_view_spec.rb, spec/fixtures/mods_records/mods_fixtures.rb, spec/helpers/catalog_helper_spec.rb, spec/models/citation_spec.rb, spec/models/concerns/citable_spec.rb, spec/models/solr_document_spec.rb, spec/support/stub_oclc_response.rb
Closes #1118 
Closes #336 <-- Preferred Citations From MODS
=> Replace Blacklight Citations w/ OCLC Citations

app/assets/stylesheets/modules/access-panel-library-locations.scss, app/assets/stylesheets/modules/access-panel.scss
=> Fix minor css bug in library panel headings

app/helpers/facets_helper.rb, app/views/catalog/_home_page.html.erb, spec/features/responsive/home_page_responsive_spec.rb
=> add language facet to home page; collapse resource facet by default

app/helpers/application_helper.rb, app/views/catalog/_zero_results.html.erb, config/locales/searchworks.en.yml, spec/features/zero_results_spec.rb, spec/helpers/application_helper_spec.rb
=> change message when no search results from advanced search only

app/controllers/concerns/callnumber_search.rb, spec/features/callnum_search_spec.rb, spec/fixtures/solr_documents/1.yml
=> fix call number search bug when going to search result

app/models/marc_fields/organization_and_arrangement.rb, app/models/solr_document.rb, app/views/catalog/record/_marc_contents_summary.html.erb, config/locales/searchworks.en.yml, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/models/marc_fields/organization_and_arrangmenet_spec.rb, spec/models/solr_document_spec.rb, spec/views/catalog/record/_marc_contents_summary.html.erb_spec.rb
=> Add MARC 351 to the Contents/Summary section.

app/assets/javascripts/jquery.accordion-section.js, app/views/catalog/_accordion_section_course_reserves.html.erb, app/views/catalog/_accordion_section_library.html.erb, app/views/catalog/_accordion_section_online.html.erb, app/views/catalog/_accordion_section_summary.html.erb, spec/features/mhld_spec.rb, spec/views/catalog/_accordion_section_course_reserves.html.erb_spec.rb, spec/views/catalog/_accordion_section_library.html.erb_spec.rb, spec/views/catalog/_accordion_section_online.html.erb_spec.rb, spec/views/catalog/_accordion_section_summary.html.erb_spec.rb, spec/views/preview/_show_mods.html.erb_spec.rb
…dded aria labels with toggling of snippet and section body. The former link in now a button, and is tabbable and togglable by means of the space bar or enter key. There is still some strange animation behaviour from bootstrap.
=> Fixes #463 and #1201. 

Gemfile, Gemfile.lock, app/views/catalog/record/_mods_upper_metadata_items.html.erb
Adds newly available Extent, Form, and Geo MODS fields.
Closes #1180 
Closes #1069
=> Update to ModsDisplay 0.4.0.

app/assets/javascripts/jquery.live-lookup.js, lib/constants.rb, lib/holdings/noncirc.rb, lib/holdings/status.rb, lib/holdings/unavailable.rb, spec/lib/holdings/noncirc_spec.rb, spec/lib/holdings/status_spec.rb, spec/lib/holdings/unavailable_spec.rb
Closes #1179 via fedfe4c
Closes #1048 via 317d958
Closes #1117 via f4cf8b5
---
---
=> Few related fixes for availability

app/helpers/marc_helper.rb, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/helpers/marc_helper_spec.rb
=> Do not render blacklisted subfields in MARC contributor data.

Gemfile, Gemfile.lock
2.2.1 has an XSS vulnerability
=> Relax version restriction on and update jquery-datatables-rails.

app/assets/stylesheets/modules/managed_purl_panel.scss
=> Add a fixed-width and scroll-bar to the many-purls for one-ckey panel.

lib/constants.rb
This can be merged in whenever.  Will deploy the morning of the 25th.
=> Update library instruction text for Rumsey public opening.

lib/constants.rb
=> Remove HAS-DIGIT from the NONCIRC locations list.

lib/constants.rb
=> Add new location EYLESAISLE.

app/views/catalog/_home_page.html.erb, spec/features/home_page_spec.rb
=> Add a Looking for ideas? block to the home page with a link to Yewno.

Gemfile, Gemfile.lock, config/initializers/okcomputer.rb, config/locales/okcomputer_en.yml, spec/features/purl_embed_spec.rb, spec/features/status_spec.rb
Ta da!
closes sul-dlss/sul-requests#549
=> add app monitoring at /status w okcomputer

app/helpers/request_link_helper.rb, app/views/catalog/_index_location.html.erb, app/views/catalog/access_panels/_location.html.erb, lib/constants.rb, spec/helpers/request_link_helper_spec.rb
=> Update request link text for on-site access libraries.

lib/constants.rb
This will get loan desk behavior by virtue of the location having a "-LOAN" suffix.
Closes #1280
=> Add ARS-LOAN location.

lib/constants.rb
=> Add MEDIA-MTXT as a page library.

app/views/shared/_su_footer.html.erb
This now matches the [link in the header](https://github.com/sul-dlss/SearchWorks/blob/master/app/views/shared/_top_navbar.html.erb#L18).
=> Fix My Account link in footer

lib/constants.rb
=> Add new Rumsey location MP-CASE-RF

lib/constants.rb
Thanks for the catch @shelleydoljack
=> Fix typo in location key for DSPLAY-1ST

app/models/concerns/index_links.rb, app/models/concerns/marc_links.rb, lib/links.rb, spec/fixtures/marc_records/marc_856_fixtures.rb, spec/fixtures/solr_documents/7626894.yml, spec/models/concerns/index_links_spec.rb
=> Update the proxy service URL to be "stanford.idm.oclc.org"

app/helpers/marc_helper.rb, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/helpers/marc_helper_spec.rb
=> Change linking/display behavior for $i subfield

app/models/concerns/marc_metadata.rb, app/models/marc_fields/physical_medium.rb, app/views/catalog/record/_marc_bibliographic.html.erb, config/locales/searchworks.en.yml, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/models/marc_fields/physical_medium_spec.rb
This PR fixes #1298 by creating a new MarcField class called PhysicalMedium.
=> add PhysicalMedium MarcField class

app/assets/stylesheets/blacklight.scss
Results from `rails generate blacklight:marc:install`. In particular, please review the additions it made to SolrDocument.
=> run blacklight:marc:install rails generator for blacklight-marc 6.x

app/assets/stylesheets/modules/thumbnail.scss
=> float-right for preview document-thumbnails

app/controllers/catalog_controller.rb
(cherry-picked from the blacklight6x branch)
=> Ensure the advanced search form sets the facet limits to -1 (unlimited)

Capfile
See http://docs.honeybadger.io/ruby/getting-started/tracking-deployments.html
=> add honeybadger for deployment tracking

config/deploy/preview_articles.rb
Additional tasks (that don't need to hold-up this PR).
* Configure EBSCO API details (this can prob. just be in the `production.local.yml` on the server since this is just for temp. usage.  We can commit the real details to `shared_configs` for the appropriate environments.
* Complete ruby version upgrade amongst all preview/standbox nodes.
=> Add a deploy environment for article search.

spec/features/blacklight_customizations/emailing_records_spec.rb, spec/fixtures/solr_documents/10.yml
@camillevilla let me know if these fixes those failing tests you were seeing too.  You'll need to re-index your test fixtures, just a heads up.
=> Fix local broken tests

app/views/catalog/_index_location.html.erb, app/views/catalog/access_panels/_location.html.erb
=> Update request button styles

Gemfile.lock, app/controllers/article_controller.rb, app/views/article/index.html.erb
Closes #1398
I have built this on top of #1405 as I need some of the changes there.  Will update the base as appropriate once #1405 gets in.
Consideration for pulling into a separate ticket: More facet modal
A few notes on behavior (not sure if these things are configureable on the ebsco side):
* The facets appear to be `OR` not `AND` like our catalog search facets are
* Some facets appear to not return the selected value in the facet response (e.g. Language), so the only way to remove the facet would be by the breadcrumb.
* Some facets appear to not be returned at all once a value is selected (e.g. Publisher), which might just be a symptom of the issue above.
=> Configure and render facets.

Gemfile.lock, app/controllers/article_controller.rb, spec/features/article_home_page_spec.rb
=> Add fielded search

app/controllers/article_controller.rb
=> Add the search limiters facet configuration.

app/controllers/article_controller.rb
Per @jvine after analysis from #1441
=> Add some additional metadata to the article record view.

spec/features/article_searching_spec.rb, spec/support/stub_article_service.rb
@drh-stanford && @camillevilla interested on your input on this approach.
=> Add a helper for stubbing article search responses

.travis.yml, spec/features/blacklight_customizations/emailing_records_spec.rb, spec/spec_helper.rb
Closes #1402 and updates Travis version to 2.1.1
=> Update PhantomJS version on Travis

app/assets/stylesheets/modules/search-bar.scss, app/assets/stylesheets/modules/subnavbar.scss, app/views/catalog/_search_form.html.erb, app/views/shared/_search_bar.html.erb, app/views/shared/_search_subnavbar.html.erb, spec/features/course_reserves_browse_spec.rb, spec/features/responsive/search_subnavbar_responsive_spec.rb, spec/features/responsive/subnav_responsive_spec.rb
=> responsive behavior for redesigned banner

app/controllers/article_controller.rb, app/views/article/_index_default.html.erb, spec/features/article_searching_spec.rb
This PR fixes #1462. Note that subjects are linked too.
=> Use composed title in the search results

app/views/article/_show_default.html.erb, config/locales/searchworks.en.yml, spec/features/article_display_spec.rb
=> Add the sidenav mini-map for article records.

app/controllers/article_controller.rb
=> add Date facet to Article Search

app/views/advanced/_advanced_search_form.html.erb, app/views/advanced/index.html.erb, app/views/article/_home_page.html.erb, app/views/article/_index.html.erb, app/views/article/show.html.erb, app/views/bookmarks/index.html.erb, app/views/catalog/_index.html.erb, app/views/catalog/mastheads/_sdr.html.erb, app/views/catalog/show.html.erb, app/views/course_reserves/index.html.erb, app/views/layouts/searchworks.html.erb, app/views/selected_databases/index.html.erb, app/views/shared/_print_header.html.erb, app/views/shared/_su_footer.html.erb, app/views/shared/_top_navbar.html.erb, config/locales/blacklight.en.yml, config/locales/searchworks.en.yml, lib/constants.rb, spec/features/access_points/collection_spec.rb, spec/features/access_points/course_reserve_spec.rb, spec/features/access_points/databases_spec.rb, spec/features/access_points/dissertation_theses_spec.rb, spec/features/access_points/sdr_spec.rb, spec/features/access_points/selected_databases_spec.rb, spec/features/advanced_search_spec.rb, spec/features/article_home_page_spec.rb, spec/features/article_searching_spec.rb, spec/features/home_page_spec.rb, spec/features/results_page_spec.rb, spec/features/show_page_spec.rb
=> update page titles to match new branding of catalog vs articles

app/controllers/article_controller.rb
=> Change Composed Title label to Source

app/controllers/article_controller.rb, app/helpers/article_helper.rb, spec/helpers/article_helper_spec.rb
=> Link authors on show page, and strip relator terms on index page

app/controllers/article_controller.rb, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/catalog/_search_targets_widget.html.erb, spec/helpers/application_helper_spec.rb
This PR is connected to #1489.
(there's a ~5 sec delay in the video for the searching)
=> pass simple queries and fielded queries between article/catalog searches

app/views/article/_index_default.html.erb, spec/features/article_searching_spec.rb
=> switch from UL to DL for subjects in search results

app/helpers/article_helper.rb, app/models/article_search_builder.rb, spec/helpers/article_helper_spec.rb
This PR fixes #1459 and depends on #1520.
=> use new EDS descriptor search_field option

app/controllers/article_controller.rb, app/models/eds/repository.rb, config/initializers/eds.rb
This PR relocates the guest mode toggle to the initializer (and not in the Settings).
=> put toggle for guest mode into the initializer

config/routes.rb, spec/routing/article_routes_spec.rb
=> permit "+" characters in EDS identifiers

app/views/article/_research_starters.html.erb
This PR fixes #1535. It's a typo (that took forever to find :)
=> fix bug with first click causing show/hide behavior

lib/constants.rb, spec/lib/holdings/callnumber_spec.rb
=> Add support for EAL StackMap links.

app/assets/stylesheets/modules/research-starter.scss, app/views/article/_research_starters.html.erb, app/views/article/_show_header_reference.html.erb
=> update Research starter term to Topic overview

app/controllers/article_controller.rb, spec/models/article_search_builder_spec.rb
=> bump default page size from 10 to 20

app/assets/stylesheets/modules/facets.scss, app/controllers/articles_controller.rb
=> Comment out date facet and hide source type facet counts (via css).

app/assets/stylesheets/modules/facets.scss
=> Temporarily restore facet counts

config/application.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/1624
Fixes https://github.com/sul-dlss/SearchWorks/issues/1625
=> Handle missing record exceptions with the 404 page

Gemfile, Gemfile.lock, config/application.rb
Closes #1628
Sorry for the redundant PR!
=> add utf-8 sanitization

Gemfile, Gemfile.lock, app/assets/javascripts/eds_range_limit.js, app/assets/stylesheets/modules/eds_range_slider.scss, app/assets/stylesheets/searchworks.scss, app/controllers/articles_controller.rb, app/models/eds/date_range_parser.rb, app/views/articles/_range_limit_panel.html.erb, config/initializers/blacklight_range_limit.rb, spec/features/date_range_spec.rb, spec/models/eds/date_range_parser_spec.rb, spec/support/stub_article_service.rb
Closes #1609 
This PR adds in the configuration + a lightweight slider plugin for using article search date faceting
=> Adds date range & slider for article search [BONUS FEATURE: Catalog stylin' update]

app/assets/javascripts/facet-options-checkboxes.js, app/assets/stylesheets/modules/facet-options.scss, app/assets/stylesheets/searchworks.scss, app/controllers/articles_controller.rb, app/helpers/article_helper.rb, app/models/eds/repository.rb, app/models/eds/session.rb, app/presenters/facet_options_presenter.rb, app/views/articles/_facet_options.html.erb, app/views/catalog/_facet_options.html.erb, app/views/catalog/_facets.html.erb, app/views/catalog/_search_form.html.erb, config/locales/searchworks.en.yml, spec/controllers/article_controller_spec.rb, spec/features/options_facet_spec.rb, spec/presenters/facet_options_presenter_spec.rb, spec/support/stub_article_service.rb, spec/views/catalog/_search_form.html.erb_spec.rb
=> Make EDS Limiters a "checkbox" facet option

app/assets/javascripts/update-hidden-inputs-by-checkbox.js, app/assets/stylesheets/modules/facet-options.scss, app/assets/stylesheets/modules/home-page.scss, app/views/articles/_facet_options.html.erb, app/views/articles/_home_page.html.erb, app/views/catalog/_search_form.html.erb, config/locales/searchworks.en.yml, spec/features/article_home_page_spec.rb, spec/support/stub_article_service.rb
=> Add EDS limiters to the Search settings section on the home page.

app/assets/stylesheets/modules/home-page.scss, app/views/articles/_home_page.html.erb, app/views/shared/_home_page_bento.html.erb
Closes #1683 
CLoses #1686 
For previous, see #1683
=> apply classes/containers/rows consistently for home page spacing

app/assets/stylesheets/modules/article.scss
=> hide article search icons

app/assets/stylesheets/modules/article.scss
=> Hide more doc type icons

config/settings.yml
This PR fixes #1766 as we're seeing that the 5 sec timeout is causing exceptions.
=> bump the open connect timeout from 5 to 10 secs

app/views/shared/_home_page_bento.html.erb
=> add an and

app/assets/stylesheets/modules/home-page.scss, app/views/shared/_home_page_bento.html.erb, spec/views/shared/_home_page_bento.html.erb_spec.rb
=> use h1/h3 for bento home pages

app/views/articles/_home_page.html.erb
=> Add a referrer param to the login link on the articles home page.

app/views/catalog/_alternate_catalog.html.erb, app/views/catalog/_index.html.erb, spec/features/alternate_catalog_spec.rb, spec/views/catalog/_alternate_catalog.html.erb_spec.rb
=> Make sure that mini-bento article only includes direct access facet

app/views/articles/_research_starters.html.erb
=> Use link_to_document instead of link_to for research starters.

app/views/articles/_home_page.html.erb
=> update articles homepage banner message

Gemfile.lock, app/models/eds/session.rb
=> Update ebsco-eds gem.

app/helpers/request_link_helper.rb, app/models/hoover_open_url_request.rb, app/views/catalog/_index_location.html.erb, config/locales/searchworks.en.yml, config/settings.yml, lib/constants.rb, spec/features/request_link_spec.rb, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/fixtures/solr_documents/56.yml, spec/helpers/request_link_helper_spec.rb, spec/models/hoover_open_url_requst_spec.rb
Closes #1372
Closes #1636 
Closes #1820
=> Change request links for Hoover Library Links to use Aeon/OpenURL

config/schedule.rb
This PR closes #1814 
cc: @eefahy
=> clear EDS cache biweekly

config/locales/searchworks.en.yml, config/settings.yml
Looking to get this merged on the final day folks are around to do so.  I'll push this out Friday before the closure (and remove it when we return on the 8th).
=> Update the winter closure notification and turn it on.

app/views/layouts/searchworks.html.erb
Reverts sul-dlss/SearchWorks#1830
=> Revert "Add a flash notice about the symphony outage on Dec. 28, 2017."

config/deploy/preview_new_index.rb
@jkeck Please merge when you get the chance. Thank you.
=> Deploy config for testing new index.

lib/constants.rb
=> Add new VROOMAN2 location.

app/views/catalog/_image_collection_filmstrip.html.erb
=> Use the data-thumb-height attribute properly

.solr_wrapper, Gemfile.lock, config/initializers/okcomputer.rb
In anticipation of an sul-solr impending solr upgrade.
=> Update .solr_wrapper.yml to use 7.4.0

app/views/catalog/mastheads/_bookplate_fund.html.erb, spec/features/bookplates_spec.rb
=> Replace bookplates masthead text; fixes #1878

app/controllers/catalog_controller.rb, app/controllers/concerns/stanford_work_facet.rb, app/views/catalog/_home_page.html.erb, app/views/catalog/mastheads/_dissertation_theses.html.erb, spec/features/access_points/dissertation_theses_spec.rb, spec/features/alternate_catalog_spec.rb, spec/features/facets_spec.rb, spec/fixtures/solr_documents/1343750.yml
=> Add Stanford work locations facet

app/helpers/marc_helper.rb, lib/constants.rb
=> Exclude all MARC subfield 1s

app/controllers/concerns/location_facet.rb, spec/features/facets_spec.rb, spec/fixtures/solr_documents/58.yml
Fixes #1635 
Fixes #1880
Need to wait for production index to be updated with this data before merging and deploying.
=> Adds curriculum collection to the location facet.

app/views/shared/_email_form.html.erb
=> Remove author from the email form

CHANGELOG.md
(accidentally kept the original Keep-A-Changelog org in the URL)
=> Update sul-dlss URL changelog

app/views/layouts/searchworks.html.erb
=> sets up preloading of stylesheets for javascript based browsers

app/models/marc_fields/linked_serials.rb
=> Suppress display of all 776 tags

lib/constants.rb
=> Exclude subfield 2s from all tags

CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/articles_controller.rb, app/controllers/catalog_controller.rb, app/controllers/concerns/email_validation.rb, app/controllers/feedback_forms_controller.rb, app/views/catalog/_email_form.html.erb, app/views/shared/_email_form.html.erb, app/views/shared/feedback_forms/_form_fields.html.erb, config/initializers/recaptcha.rb, config/locales/searchworks.en.yml, config/settings.yml, spec/controllers/catalog_controller_spec.rb, spec/controllers/feedback_forms_controller_spec.rb, spec/features/blacklight_customizations/emailing_records_spec.rb, spec/helpers/feedback_form_helper_spec.rb
Closes #1942 
See sul-dlss/shared_configs#724
=> Implement reCAPTCHA for anonymous feedback and record emails

.travis.yml
=> test on travis w/ current prod Ruby version + future

CHANGELOG.md, app/assets/javascripts/jquery.stackmap.js
=> hide attribution control for stackmap map

CHANGELOG.md, app/assets/javascripts/jquery.side-nav-minimap.js, app/views/catalog/record/_marc_metadata_sections.html.erb
Closes #1961 
Example record 9257713
=> Fixes issue where side-nav minimap would raise error and stop further javascript execution

CHANGELOG.md, app/views/layouts/searchworks.html.erb
=> Revert preload

CHANGELOG.md, app/assets/stylesheets/modules/access-panel-library-locations.scss, app/models/marc_fields/bound_with_note.rb, app/views/catalog/_index_location.html.erb, app/views/catalog/access_panels/_location.html.erb, app/views/marc_fields/_bound_with_note.html.erb, lib/constants.rb, lib/holdings/callnumber.rb, lib/holdings/library.rb, lib/holdings/location.rb, spec/models/marc_fields/bound_with_note_spec.rb, spec/views/catalog/_index_location.html.erb_spec.rb, spec/views/catalog/access_panels/_location.html.erb_spec.rb
Closes #1339 
_Because I like the incorrect book cover_
=> Changes to bound-with notes in availability display

CHANGELOG.md, app/views/shared/_search_navbar_services_menu.html.erb, app/views/shared/_su_footer.html.erb
=> add sw status links to searchworks

app/views/catalog/_show_marc.html.erb, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/views/catalog/_show_marc.html.erb_spec.rb
=> Add the upper metadata items to records with managed purls

app/models/marc_fields/marc_field_wrapper.rb, spec/models/marc_fields/marc_field_wrapper_spec.rb
=> Fix equality for MarcFieldWrappers

app/controllers/catalog_controller.rb, app/models/concerns/schema_dot_org.rb, app/models/solr_document.rb, app/views/catalog/_schema_dot_org_default.html.erb, spec/features/blacklight_customizations/record_metadata_spec.rb, spec/models/concerns/schema_dot_org_spec.rb
=> Add some basic schema.org JSON-LD markup to the page

.travis.yml
=> remove ruby 2.3 build

spec/fixtures/marc_records/marc_856_fixtures.rb
currently showing errored images in dev
=> update managed purl fixture to reference correct files

CHANGELOG.md, Gemfile.lock
=> Update SearchWorks to Blacklight v6.16.0

app/helpers/marc_helper.rb, app/models/concerns/marc_subjects.rb, app/models/marc_fields/subjects.rb, app/models/solr_document.rb, app/views/catalog/record/_marc_subjects.html.erb, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/helpers/marc_helper_spec.rb
=> Display vernacular subjects

app/models/concerns/marc_links.rb, app/views/catalog/_managed_purl_embed.html.erb, lib/links.rb, spec/fixtures/marc_records/marc_856_fixtures.rb, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/lib/links_spec.rb, spec/models/concerns/marc_links_spec.rb, spec/views/catalog/_show_marc.html.erb_spec.rb
=>  Sort managed purls by the sort key or part label

app/models/concerns/schema_dot_org.rb, spec/models/concerns/schema_dot_org_spec.rb
Fixes #2040 adds thesis type and sets equipment to a thing
Also fixes #2064
=> additional types added for schema mapping (thesis, thing)

CHANGELOG.md, Gemfile, Gemfile.lock, app/models/citation.rb, app/models/eds/session.rb, app/views/catalog/_single_citation.html.erb, app/views/shared/record/_record_toolbar.html.erb, config/settings.yml, spec/models/citation_spec.rb
=> Allow for citations from EDS to populate the "Cite" modal

CHANGELOG.md
=> Update changelog for 3.3.6 release.

public/404.html
=> update 404 page, fixes #2079

config/solr_configs/schema.xml
Related to #2043 and #2042. Might be good to get this in place so neither relay on the same change
=> update schema to work with forthcoming marc/mods no parsing changes

app/views/catalog/_index_brief.html.erb
Looks like I missed removing the old one in #2053
=> Remove duplicate online label

spec/views/catalog/record/_mods_metadata_sections.html.erb_spec.rb
=> Remove debugging puts from spec

app/views/catalog/record/_record_metadata_default.html.erb
=> Remove redundant description h2

CHANGELOG.md, app/controllers/articles_controller.rb, spec/controllers/article_controller_spec.rb
=> Raise a NotFound error when the EDS API returns a BadRequest error

app/views/catalog/access_panels/_online.html.erb
=> Add the Online h2 to the online access panel.

CHANGELOG.md
=> Update the CHANGELOG for the 3.3.8 release.

app/controllers/catalog_controller.rb, lib/holdings/callnumber.rb, spec/controllers/catalog_controller_spec.rb, spec/lib/holdings/callnumber_spec.rb
This reverts commit c0f6ddda39764334394e60ad88bb2c3f13af2389
Realized I put this in the wrong place. 🤦‍♂️
=> Move isbn in availability to top level response.

app/assets/stylesheets/modules/facets.scss
Closes #2159 
This PR restyles hierarchical facets (e.g. Callnumber) and makes it easier to see number of results per sub-facet.
=> Restyle hierarchical facets

app/assets/javascripts/analytics.js
Part of #2117 
I think getting this partially in is useful. I just don't want the ticket to keep lingering and not being able to ship this.
The remaining items may need more analysis. I've confirmed all of the events added today in sw-stage GA.
=> Adds more custom analytics events

app/assets/stylesheets/modules/record-metadata-section.scss
=> Fixes #2132 managed purl alignment issue

app/assets/javascripts/feedback_form.js, app/models/feedback_mailer_parser.rb, app/views/feedback_mailer/_shared_closing.text.erb, app/views/shared/feedback_forms/_form_fields.html.erb, spec/mailers/feedback_mailer_spec.rb, spec/models/feedback_mailer_parser_spec.rb
=> adds in last search (from show page) fixes #1967

.travis.yml, CHANGELOG.md, Gemfile, Gemfile.lock, spec/features/article_display_spec.rb, spec/features/article_home_page_spec.rb, spec/features/article_searching_spec.rb, spec/features/backend_lookup_spec.rb, spec/features/blacklight_customizations/emailing_records_spec.rb, spec/features/connection_form_spec.rb, spec/features/course_reserves_browse_spec.rb, spec/features/image_collection_spec.rb, spec/features/merged_file_collection_spec.rb, spec/features/merged_image_collections_spec.rb, spec/features/responsive/home_page_responsive_spec.rb, spec/features/responsive/record_toolbar_responsive_spec.rb, spec/features/responsive/results_toolbar_spec.rb, spec/features/responsive/results_view_spec.rb, spec/features/responsive/search_subnavbar_responsive_spec.rb, spec/features/responsive/search_toolbar_responsive_spec.rb, spec/features/skip_to_nav_spec.rb, spec/features/tabbed_selections_spec.rb, spec/spec_helper.rb
=> Swap out poltergeist for chromedriver 

app/assets/javascripts/analytics.js
=> Add more analytics events (browse-nearby, stacks map, cite link)

lib/holdings/location.rb
=> Remove some unnecessary method_missing code; Fixes #2227

app/views/articles/_home_page.html.erb
=> Remove articles+ beta banner

app/assets/javascripts/application.js, app/views/layouts/searchworks.html.erb, config/settings.yml, vendor/assets/javascripts/honeybadger.js
=> Add Honeybadger js error reporting

app/assets/stylesheets/modules/feedback-form.scss, app/assets/stylesheets/modules/global-alert.scss, app/assets/stylesheets/searchworks.scss, app/views/layouts/searchworks.html.erb, app/views/shared/feedback_forms/_connection_form.html.erb, app/views/shared/feedback_forms/_form.html.erb, config/locales/searchworks.en.yml, config/settings.yml
=> Update outage notice and styling.

Gemfile, Gemfile.lock
=> Unpin bootstrap

.travis.yml
=> Test with ruby 2.6

lib/constants.rb
=> Add a translation for PAGE-IRON2

app/assets/javascripts/wof.js, app/assets/stylesheets/modules/show_page.scss, app/helpers/knowledge_panel_helper.rb, app/models/concerns/wof_concern.rb, app/models/solr_document.rb, app/views/catalog/_index.html.erb, app/views/catalog/_wof_knowledge_panel.html.erb, config/deploy/preview_articles.rb, config/initializers/wof.rb, lib/tasks/wof.rake, spec/fixtures/solr_documents/1.yml
SearchWorks
Make sure your root project directory has a wof_lookup.json file.
curl -o wof_lookup.json https://gist.githubusercontent.com/mejackreed/d217e5f7a6b35bf7c964cc8089fb0e4a/raw/0cb526a96c099fdc4be5aa15688830104a32c29b/wof_lookup.json
lib/tasks/wof.rake - rake tasks to create the data needed
=> [WIP] Hacky start to think about integration of Who's on First data in

app/controllers/catalog_controller.rb, config/settings.yml
=> Add a boolean in Settings to disable crawlers (false by default).

lib/constants.rb
=> Add two new locations (for Rumsey)

lib/constants.rb
=> Add RWC-LOAN location translation.

app/assets/stylesheets/modules/sul-footer.scss, app/assets/stylesheets/sul-variables.scss, app/views/layouts/searchworks.html.erb, app/views/shared/_su_footer.html.erb
Part of maintenance work cycle. This is a bit different in Bootstrap 3 via 4. 
I tried to adopt the approach in https://github.com/sul-dlss/mylibrary/pull/271/files so that we could see the differences.
=> Update SU footer

app/assets/stylesheets/modules/sul-footer.scss
=> Fix SU footer horizontal overflow

lib/constants.rb
=> Update location name of LAW-CAREERS to include the location name.

config/deploy/preview_articles.rb
(also make sure the Whose On First file is linked)
=> Explicitly set the branch for the "preview articles" env

app/models/marc_field.rb
Addresses part of https://github.com/sul-dlss/SearchWorks/issues/2365, at least.
=> Refactor MarcFields vernacular matching to make it impossible to create an infinite loop

app/views/layouts/searchworks.html.erb, config/locales/searchworks.en.yml
=> Update winter closure text & link.

app/assets/javascripts/exhibitPanel.js
=> Adds a custom event for when exhibit links are clicked fixes #2381

app/assets/javascripts/exhibitPanel.js, app/assets/stylesheets/modules/access-panel-exhibit.scss, spec/features/access_panels/exhibit_spec.rb
=> Update exhibit toggle link to a button.

app/controllers/concerns/all_caps_params.rb, spec/features/all_caps_params_spec.rb
=> Don't pass through nil queries for case checking.

config/locales/searchworks.en.yml
This text is likely to be updated shortly and possibly in the future as development occur. 
shared_configs PR to follow to enable
=> Update the global alert message for a COVID-19 update.

config/locales/searchworks.en.yml
=> Update global alert text.

config/locales/searchworks.en.yml
=> Update current to valid in global alert text

config/locales/searchworks.en.yml
=> Update global alert text w/ messaging about request service.

config/locales/searchworks.en.yml
=> Update covid banner

Gemfile, Gemfile.lock
=> Update recaptcha dependency

config/locales/searchworks.en.yml
=> Remove outage notice (all is clear w/ SFX)

app/controllers/concerns/location_facet.rb
=> Wrap the building_facet in an array to handle invalid params better.

app/views/shared/_search_navbar_services_menu.html.erb
=> Update purchase link

lib/holdings/callnumber.rb, lib/holdings/library.rb, spec/lib/holdings/callnumber_spec.rb, spec/lib/holdings/library_spec.rb
=> Exclude E-RESV at the holding level

config/locales/searchworks.en.yml
=> Updating global alert wording.

lib/access_panels/temporary_access.rb
Requires https://github.com/sul-dlss/sul-solr-configs/pull/220
=> Use ht_* fields instead of the full serialized data

app/assets/javascripts/analytics.js
=> Adds a custom event for access to HathiTrust content

app/assets/javascripts/analytics.js
=> Fix typo for event type for IIIF click

config/locales/searchworks.en.yml
=> Update global alert to indicate re-opening for research

app/models/concerns/display_type.rb, app/models/concerns/eds_links.rb, app/models/concerns/series_linkable.rb, app/models/marc_fields/instrumentation.rb, app/models/marc_fields/organization_and_arrangement.rb, config/solr_configs/synonyms.txt, lib/constants.rb, lib/holdings/callnumber.rb, spec/helpers/marc_helper_spec.rb, spec/lib/holdings/callnumber_spec.rb, spec/lib/nearby_on_shelf_spec.rb, spec/models/concerns/eds_links_spec.rb, spec/models/marc_fields/organization_and_arrangmenet_spec.rb
=> Tweak some constant and variable names

config/locales/searchworks.en.yml
=> Update link in global alert.

app/helpers/request_link_helper.rb, app/models/hoover_open_url_request.rb, app/models/request_link.rb, app/models/request_link_factory.rb, app/models/request_links/hoover_archive_request_link.rb, app/models/request_links/hoover_request_link.rb, app/models/request_links/ssrc_data_request_link.rb, app/views/catalog/_index_location.html.erb, app/views/catalog/access_panels/_location.html.erb, lib/holdings/location.rb, spec/features/request_link_spec.rb, spec/models/hoover_open_url_requst_spec.rb, spec/models/request_link_factory_spec.rb, spec/models/request_link_spec.rb, spec/models/request_links/hoover_archive_request_link_spec.rb, spec/models/request_links/hoover_request_link_spec.rb, spec/models/request_links/ssrc_data_request_link_spec.rb, spec/views/catalog/_index_location.html.erb_spec.rb, spec/views/catalog/access_panels/_location.html.erb_spec.rb
=> Update Request Link logic for re-opening of paging services

app/models/concerns/cjk_query.rb
https://app.honeybadger.io/projects/50022/faults/46000963
=> Don't call gsub! on query params (they may be frozen strings)

app/models/request_link.rb, app/models/request_link_factory.rb, app/models/request_links/hopkins_request_link.rb, app/views/catalog/access_panels/_location.html.erb, lib/constants.rb, spec/models/request_link_spec.rb, spec/models/request_links/hopkins_request_link_spec.rb, spec/views/catalog/access_panels/_location.html.erb_spec.rb
=> [6/26] Add SERG Libraries + DRMC + Locked Stacks Request Links

app/views/shared/_search_navbar_services_menu.html.erb
=> Update suggest a purchase link fixes #2504

app/controllers/catalog_controller.rb, app/models/json_results_document_presenter.rb, spec/controllers/catalog_controller_spec.rb, spec/models/json_results_document_presenter_spec.rb, spec/requests/json_api_spec.rb
=> Add temporary access links to our results API

Gemfile, Gemfile.lock, app/models/eds/session.rb, config/settings.yml
This has been tested out in UAT by @trapido and given then 👍
=> Update EDS (and configure smart text failover)

lib/constants.rb
=> Add LL-NEWS location translation.

config/locales/searchworks.en.yml
=> Restore global message to research restart

app/models/request_links/sal_request_link.rb
Connected to sul-dlss/sul-requests#1060 (that PR should be rolled out before this one)
=> Add request links to scannable only locations/item-types in SAL.

app/views/articles/_home_page.html.erb
=> Update search guide link to be redirect

app/views/marc_fields/_linked_author.html.erb, app/views/marc_fields/_linked_author_index.html.erb, spec/views/marc_fields/_linked_author.html.erb_spec.rb, spec/views/marc_fields/_linked_author_index.html.erb_spec.rb
Waiting on some feedback on what we should be doing w/ similar data in the search results (if anything)
=> Fix vernacular display for linked authors

app/assets/javascripts/jquery.live-lookup.js, app/helpers/request_link_helper.rb, app/models/request_link.rb, spec/helpers/request_link_helper_spec.rb
=> Don't use modal/iframes for requests.

README.md
=> Update badge on README to point to GH Action Status

.github/workflows/ruby.yml
=> Setup bundler cache

app/models/request_link.rb, spec/models/request_link_spec.rb
=> Add request links to materials in GREEN IC

Gemfile.lock
=> Update global alerts version

app/views/catalog/_index_cdl_section.html.erb, app/views/catalog/access_panels/_cdl.html.erb
=> Digital borrowing fixes #2592

app/models/request_link.rb, lib/holdings/location.rb, spec/models/request_link_spec.rb
=> Add request links for various in-process locations

app/helpers/access_panel_helper.rb, app/views/catalog/access_panels/_online.html.erb, spec/features/access_panels/online_spec.rb, spec/helpers/access_panel_helper_spec.rb, spec/integration/external-data/access_panels_spec.rb, spec/views/catalog/access_panels/_online.html.erb_spec.rb
=> "Report a connection problem" panel footer updates

app/controllers/catalog_controller.rb, app/controllers/concerns/search_relevancy_logging.rb, config/application.rb
=> Add some search relevancy logging

app/controllers/concerns/search_relevancy_logging.rb
Related to https://app.honeybadger.io/projects/50022/faults/76776311
=> Safe navigate the current_search_session in case it does not exist.

Gemfile.lock, app/helpers/record_helper.rb, app/views/catalog/_mods_search_results_document_fields.html.erb, app/views/catalog/record/_mods_contributors.html.erb, app/views/catalog/record/_mods_subjects.html.erb, spec/helpers/record_helper_spec.rb
I've only pointed this at the local index, nothing with production data. But looking good to me.
=> Replace current RecordHelpers with upstream ported code

app/models/sfx_data.rb, app/views/sfx_data/show.html.erb, spec/models/sfx_data_spec.rb, spec/views/sfx_data/show.html.erb_spec.rb
=> Add embargo and notes to the SFX access panel

lib/constants.rb
=> Remove BENDER from NONCIRC_LOCS

app/controllers/application_controller.rb, app/models/concerns/index_links.rb, app/models/hathi_trust_links.rb, app/views/articles/access_panels/_sfx.html.erb, spec/controllers/barcode_controller_spec.rb, spec/controllers/lib_guides_controller_spec.rb, spec/controllers/sfx_data_controller_spec.rb, spec/models/hathi_trust_links_spec.rb, spec/routing/article_routes_spec.rb, spec/views/marc_fields/_linked_related_works.html.erb_spec.rb
Sadly, not all of them. Many BL7-related deprecation warnings remain.
=> Ditch a bunch of deprecation warnings

app/models/marc_fields/subjects.rb, spec/fixtures/marc_records/marc_metadata_fixtures.rb, spec/views/catalog/record/_marc_subjects.html.erb_spec.rb
(Requested by Vitus in Gryphonsearch, pending full agreement of the group about what we're doing and how we're doing it 🤷‍♂️)
=> Deduplicate subjects

app/helpers/masthead_helper.rb, app/models/bookplate.rb, spec/models/bookplate_spec.rb
This is mostly trying to clarify how the fund facet + bookplates work, plus a tiny extension to support fund codes in addition to druids (related to https://github.com/sul-dlss/searchworks_traject_indexer/pull/537, and potential future work)
=> Do a little refactoring and cleanup around fund facets

app/views/browse/index.html.erb, app/views/catalog/thumbnails/_collection_thumbnail.html.erb, app/views/catalog/thumbnails/_item_thumbnail.html.erb, app/views/preview/_show_marc.html.erb, app/views/preview/_show_mods.html.erb
=> Improve callnumber browse accessibility

Gemfile, Gemfile.lock
Removing some cruft from the Gemfile. We're well past the versions we were trying to avoid.
=> Remove unnecessary pins in Gemfile

config/locales/searchworks.en.yml
=> Modify display label for MARC 510

lib/holdings/mhld.rb, spec/lib/holdings/mhld_spec.rb
=> Add a space after semicolons in the mhld

app/models/marc_fields/subjects.rb, spec/models/marc_fields/subjects_spec.rb
Part of https://github.com/sul-dlss/searchworks_traject_indexer/issues/550
=> Suppress nomesh values in the 6xx display

app/controllers/concerns/location_facet.rb, lib/constants.rb
=> Re-label Cubberley

app/models/concerns/index_links.rb, spec/models/concerns/index_links_spec.rb
=> Fix a regression (from #2661) with handling unparsable URLs

app/views/catalog/record/_mods_abstract_contents.html.erb, spec/views/catalog/record/_mods_abstract_contents.html.erb_spec.rb
=> Display abstract + toc labels using mods_display

app/assets/stylesheets/modules/brief-view.scss, app/assets/stylesheets/modules/flex.scss, app/assets/stylesheets/searchworks.scss, app/views/catalog/_index_brief.html.erb
=> Use flexbox to align controls in the brief view

Gemfile, Gemfile.lock
Deployed to searchworks-uat for testing.
=> Update ebsco-eds gem

Gemfile, Gemfile.lock, app/assets/javascripts/blacklight_gallery.js, app/assets/stylesheets/blacklight_gallery.scss, app/assets/stylesheets/modules/gallery-view.scss, app/controllers/catalog_controller.rb
Maybe I'm missing something, but I don't see where this is currently used.
=> Remove blacklight-gallery

app/models/request_link.rb, lib/constants.rb
=> Add W7-MAP-XLG location for Rumsey

app/models/request_link.rb, spec/models/request_link_spec.rb, spec/views/catalog/_index_location.html.erb_spec.rb, spec/views/catalog/access_panels/_location.html.erb_spec.rb
=> [Ship 9/7] Remove PAGE request links from many campus libraries circulating collections

lib/constants.rb
Part of https://github.com/sul-dlss/sul-requests/issues/1206
=> Update Rumsey access panel text

lib/constants.rb
=> Add translation for SGC

Gemfile, Gemfile.lock
They've done something weird with zeitwerk and things no longer load correctly 🤷‍♂️
=> Pin faraday-detailed_logger to fix #2759

app/views/shared/_search_subnavbar.html.erb
👍. This has been approved for deployment on 12/13
=> winter closure - bump Access info to 2022

app/views/catalog/record/_marc_subjects.html.erb
=> Removed field 654. Add field 647.

lib/constants.rb
Adds SCIFI location.
Closes #2775
=> Add SCIFI location to constants.

lib/constants.rb
=> Translate new location for Hohbach Hall magazines

app/views/shared/_chat_librarian_sidebar.html.erb, lib/constants.rb
=> Update IC Reference location translation

app/models/marc_fields/subjects.rb
=> Refactor subject display, and stop hoisting $a to the front

lib/constants.rb, spec/views/catalog/access_panels/_location.html.erb_spec.rb
Closes #2829 
**Hold until May 2**
=> Update library instructions for SPEC and Rumsey

lib/constants.rb
See SW-4113 in JIRA.. this will make SCI-RESV the same as e.g. ENG-RESV
=> Add SCI-RESV to the list of CURRENT_HOME_LOCS

config/settings.yml
See VUF-8851. Probably a data error 🤷‍♂️
=> Add ND-PAGE-EA as a pageable location for SAL3

app/views/catalog/record/_marc_upper_metadata_items.html.erb
=> Display the MARC 300$3 on show pages

app/views/catalog/_citation.html.erb, app/views/catalog/_email_form.html.erb, app/views/catalog/_sms_form.html.erb
See https://github.com/projectblacklight/blacklight/pull/2271
Fixes #2872
Fixes #2874
=> Safe-navigate when iterating over the documents ivar in various export views

app/controllers/articles_controller.rb
We must have figured out a better option at some point 🤷‍♂️
=> Remove old comment

app/views/catalog/record/_marc_contents_summary.html.erb
=> Display "S" icon after stanford-only supplemental links.

app/views/article_selections/_tool_dropdown.html.erb, app/views/articles/_facet_additional_selections_warning.erb
=> Use #to_unsafe_h on a couple more links

config/initializers/mime_types.rb
=> Register ris MIME type

app/models/article_search_builder.rb, spec/models/article_search_builder_spec.rb
=> Guard against passing arrays of range values through to EDS

app/controllers/articles_controller.rb
=> Configure the citation action for articles+

config/settings.yml
=> Add more SAL circulating item types

app/views/catalog/record/_marc_upper_metadata_items.html.erb
Fixes a regression introduced in #2868
=> Fix find+replace error in uniform title display

app/assets/stylesheets/modules/access-panel-library-locations.scss, app/helpers/marc_helper.rb, app/models/request_link.rb
=> Add icon to "Request" buttons

app/models/concerns/eds_subjects.rb
=> Ensure node['term'] is a string

Gemfile
already listed here:
https://github.com/sul-dlss/SearchWorks/blob/54b80e87fe22a7c463fd81387450990ed1de7cbe/Gemfile#L24-L25
=> Remove duplicate bootsnap dependency in Gemfile

.github/workflows/ruby.yml
=> Drop the ruby 2.7 build

app/assets/stylesheets/modules/brief-view.scss, app/assets/stylesheets/modules/browse-embed.scss, app/assets/stylesheets/modules/gallery-view.scss, app/assets/stylesheets/searchworks-mixins.scss, app/views/catalog/thumbnails/_collection_thumbnail.html.erb, app/views/catalog/thumbnails/_item_thumbnail.html.erb
Some before + after screenshots (not that there's much of a difference beyond a little alignment 🤷‍♂️ )
Before:
After:
Before:
After:
=> Use flexbox to style the gallery tiles

app/assets/javascripts/skip-to-nav.js
=> Fix some typos

README.md, app/assets/javascripts/jquery.requestsModal.js, config/initializers/devise.rb, config/routes.rb
- Remove webauth-specific Devise config
- Rename webauth login route to sso login
=> Rename /webauth/ routes to /sso/

app/assets/javascripts/course_reserves.js, app/assets/stylesheets/modules/course_reserve_browse.scss, app/assets/stylesheets/modules/data-tables.scss
=> Style the course reserves datatable with flexbox

app/assets/stylesheets/modules/home-page.scss, app/views/shared/_home_page_bento.html.erb
=> Rewrite the 'you are here' badge using explicit dom elements

app/views/layouts/searchworks.html.erb
_**[WIP]** while we see there are any gotchas we need to be aware of via sul-dlss/exhibits#1153_
=> [WIP] Load application.js asynchronously to improve 1st draw.

lib/tasks/rubocop.rake
=> Remove warning that Rubocop is not present (expected in prod)

app/views/layouts/searchworks.html.erb
> ReferenceError: Can't find variable: Honeybadger
=> Async doesn't play nicely with Honeybadger (and WebFont) loading below

app/assets/stylesheets/modules/record-metadata-section.scss
Before:
https://searchworks.stanford.edu/view/576562
After:
=> Fix a typo

.rubocop.yml, .rubocop_todo.yml, app/controllers/catalog_controller.rb
=> Fix opensearch responses; fixes #2953

app/views/catalog/librarian_view.html.erb, config/locales/en.yml, spec/views/catalog/librarian_view.html.erb_spec.rb
Closes #983
📝 CHANGELOG update?
Add last updated to librarian view
=> Add Last updated to librarian view

app/assets/stylesheets/bootstrap-overrides.scss, app/assets/stylesheets/modules/librarian-view.scss, app/views/catalog/_folio_json_view.html.erb, app/views/catalog/_marc_view.html.erb, spec/views/catalog/librarian_view.html.erb_spec.rb
Closes #2955
📝 CHANGELOG update
Add FOLIO JSON to librarian view
=> Add FOLIO JSON to librarian view

app/views/catalog/_folio_json_view.html.erb, spec/views/catalog/librarian_view.html.erb_spec.rb
=> `items_json_struct` is now gone

app/models/concerns/marc_json_extension.rb, app/models/solr_document.rb, spec/models/solr_document_spec.rb
We used a different field name in https://github.com/sul-dlss/searchworks_traject_indexer/pull/651
=> Rename the marcjson field

lib/holdings/location.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/2973
=> Apparently we pretend Holdings::Location is a null object sometimes

lib/holdings/location.rb
https://app.honeybadger.io/projects/50022/faults/87414562 happens... way too often
=> Don't spam honeybadger with location alerts

app/models/concerns/marc_json_extension.rb
=> blacklight-marc can't handle multi-valued marc record fields

app/models/concerns/collection_member.rb, lib/page_location.rb
https://github.com/sul-dlss/searchworks_traject_indexer/pull/697 adds `folio` as a potential value for the `collection` field.
=> Allow folio collection data

app/controllers/catalog_controller.rb
=> Add author, pub date, and finding aid to availability.json

Gemfile, Gemfile.lock
=> Unpin oauth2 version

app/views/layouts/searchworks.html.erb
=> Remove obsolete meta tags and conditional styles

lib/search_works/links.rb, spec/models/concerns/index_links_spec.rb, spec/models/concerns/marc_links_spec.rb
=> Set the qurl rather than url param for ezproxy links

README.md
I couldn't find anywhere that described how to do this...
=> Document how to get data in local development

config/ezproxy/sul_proxy_file.txt
Removal requested by Acquisitions.
=> Remove janes domains from proxy list

lib/constants.rb
=> Change CURRICULUM loc to Curriculum at Green

config/locales/blacklight.en.yml, spec/features/blacklight_customizations/bookmarks_path_spec.rb, spec/features/blacklight_customizations/search_toolbar_spec.rb
TODO: fix up the tests
SW-1309
=> Localize "no bookmarks" text

config/settings.yml
=> Update pageable locations for Hopkins library

config/settings.yml
=> Avoid deprecated method File.exists?

app/controllers/concerns/database_access_point.rb, app/helpers/masthead_helper.rb, app/models/search_builder.rb, lib/page_location.rb, spec/controllers/concerns/database_access_point_spec.rb, spec/helpers/masthead_helper_spec.rb, spec/lib/page_location_spec.rb
Because it protects from Facebooks badly mangled parameters
Fixes #3107
=> Use Blacklight:SearchState

spec/controllers/concerns/database_access_point_spec.rb
=> Fix flappy tests

.rubocop_todo.yml, app/controllers/concerns/email_validation.rb, app/helpers/xml_api_helper.rb, lib/holdings/item.rb, lib/live_lookup.rb
=> Prefer exclude? over negated include?

.rubocop_todo.yml, spec/components/access_panels/at_the_library_component_spec.rb, spec/components/access_panels/course_reserves_component_spec.rb, spec/components/access_panels/sfx_component_spec.rb, spec/features/access_panels/course_reserve_spec.rb, spec/helpers/alternate_catalog_helper_spec.rb, spec/models/bookplate_spec.rb, spec/models/solr_document_spec.rb
=> Prefer 'be true' over 'eq true'

.rubocop_todo.yml, app/controllers/availability_controller.rb, app/helpers/article_helper.rb, app/helpers/feedback_form_helper.rb, app/models/concerns/eds_links.rb, app/models/concerns/eds_subjects.rb
=> Prefer match? over =~

config/solr_configs/schema.xml, config/solr_configs/solrconfig.xml
=> Sync solr configs with production configs

config/settings.yml, spec/models/concerns/index_links_spec.rb
=> Remove auth=shibboleth from law ezproxy

Jenkinsfile-Lane-Update
Fixes authentication problem creating a PR via Jenkins to update the lane proxy file.
```
(fatal: could not read Username for 'https://github.com': No such device or address)fatal: could not read Username for 'https://github.com/': No such device or address
```
=> Use git@github.com:sul-dlss/SearchWorks.git to push lane-ezproxy-update branch 

app/views/catalog/_index_location.html.erb, spec/views/catalog/_index_location.html.erb_spec.rb
=> Don't show item-level request links if there's already a location-level request link

app/components/access_panels/at_the_library_component.rb, app/components/access_panels/library_component.rb, app/components/access_panels/library_location_component.rb, app/components/location_request_link_component.rb, app/helpers/request_link_helper.rb, lib/holdings.rb, lib/holdings/library.rb, lib/holdings/location.rb
=> Add documentation to some methods

Gemfile, Gemfile.lock, app/services/folio_client.rb, spec/services/folio_client_spec.rb, spec/spec_helper.rb
=> Add a FolioClient service

app/services/live_lookup.rb, app/services/live_lookup/folio.rb, spec/services/live_lookup/folio_spec.rb
Part of [#3135](https://github.com/sul-dlss/SearchWorks/issues/3135).
Will wire it up to update availability in another PR.
=> Add LiveLookup service for FOLIO

app/assets/javascripts/jquery.live-lookup.js, app/components/access_panels/at_the_library_component.html.erb, app/components/access_panels/library_location_component.html.erb, app/models/concerns/live_lookup_ids.rb, app/models/concerns/solr_holdings.rb, app/models/solr_document.rb, app/services/live_lookup/folio.rb, app/services/live_lookup/sirsi.rb, app/views/catalog/_index_location.html.erb, lib/holdings/item.rb, spec/components/access_panels/at_the_library_component_spec.rb, spec/lib/holdings/item_spec.rb, spec/models/concerns/live_lookup_ids_spec.rb, spec/services/live_lookup/folio_spec.rb, spec/services/live_lookup/sirsi_spec.rb, spec/views/catalog/_index_location.html.erb_spec.rb
=> Use LiveLookup::Folio to update availability information when enabled

app/components/location_request_link_component.rb, app/services/folio/circulation_rules/policy_service.rb, config/settings.yml, lib/holdings/item.rb, spec/components/location_request_link_component_spec.rb
An initial stab at part of #3129. Hopefully it's enough to see if circ rules get us kinda close or if they're not a good fit.
Builds on #3183
=> Render location-level request links based on the circ rules

config/solr_configs/solrconfig.xml
Needed for FOLIO live availability
=> Add uuid_ssi to default fl config

app/views/catalog/_folio_json_view.html.erb
=> Add debug information for FOLIO circ rules to the librarian view

app/views/catalog/_index_location.html.erb
=> Allow unknown library codes

app/views/catalog/_index_location.html.erb
=> Add more guards for missing library settings

app/helpers/application_helper.rb, app/views/catalog/show.html.erb
=> Conditionally display warning about FOLIO migration data

lib/constants.rb, spec/components/access_panels/at_the_library_component_spec.rb
=> Update special collection at the library message

.rubocop.yml, app/models/concerns/digital_collection.rb, app/models/concerns/extent.rb, app/models/marc_field.rb, lib/holdings/item.rb
=> Add new rubocop rules

app/models/concerns/collection_titles.rb, spec/models/concerns/collection_titles_spec.rb
=> Exclude digital collections from collection title display

config/ezproxy/sul_proxy_file.txt
=> Add stanford-artech-patron.eb20.com sul_proxy_file.txt

app/models/folio/location.rb, app/services/folio/circulation_rules/index.rb, app/services/folio/circulation_rules/policy_service.rb, app/services/folio/circulation_rules/rule.rb, app/services/folio/circulation_rules/transform.rb, config/folio/circulation_rules.csv, spec/services/folio/circulation_rules/policy_service_spec.rb
=> Continue to improve the circ rules diff

app/components/location_request_link_component.rb, app/models/folio/item.rb, lib/constants.rb, lib/holdings/item.rb, spec/components/location_request_link_component_spec.rb, spec/lib/holdings/item_spec.rb, spec/models/folio/item_spec.rb
When in special collections and Missing or In process statuses
Ref #3129
=> Don't show request links for Folio items

.rubocop.yml, .rubocop_todo.yml, app/components/location_request_link_component.rb, app/models/concerns/index_links.rb
=> [Refactor] move finding_aid? method to the SolrDocument model

app/views/catalog/_stackmap_link.html.erb, lib/holdings/location.rb, spec/lib/holdings/location_spec.rb
=> Refactor location links and stop linking to Voyager for FOLIO records

lib/constants.rb
=> Hopkins is switching from PAGE-HP to PAGE-MA for consistency

app/policies/request_link_policy.rb, spec/policies/request_link_policy_spec.rb
=> Handle the case where there are no items

app/assets/javascripts/jquery.live-lookup.js
Related to changes here: https://github.com/sul-dlss/SearchWorks/pull/3268
=> Target deliver-from-offsite class when updating availability status

lib/tasks/searchworks.rake
=> Fix pruning task

app/components/item_request_link_component.rb, app/components/location_request_link_component.rb, app/policies/item_request_link_policy.rb, app/policies/location_request_link_policy.rb, spec/policies/location_request_link_policy_spec.rb
This makes room for an ItemRequestLinkPolicy as well
=> Move RequestLinkPolicy to LocationRequestLinkPolicy

spec/spec_helper.rb
=> Pin required chromedriver version to v114

lib/holdings/library.rb
=> Add a comment explaining grouping by translation

app/models/folio/holding.rb, app/models/folio/location.rb, app/policies/location_request_link_policy.rb, spec/components/location_request_link_component_spec.rb, spec/policies/location_request_link_policy_spec.rb
=> Migrate bound-with logic to use folio data

app/services/live_lookup/folio.rb, config/application.rb, spec/services/live_lookup/folio_spec.rb
FOLIO due dates are stored as UTC.
=> Parse the due date using the application's time zone

lib/holdings/location.rb
We don't want HB notifications when these come up.
=> Add more folio legacy locations to ignore

lib/holdings/item.rb
We don't need to keep looking up the equivalent FOLIO code...
=> Memoize Holdings::Item#current_location

app/views/shared/_su_footer.html.erb
=> Update footer links

config/settings.yml
=> [HOLD until 7/30 11pm PDT] Update about URLs for new D9 pages

app/views/catalog/mastheads/_bookplate_fund.html.erb
=> Update _bookplate_fund.html.erb link

app/views/course_reserves/index.html.erb
=> Update CREZ info URL

Gemfile, Gemfile.lock, spec/spec_helper.rb
=> Remove pin of chromedriver

app/views/shared/_su_footer.html.erb, app/views/shared/_top_navbar.html.erb
=> Update link to mylibrary

.rubocop.yml, spec/components/access_panels/in_collection_component_spec.rb, spec/controllers/article_controller_spec.rb, spec/helpers/alternate_catalog_helper_spec.rb, spec/helpers/catalog_helper_spec.rb, spec/lib/page_location_spec.rb, spec/services/folio/circulation_rules/policy_service_spec.rb, spec/views/catalog/_index_marc.html.erb_spec.rb, spec/views/catalog/_index_mods.html.erb_spec.rb, spec/views/catalog/_show_marc.html.erb_spec.rb, spec/views/catalog/thumbnails/_collection_thumbnail.html.erb_spec.rb, spec/views/catalog/thumbnails/_item_thumbnail.html.erb_spec.rb, spec/views/shared/_zero_results.html.erb_spec.rb
=> Add new rubocop config and autocorrect

app/components/item_request_link_component.rb, lib/constants.rb, spec/components/item_request_link_component_spec.rb
=> Convert ItemRequestLinkComponent to use Folio locations 

app/models/folio/item.rb
=> Guard against items without permanent locations

app/services/live_lookup/solr.rb, spec/services/live_lookup/solr_spec.rb
=> Add LiveLookup::Solr service for use when ILS service is unavailable

app/assets/stylesheets/modules/global-alert.scss
=> Allow global alert paragraphs to fill the whole alert section

app/views/catalog/_folio_json_view.html.erb
We show expanded details for the preferred item, but it will be helpful for collecting feedback if we can also get at rules for each item. It doesn't need to be as pretty because it will just get plopped in a spreadsheet for analysis.
=> Add full details (for all items) for circ rules for reporting circ rule errors

Jenkinsfile-Folio-Update
... to sync better with sul-requests. Part of https://github.com/sul-dlss/sul-requests/issues/1614
=> Pin down folio updates to a narrower window of time

lib/holdings/library.rb, spec/lib/holdings/library_spec.rb
=> Use the location's _library_ name for Holdings::Library

app/components/access_panels/library_location_component.html.erb, app/components/access_panels/library_location_component.rb, app/components/access_panels/location_item_component.html.erb, app/components/access_panels/location_item_component.rb, app/models/concerns/solr_holdings.rb, app/models/hathi_trust_links.rb, app/views/catalog/_index_location.html.erb, lib/holdings/item.rb, lib/holdings/library.rb, lib/holdings/location.rb, spec/lib/holdings/item_spec.rb
=> Extract location item component

spec/lib/holdings/library_spec.rb
Remove assertions on the inputs that the test provides. Use contexts when appropriate. Use more suitable names.
=> Refactor spec around Holdings::Library#locations

lib/holdings/item.rb, lib/holdings/mhld.rb, spec/lib/holdings/library_spec.rb
It should be nil rather than an empty string
Fixes #3441
=> Fix ZOMBIE MHLD location

config/locales/okcomputer_en.yml
I'm not sure what this does, but we don't use it elsewhere so...
=> Remove custom okcomputer formatting

Jenkinsfile-Folio-Update
=> Switch folio update to use the prod server

app/services/folio_client.rb, config/initializers/okcomputer.rb, spec/features/status_spec.rb
Part of https://github.com/sul-dlss/library-status/issues/389
I think this is the best we can do for now?
=> Add live_lookup check to OkComputer

app/policies/location_request_link_policy.rb, lib/constants.rb, lib/holdings/status.rb, spec/policies/location_request_link_policy_spec.rb
...and using the location availability class data for SPEC special cases
=> Add support for non-requestable in-process item statuses..

config/solr_configs/schema.xml, config/solr_configs/solrconfig.xml
=> Sync test schemas from -prod

config/ezproxy/law_proxy_file.txt
=> Update law proxy file

lib/holdings/location.rb, spec/lib/holdings/location_spec.rb
=> Remove LANE-MED location links

lib/holdings/item.rb
=> Allow folio-item to be nil

app/controllers/catalog_controller.rb, app/models/concerns/solr_holdings.rb, config/routes.rb, spec/controllers/catalog_controller_spec.rb
=> Remove catalog#availability route

config/settings.yml, spec/helpers/stackmap_helper_spec.rb
=> Remove stackmaps for LAW

lib/holdings.rb
=> Document the parameters to Holdings

app/views/shared/_search_navbar_services_menu.html.erb
=> Remove find subject specialist link

app/policies/item_request_link_policy.rb, app/policies/location_request_link_policy.rb, app/services/folio/circulation_rules/policy_service.rb, lib/holdings/item.rb, spec/components/item_request_link_component_spec.rb, spec/components/location_request_link_component_spec.rb
=> Make Holdings::Item#request_policy private

lib/holdings/status.rb
=> Prefer using include rather than multiple equals clauses

app/components/access_panels/location_item_component.html.erb, app/models/concerns/live_lookup_ids.rb, app/models/folio/holding.rb, lib/holdings/item.rb, lib/holdings/location.rb, spec/components/access_panels/at_the_library_component_spec.rb, spec/lib/holdings/item_spec.rb, spec/lib/holdings/location_spec.rb, spec/models/concerns/live_lookup_ids_spec.rb
Closes https://github.com/sul-dlss/SearchWorks/issues/3494
=> Display parent availability for FOLIO bound-with children

config/initializers/blacklight_initialize.rb, config/settings.yml
With https://github.com/sul-dlss/shared_configs/pull/2066.
=> Configure BlacklightDynamicSitemap to use the export handler

app/views/shared/_side_nav_minimap.html.erb
=> Add accessible labels for side nav buttons

app/helpers/application_helper.rb, app/views/catalog/show.html.erb
=> Remove FOLIO migration disclaimer

config/settings.yml, config/settings/development.yml, config/settings/test.yml
=> Remove unused variables

app/assets/javascripts/async_collection_members.js
Just use the fetch() api instead.
=> Move away from jquery 1.x ajax api

.rubocop.yml, .rubocop_todo.yml
=> Update rubocop BlockLength rule

app/assets/stylesheets/modules/access-panel-course-reserve.scss, app/assets/stylesheets/modules/access-panel-library-locations.scss, app/assets/stylesheets/modules/access-panel-online.scss, app/assets/stylesheets/sul-variables.scss
=> Rename -access-font variable to be more descriptive

app/services/folio/types.rb
Fixes https://github.com/orgs/sul-dlss/projects/51/views/2?pane=issue&itemId=37031834 for SearchWorks
=> Sort generated types json before writing to file

config/ezproxy/sul_proxy_file.txt
Closes https://github.com/sul-dlss/SearchWorks/issues/3593
=> Change faulkner.com proxy url

app/views/catalog/_show_main_content.html.erb, app/views/catalog/show.html.erb
So that we have something that matches what blacklight is doing in each partial.  This means that we can change only the little bits that need changing, rather than having to override a lot in one file.
=> Split show and main content partials

app/assets/javascripts/feedback_form.js
This helps to move us off Jquery 1.x, so that we can upgrade to Bootstrap 4.
=> Convert feedback form to use fetch

app/helpers/collection_helper.rb, app/models/concerns/digital_collection.rb, spec/helpers/collection_helper_spec.rb, spec/models/concerns/digital_collection_spec.rb
=> Use the right id when generating a collection member search

app/models/concerns/digital_collection.rb, spec/models/concerns/digital_collection_spec.rb, spec/views/collection_members/_file_collection_members.html.erb_spec.rb
=> Ensure that we can handle digital collections with no members

app/assets/javascripts/application.js
=> Prevent turbolinks from reinitializing recaptcha when loading from cache

app/assets/javascripts/application.js
Previously we only accounted for one of two forms.
=> Clear all of the recaptcha elements before caching

app/views/shared/_email_form.html.erb, app/views/shared/feedback_forms/_form_fields.html.erb
=> Use different IDs for the two ReCaptchas used on our forms

config/ezproxy/sul_proxy_file.txt
=> Add flipster.ebsco.com to sul proxy list

app/assets/stylesheets/base.scss
=> Don't underline facet remove button on hover

app/views/shared/_skip_to_nav.html.erb, config/locales/searchworks.en.yml
=> Put the skip links inside a labeled nav

config/ezproxy/sul_proxy_file.txt
=>  replace www.clcd.com

app/assets/javascripts/jquery.preview-gallery.js
=> Fix arrow offset for preview gallery

app/helpers/catalog_helper.rb, app/services/folio/locations_map.rb, lib/holdings/item.rb
At least until stackmaps is ready to handle FOLIO codes.
=> Map location codes to Symphony codes for stackmaps

lib/holdings/item.rb, spec/components/access_panels/at_the_library_component_spec.rb, spec/components/item_request_link_component_spec.rb, spec/fixtures/solr_documents/4.yml, spec/lib/holdings/item_spec.rb, spec/views/catalog/_index_location.html.erb_spec.rb
=> Use the status from the item_display field to determine on-order-ness

app/assets/stylesheets/base.scss, app/views/catalog/_search_results.html.erb
=> Fix layout of zero results display

config/ezproxy/sul_proxy_file.txt
=> Add db.mkstudy.com to sulproxy file

config/settings.yml, spec/models/concerns/index_links_spec.rb, spec/models/links/ezproxy_spec.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/3713
=> Update Law EZproxy prefix

config/solr_configs/schema.xml, config/solr_configs/solrconfig.xml
Hold until https://github.com/sul-dlss/sul-solr-configs/pull/282 is approved and merged.
=> Set id_search and barcode_search fields to string_punct_stop type

.github/workflows/ruby.yml, Jenkinsfile
=> Rename default branch to main

config/deploy.rb
=> Autodeploy the correct branch

Gemfile, Gemfile.lock
=> Update to rspec-rails 6.1

.github/workflows/ruby.yml
=> Test on ruby 3.3

app/assets/javascripts/jquery.preview-gallery.js
=> Correctly check for NaN case

Gemfile
=> Add documentation about why we need the parselt gem

config/application.rb, config/initializers/zeitwerk.rb, lib/holdings.rb
=> Remove unnecessary requires

app/controllers/articles_controller.rb, app/models/eds.rb, config/application.rb, config/initializers/okcomputer.rb, spec/controllers/quick_reports_controller_spec.rb, spec/helpers/record_helper_spec.rb
=> Use Rails 7.1 defaults

README.md
This is an undocumented but necessary step.
=> Add yarn install to README steps

Gemfile, Gemfile.lock, app/components/access_panels/online_eds_component.html.erb, app/components/articles/response/facet_group_component.html.erb, app/helpers/catalog_helper.rb, app/javascript/application.js, app/javascript/course_reserves.js, app/presenters/article_fulltext_link_presenter.rb, app/views/articles/_index_brief.html.erb, app/views/catalog/_select_all_widget.html.erb, app/views/layouts/application.html.erb, app/views/shared/_skip_to_nav.html.erb, package.json, spec/helpers/catalog_helper_spec.rb, yarn.lock
=> Replace turbolinks with turbo

Gemfile, Gemfile.lock, app/components/access_panels/appears_in_component.html.erb, app/components/access_panels/collection_component.html.erb, app/components/access_panels/course_reserves_component.html.erb, app/components/access_panels/exhibit_component.html.erb, app/components/access_panels/online_component.html.erb, app/components/access_panels/online_eds_component.html.erb, app/components/access_panels/related_component.html.erb, app/components/access_panels/sfx_component.html.erb, app/components/additional_selections_facet_component.html.erb, app/components/articles_range_limit_component.html.erb, app/components/view_type_dropdown_component.rb, spec/rails_helper.rb
=> Update to view_component 3

app/javascript/application.js, package.json, yarn.lock
=> Remove rails-ujs

app/assets/stylesheets/modules/gallery-view.scss, app/javascript/embedded-call-number-browse.js, app/javascript/truncate.js, app/views/catalog/_index_header_gallery.html.erb
=> Fix call number browse javascript

app/helpers/record_helper.rb, spec/helpers/record_helper_spec.rb
=> update record helper to include correct class for mods gem

app/views/catalog/_search_bar_selections_widget.html.erb, app/views/catalog/_sort_and_per_page.html.erb
Ref https://github.com/sul-dlss/SearchWorks/pull/3751#issuecomment-1902175863
Rails-ujs will not ship any more releases: https://github.com/rails/rails/pull/50535
=> Replace Rails-ujs directives with turbo-rails directives

yarn.lock
This should fix problems with CSRF tokens when making selections"
=> Upgrade blacklight-frontend to 7.36.2

app/javascript/application.js, app/javascript/bootstrap-modal-addon.js
=> Remove empty script

app/views/catalog/_home_page.html.erb
=> remove incorrect title, make blank to match other icons on homepage

app/components/access_panels/collection_component.html.erb, spec/components/access_panels/in_collection_component_spec.rb
=> wrap collection summary in helpers.format_record_html

app/javascript/select-all.js
=> Apply a rate limit to check all

app/helpers/preview_helper.rb, app/views/catalog/_index_brief.html.erb, app/views/catalog/_index_gallery.html.erb, app/views/collection_members/_image_collection_filmstrip.html.erb
This makes the code easier to understand
=> Remove unused conditional

Gemfile, Gemfile.lock
=> Update to fixed version of recaptcha gem

app/components/access_panels/online_component.html.erb
=> update online heading to always show up

app/services/folio/types.rb, app/services/folio_client.rb, spec/services/folio/types_spec.rb
So that we don't need to stuff it in Solr
Ref #3736
=> Load course reserves data from Folio

app/views/articles/_show_header_reference.html.erb
=> Remove unused partial

app/components/access_panels/appears_in_component.html.erb, app/components/search_result/item/marc/metadata_component.html.erb, app/models/concerns/database_document.rb, app/models/concerns/extent.rb, app/models/marc_fields/language.rb, app/models/solr_document.rb, app/views/catalog/_show_main_content.html.erb, app/views/catalog/record/_marc_subjects.html.erb, app/views/collection_members/_file_collection_members.html.erb, app/views/preview/_show_header_default.html.erb, spec/models/concerns/database_document_spec.rb
=> Extract a document_formats method and use it consistently

app/mailers/application_mailer.rb, app/mailers/feedback_mailer.rb, app/mailers/search_works_record_mailer.rb
This is a required class for Blacklight 8.  Typically it's installed by default when you generate a Rails app
=> Add application mailer

config/ezproxy/sul_proxy_file.txt
=> Update sul proxy file

app/views/_flash_msg.html.erb
So we can debug why it's not working.
=> Render the recaptcha-error in the flash messages

Gemfile.lock, app/javascript/application.js, yarn.lock
=> Restore Blacklight-range-limit facet functionality

app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/sul-variables.scss
=> Remove duplicate color

app/controllers/catalog_controller.rb, config/environments/development.rb, spec/features/blacklight_customizations/results_document_spec.rb
=> Use the ThumbnailWithIIIFComponent for thumbnails

app/components/search_result/item/marc/metadata_component.html.erb, app/helpers/catalog_helper.rb, app/views/catalog/record/_marc_subjects.html.erb
=> Extract method for link_to_database_search

config/solr_configs/solrconfig.xml
=> Remove unused qf/pf and sort for course reserves

app/javascript/jquery.preview-embed-browse.js
=> cleanup embed browse javascript

app/assets/stylesheets/base.scss, app/assets/stylesheets/modules/brief-view.scss, app/javascript/jquery.preview-brief.js, app/views/catalog/_index_brief.html.erb
=> Remove unnecessary hidden class

spec/fixtures/solr_documents/17.yml, spec/fixtures/solr_documents/18.yml
Same as #3658 but these ones fell through the cracks.
=> Add all_search to remaining fixtures

Gemfile, app/javascript/application.js, app/javascript/jquery.stackmap.js
=> Import leaflet as a module

spec/fixtures/solr_documents/1.yml, spec/fixtures/solr_documents/10.yml, spec/fixtures/solr_documents/4.yml, spec/fixtures/solr_documents/55.yml, spec/fixtures/solr_documents/56.yml
This looks like what we get from the modern indexer
=> Update home_locations in fixture data

app/assets/stylesheets/sul-variables.scss
=> Remove unused sass variable

Gemfile, Gemfile.lock, package.json, yarn.lock
=> Upgrade to turbo-rails 2.0

spec/features/access_panels/library_location_spec.rb, spec/features/brief_view_spec.rb, spec/features/gallery_view_spec.rb, spec/features/stackmap_spec.rb, spec/fixtures/solr_documents/10.yml
=> Rewrite the stackmap spec to test the stackmap interaction

app/assets/stylesheets/modules/managed_purl_panel.scss, app/javascript/jquery.managed-purl.js, app/views/catalog/_managed_purl_embed.html.erb, spec/features/purl_embed_spec.rb
=> Remove hover style for managed purl

Jenkinsfile
=> Deploy `link-decoration` branch to sw-webapp-sandbox-f for UAT

app/views/shared/_top_navbar.html.erb
This may avoid a bunch of Honeybadger errors about unresolved promises.
Ref #3921
=> Disable turbo on the login link
